// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ACTIVESPEAKEROBSERVER_FBS_ACTIVESPEAKEROBSERVER_H_
#define FLATBUFFERS_GENERATED_ACTIVESPEAKEROBSERVER_FBS_ACTIVESPEAKEROBSERVER_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace FBS {
namespace ActiveSpeakerObserver {

struct ActiveSpeakerObserverOptions;
struct ActiveSpeakerObserverOptionsBuilder;
struct ActiveSpeakerObserverOptionsT;

struct DominantSpeakerNotification;
struct DominantSpeakerNotificationBuilder;
struct DominantSpeakerNotificationT;

inline const ::flatbuffers::TypeTable *ActiveSpeakerObserverOptionsTypeTable();

inline const ::flatbuffers::TypeTable *DominantSpeakerNotificationTypeTable();

struct ActiveSpeakerObserverOptionsT : public ::flatbuffers::NativeTable {
  typedef ActiveSpeakerObserverOptions TableType;
  uint16_t interval = 0;
};

struct ActiveSpeakerObserverOptions FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ActiveSpeakerObserverOptionsT NativeTableType;
  typedef ActiveSpeakerObserverOptionsBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return ActiveSpeakerObserverOptionsTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INTERVAL = 4
  };
  uint16_t interval() const {
    return GetField<uint16_t>(VT_INTERVAL, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_INTERVAL, 2) &&
           verifier.EndTable();
  }
  ActiveSpeakerObserverOptionsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ActiveSpeakerObserverOptionsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ActiveSpeakerObserverOptions> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ActiveSpeakerObserverOptionsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ActiveSpeakerObserverOptionsBuilder {
  typedef ActiveSpeakerObserverOptions Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_interval(uint16_t interval) {
    fbb_.AddElement<uint16_t>(ActiveSpeakerObserverOptions::VT_INTERVAL, interval, 0);
  }
  explicit ActiveSpeakerObserverOptionsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ActiveSpeakerObserverOptions> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ActiveSpeakerObserverOptions>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ActiveSpeakerObserverOptions> CreateActiveSpeakerObserverOptions(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t interval = 0) {
  ActiveSpeakerObserverOptionsBuilder builder_(_fbb);
  builder_.add_interval(interval);
  return builder_.Finish();
}

::flatbuffers::Offset<ActiveSpeakerObserverOptions> CreateActiveSpeakerObserverOptions(::flatbuffers::FlatBufferBuilder &_fbb, const ActiveSpeakerObserverOptionsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct DominantSpeakerNotificationT : public ::flatbuffers::NativeTable {
  typedef DominantSpeakerNotification TableType;
  std::string producerId{};
};

struct DominantSpeakerNotification FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DominantSpeakerNotificationT NativeTableType;
  typedef DominantSpeakerNotificationBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return DominantSpeakerNotificationTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PRODUCERID = 4
  };
  const ::flatbuffers::String *producerId() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PRODUCERID);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_PRODUCERID) &&
           verifier.VerifyString(producerId()) &&
           verifier.EndTable();
  }
  DominantSpeakerNotificationT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(DominantSpeakerNotificationT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<DominantSpeakerNotification> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DominantSpeakerNotificationT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct DominantSpeakerNotificationBuilder {
  typedef DominantSpeakerNotification Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_producerId(::flatbuffers::Offset<::flatbuffers::String> producerId) {
    fbb_.AddOffset(DominantSpeakerNotification::VT_PRODUCERID, producerId);
  }
  explicit DominantSpeakerNotificationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DominantSpeakerNotification> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DominantSpeakerNotification>(end);
    fbb_.Required(o, DominantSpeakerNotification::VT_PRODUCERID);
    return o;
  }
};

inline ::flatbuffers::Offset<DominantSpeakerNotification> CreateDominantSpeakerNotification(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> producerId = 0) {
  DominantSpeakerNotificationBuilder builder_(_fbb);
  builder_.add_producerId(producerId);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DominantSpeakerNotification> CreateDominantSpeakerNotificationDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *producerId = nullptr) {
  auto producerId__ = producerId ? _fbb.CreateString(producerId) : 0;
  return FBS::ActiveSpeakerObserver::CreateDominantSpeakerNotification(
      _fbb,
      producerId__);
}

::flatbuffers::Offset<DominantSpeakerNotification> CreateDominantSpeakerNotification(::flatbuffers::FlatBufferBuilder &_fbb, const DominantSpeakerNotificationT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline ActiveSpeakerObserverOptionsT *ActiveSpeakerObserverOptions::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ActiveSpeakerObserverOptionsT>(new ActiveSpeakerObserverOptionsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ActiveSpeakerObserverOptions::UnPackTo(ActiveSpeakerObserverOptionsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = interval(); _o->interval = _e; }
}

inline ::flatbuffers::Offset<ActiveSpeakerObserverOptions> ActiveSpeakerObserverOptions::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ActiveSpeakerObserverOptionsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateActiveSpeakerObserverOptions(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ActiveSpeakerObserverOptions> CreateActiveSpeakerObserverOptions(::flatbuffers::FlatBufferBuilder &_fbb, const ActiveSpeakerObserverOptionsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ActiveSpeakerObserverOptionsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _interval = _o->interval;
  return FBS::ActiveSpeakerObserver::CreateActiveSpeakerObserverOptions(
      _fbb,
      _interval);
}

inline DominantSpeakerNotificationT *DominantSpeakerNotification::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<DominantSpeakerNotificationT>(new DominantSpeakerNotificationT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void DominantSpeakerNotification::UnPackTo(DominantSpeakerNotificationT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = producerId(); if (_e) _o->producerId = _e->str(); }
}

inline ::flatbuffers::Offset<DominantSpeakerNotification> DominantSpeakerNotification::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DominantSpeakerNotificationT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateDominantSpeakerNotification(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<DominantSpeakerNotification> CreateDominantSpeakerNotification(::flatbuffers::FlatBufferBuilder &_fbb, const DominantSpeakerNotificationT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const DominantSpeakerNotificationT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _producerId = _fbb.CreateString(_o->producerId);
  return FBS::ActiveSpeakerObserver::CreateDominantSpeakerNotification(
      _fbb,
      _producerId);
}

inline const ::flatbuffers::TypeTable *ActiveSpeakerObserverOptionsTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_USHORT, 0, -1 }
  };
  static const char * const names[] = {
    "interval"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 1, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *DominantSpeakerNotificationTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 }
  };
  static const char * const names[] = {
    "producerId"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 1, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

}  // namespace ActiveSpeakerObserver
}  // namespace FBS

#endif  // FLATBUFFERS_GENERATED_ACTIVESPEAKEROBSERVER_FBS_ACTIVESPEAKEROBSERVER_H_
