// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DATACONSUMER_FBS_DATACONSUMER_H_
#define FLATBUFFERS_GENERATED_DATACONSUMER_FBS_DATACONSUMER_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "common_generated.h"
#include "dataProducer_generated.h"
#include "sctpParameters_generated.h"

namespace FBS {
namespace DataConsumer {

struct GetBufferedAmountResponse;
struct GetBufferedAmountResponseBuilder;
struct GetBufferedAmountResponseT;

struct SetBufferedAmountLowThresholdRequest;
struct SetBufferedAmountLowThresholdRequestBuilder;
struct SetBufferedAmountLowThresholdRequestT;

struct DumpResponse;
struct DumpResponseBuilder;
struct DumpResponseT;

struct GetStatsResponse;
struct GetStatsResponseBuilder;
struct GetStatsResponseT;

struct SendRequest;
struct SendRequestBuilder;
struct SendRequestT;

struct SetSubchannelsRequest;
struct SetSubchannelsRequestBuilder;
struct SetSubchannelsRequestT;

struct SetSubchannelsResponse;
struct SetSubchannelsResponseBuilder;
struct SetSubchannelsResponseT;

struct AddSubchannelRequest;
struct AddSubchannelRequestBuilder;
struct AddSubchannelRequestT;

struct AddSubchannelResponse;
struct AddSubchannelResponseBuilder;
struct AddSubchannelResponseT;

struct RemoveSubchannelRequest;
struct RemoveSubchannelRequestBuilder;
struct RemoveSubchannelRequestT;

struct RemoveSubchannelResponse;
struct RemoveSubchannelResponseBuilder;
struct RemoveSubchannelResponseT;

struct BufferedAmountLowNotification;
struct BufferedAmountLowNotificationBuilder;
struct BufferedAmountLowNotificationT;

struct MessageNotification;
struct MessageNotificationBuilder;
struct MessageNotificationT;

inline const ::flatbuffers::TypeTable *GetBufferedAmountResponseTypeTable();

inline const ::flatbuffers::TypeTable *SetBufferedAmountLowThresholdRequestTypeTable();

inline const ::flatbuffers::TypeTable *DumpResponseTypeTable();

inline const ::flatbuffers::TypeTable *GetStatsResponseTypeTable();

inline const ::flatbuffers::TypeTable *SendRequestTypeTable();

inline const ::flatbuffers::TypeTable *SetSubchannelsRequestTypeTable();

inline const ::flatbuffers::TypeTable *SetSubchannelsResponseTypeTable();

inline const ::flatbuffers::TypeTable *AddSubchannelRequestTypeTable();

inline const ::flatbuffers::TypeTable *AddSubchannelResponseTypeTable();

inline const ::flatbuffers::TypeTable *RemoveSubchannelRequestTypeTable();

inline const ::flatbuffers::TypeTable *RemoveSubchannelResponseTypeTable();

inline const ::flatbuffers::TypeTable *BufferedAmountLowNotificationTypeTable();

inline const ::flatbuffers::TypeTable *MessageNotificationTypeTable();

struct GetBufferedAmountResponseT : public ::flatbuffers::NativeTable {
  typedef GetBufferedAmountResponse TableType;
  uint32_t bufferedAmount = 0;
};

struct GetBufferedAmountResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GetBufferedAmountResponseT NativeTableType;
  typedef GetBufferedAmountResponseBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return GetBufferedAmountResponseTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BUFFEREDAMOUNT = 4
  };
  uint32_t bufferedAmount() const {
    return GetField<uint32_t>(VT_BUFFEREDAMOUNT, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_BUFFEREDAMOUNT, 4) &&
           verifier.EndTable();
  }
  GetBufferedAmountResponseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(GetBufferedAmountResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<GetBufferedAmountResponse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const GetBufferedAmountResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct GetBufferedAmountResponseBuilder {
  typedef GetBufferedAmountResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_bufferedAmount(uint32_t bufferedAmount) {
    fbb_.AddElement<uint32_t>(GetBufferedAmountResponse::VT_BUFFEREDAMOUNT, bufferedAmount, 0);
  }
  explicit GetBufferedAmountResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GetBufferedAmountResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GetBufferedAmountResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GetBufferedAmountResponse> CreateGetBufferedAmountResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t bufferedAmount = 0) {
  GetBufferedAmountResponseBuilder builder_(_fbb);
  builder_.add_bufferedAmount(bufferedAmount);
  return builder_.Finish();
}

::flatbuffers::Offset<GetBufferedAmountResponse> CreateGetBufferedAmountResponse(::flatbuffers::FlatBufferBuilder &_fbb, const GetBufferedAmountResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SetBufferedAmountLowThresholdRequestT : public ::flatbuffers::NativeTable {
  typedef SetBufferedAmountLowThresholdRequest TableType;
  uint32_t threshold = 0;
};

struct SetBufferedAmountLowThresholdRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SetBufferedAmountLowThresholdRequestT NativeTableType;
  typedef SetBufferedAmountLowThresholdRequestBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return SetBufferedAmountLowThresholdRequestTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_THRESHOLD = 4
  };
  uint32_t threshold() const {
    return GetField<uint32_t>(VT_THRESHOLD, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_THRESHOLD, 4) &&
           verifier.EndTable();
  }
  SetBufferedAmountLowThresholdRequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SetBufferedAmountLowThresholdRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SetBufferedAmountLowThresholdRequest> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SetBufferedAmountLowThresholdRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SetBufferedAmountLowThresholdRequestBuilder {
  typedef SetBufferedAmountLowThresholdRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_threshold(uint32_t threshold) {
    fbb_.AddElement<uint32_t>(SetBufferedAmountLowThresholdRequest::VT_THRESHOLD, threshold, 0);
  }
  explicit SetBufferedAmountLowThresholdRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SetBufferedAmountLowThresholdRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SetBufferedAmountLowThresholdRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SetBufferedAmountLowThresholdRequest> CreateSetBufferedAmountLowThresholdRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t threshold = 0) {
  SetBufferedAmountLowThresholdRequestBuilder builder_(_fbb);
  builder_.add_threshold(threshold);
  return builder_.Finish();
}

::flatbuffers::Offset<SetBufferedAmountLowThresholdRequest> CreateSetBufferedAmountLowThresholdRequest(::flatbuffers::FlatBufferBuilder &_fbb, const SetBufferedAmountLowThresholdRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct DumpResponseT : public ::flatbuffers::NativeTable {
  typedef DumpResponse TableType;
  std::string id{};
  std::string dataProducerId{};
  FBS::DataProducer::Type type = FBS::DataProducer::Type::SCTP;
  std::unique_ptr<FBS::SctpParameters::SctpStreamParametersT> sctpStreamParameters{};
  std::string label{};
  std::string protocol{};
  uint32_t bufferedAmountLowThreshold = 0;
  bool paused = false;
  bool dataProducerPaused = false;
  std::vector<uint16_t> subchannels{};
  DumpResponseT() = default;
  DumpResponseT(const DumpResponseT &o);
  DumpResponseT(DumpResponseT&&) FLATBUFFERS_NOEXCEPT = default;
  DumpResponseT &operator=(DumpResponseT o) FLATBUFFERS_NOEXCEPT;
};

struct DumpResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DumpResponseT NativeTableType;
  typedef DumpResponseBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return DumpResponseTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_DATAPRODUCERID = 6,
    VT_TYPE = 8,
    VT_SCTPSTREAMPARAMETERS = 10,
    VT_LABEL = 12,
    VT_PROTOCOL = 14,
    VT_BUFFEREDAMOUNTLOWTHRESHOLD = 16,
    VT_PAUSED = 18,
    VT_DATAPRODUCERPAUSED = 20,
    VT_SUBCHANNELS = 22
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const ::flatbuffers::String *dataProducerId() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DATAPRODUCERID);
  }
  FBS::DataProducer::Type type() const {
    return static_cast<FBS::DataProducer::Type>(GetField<uint8_t>(VT_TYPE, 0));
  }
  const FBS::SctpParameters::SctpStreamParameters *sctpStreamParameters() const {
    return GetPointer<const FBS::SctpParameters::SctpStreamParameters *>(VT_SCTPSTREAMPARAMETERS);
  }
  const ::flatbuffers::String *label() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LABEL);
  }
  const ::flatbuffers::String *protocol() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PROTOCOL);
  }
  uint32_t bufferedAmountLowThreshold() const {
    return GetField<uint32_t>(VT_BUFFEREDAMOUNTLOWTHRESHOLD, 0);
  }
  bool paused() const {
    return GetField<uint8_t>(VT_PAUSED, 0) != 0;
  }
  bool dataProducerPaused() const {
    return GetField<uint8_t>(VT_DATAPRODUCERPAUSED, 0) != 0;
  }
  const ::flatbuffers::Vector<uint16_t> *subchannels() const {
    return GetPointer<const ::flatbuffers::Vector<uint16_t> *>(VT_SUBCHANNELS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffsetRequired(verifier, VT_DATAPRODUCERID) &&
           verifier.VerifyString(dataProducerId()) &&
           VerifyField<uint8_t>(verifier, VT_TYPE, 1) &&
           VerifyOffset(verifier, VT_SCTPSTREAMPARAMETERS) &&
           verifier.VerifyTable(sctpStreamParameters()) &&
           VerifyOffsetRequired(verifier, VT_LABEL) &&
           verifier.VerifyString(label()) &&
           VerifyOffsetRequired(verifier, VT_PROTOCOL) &&
           verifier.VerifyString(protocol()) &&
           VerifyField<uint32_t>(verifier, VT_BUFFEREDAMOUNTLOWTHRESHOLD, 4) &&
           VerifyField<uint8_t>(verifier, VT_PAUSED, 1) &&
           VerifyField<uint8_t>(verifier, VT_DATAPRODUCERPAUSED, 1) &&
           VerifyOffsetRequired(verifier, VT_SUBCHANNELS) &&
           verifier.VerifyVector(subchannels()) &&
           verifier.EndTable();
  }
  DumpResponseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(DumpResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<DumpResponse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DumpResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct DumpResponseBuilder {
  typedef DumpResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(DumpResponse::VT_ID, id);
  }
  void add_dataProducerId(::flatbuffers::Offset<::flatbuffers::String> dataProducerId) {
    fbb_.AddOffset(DumpResponse::VT_DATAPRODUCERID, dataProducerId);
  }
  void add_type(FBS::DataProducer::Type type) {
    fbb_.AddElement<uint8_t>(DumpResponse::VT_TYPE, static_cast<uint8_t>(type), 0);
  }
  void add_sctpStreamParameters(::flatbuffers::Offset<FBS::SctpParameters::SctpStreamParameters> sctpStreamParameters) {
    fbb_.AddOffset(DumpResponse::VT_SCTPSTREAMPARAMETERS, sctpStreamParameters);
  }
  void add_label(::flatbuffers::Offset<::flatbuffers::String> label) {
    fbb_.AddOffset(DumpResponse::VT_LABEL, label);
  }
  void add_protocol(::flatbuffers::Offset<::flatbuffers::String> protocol) {
    fbb_.AddOffset(DumpResponse::VT_PROTOCOL, protocol);
  }
  void add_bufferedAmountLowThreshold(uint32_t bufferedAmountLowThreshold) {
    fbb_.AddElement<uint32_t>(DumpResponse::VT_BUFFEREDAMOUNTLOWTHRESHOLD, bufferedAmountLowThreshold, 0);
  }
  void add_paused(bool paused) {
    fbb_.AddElement<uint8_t>(DumpResponse::VT_PAUSED, static_cast<uint8_t>(paused), 0);
  }
  void add_dataProducerPaused(bool dataProducerPaused) {
    fbb_.AddElement<uint8_t>(DumpResponse::VT_DATAPRODUCERPAUSED, static_cast<uint8_t>(dataProducerPaused), 0);
  }
  void add_subchannels(::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> subchannels) {
    fbb_.AddOffset(DumpResponse::VT_SUBCHANNELS, subchannels);
  }
  explicit DumpResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DumpResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DumpResponse>(end);
    fbb_.Required(o, DumpResponse::VT_ID);
    fbb_.Required(o, DumpResponse::VT_DATAPRODUCERID);
    fbb_.Required(o, DumpResponse::VT_LABEL);
    fbb_.Required(o, DumpResponse::VT_PROTOCOL);
    fbb_.Required(o, DumpResponse::VT_SUBCHANNELS);
    return o;
  }
};

inline ::flatbuffers::Offset<DumpResponse> CreateDumpResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> dataProducerId = 0,
    FBS::DataProducer::Type type = FBS::DataProducer::Type::SCTP,
    ::flatbuffers::Offset<FBS::SctpParameters::SctpStreamParameters> sctpStreamParameters = 0,
    ::flatbuffers::Offset<::flatbuffers::String> label = 0,
    ::flatbuffers::Offset<::flatbuffers::String> protocol = 0,
    uint32_t bufferedAmountLowThreshold = 0,
    bool paused = false,
    bool dataProducerPaused = false,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> subchannels = 0) {
  DumpResponseBuilder builder_(_fbb);
  builder_.add_subchannels(subchannels);
  builder_.add_bufferedAmountLowThreshold(bufferedAmountLowThreshold);
  builder_.add_protocol(protocol);
  builder_.add_label(label);
  builder_.add_sctpStreamParameters(sctpStreamParameters);
  builder_.add_dataProducerId(dataProducerId);
  builder_.add_id(id);
  builder_.add_dataProducerPaused(dataProducerPaused);
  builder_.add_paused(paused);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DumpResponse> CreateDumpResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *dataProducerId = nullptr,
    FBS::DataProducer::Type type = FBS::DataProducer::Type::SCTP,
    ::flatbuffers::Offset<FBS::SctpParameters::SctpStreamParameters> sctpStreamParameters = 0,
    const char *label = nullptr,
    const char *protocol = nullptr,
    uint32_t bufferedAmountLowThreshold = 0,
    bool paused = false,
    bool dataProducerPaused = false,
    const std::vector<uint16_t> *subchannels = nullptr) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto dataProducerId__ = dataProducerId ? _fbb.CreateString(dataProducerId) : 0;
  auto label__ = label ? _fbb.CreateString(label) : 0;
  auto protocol__ = protocol ? _fbb.CreateString(protocol) : 0;
  auto subchannels__ = subchannels ? _fbb.CreateVector<uint16_t>(*subchannels) : 0;
  return FBS::DataConsumer::CreateDumpResponse(
      _fbb,
      id__,
      dataProducerId__,
      type,
      sctpStreamParameters,
      label__,
      protocol__,
      bufferedAmountLowThreshold,
      paused,
      dataProducerPaused,
      subchannels__);
}

::flatbuffers::Offset<DumpResponse> CreateDumpResponse(::flatbuffers::FlatBufferBuilder &_fbb, const DumpResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct GetStatsResponseT : public ::flatbuffers::NativeTable {
  typedef GetStatsResponse TableType;
  uint64_t timestamp = 0;
  std::string label{};
  std::string protocol{};
  uint64_t messagesSent = 0;
  uint64_t bytesSent = 0;
  uint32_t bufferedAmount = 0;
};

struct GetStatsResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GetStatsResponseT NativeTableType;
  typedef GetStatsResponseBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return GetStatsResponseTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTAMP = 4,
    VT_LABEL = 6,
    VT_PROTOCOL = 8,
    VT_MESSAGESSENT = 10,
    VT_BYTESSENT = 12,
    VT_BUFFEREDAMOUNT = 14
  };
  uint64_t timestamp() const {
    return GetField<uint64_t>(VT_TIMESTAMP, 0);
  }
  const ::flatbuffers::String *label() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LABEL);
  }
  const ::flatbuffers::String *protocol() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PROTOCOL);
  }
  uint64_t messagesSent() const {
    return GetField<uint64_t>(VT_MESSAGESSENT, 0);
  }
  uint64_t bytesSent() const {
    return GetField<uint64_t>(VT_BYTESSENT, 0);
  }
  uint32_t bufferedAmount() const {
    return GetField<uint32_t>(VT_BUFFEREDAMOUNT, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP, 8) &&
           VerifyOffsetRequired(verifier, VT_LABEL) &&
           verifier.VerifyString(label()) &&
           VerifyOffsetRequired(verifier, VT_PROTOCOL) &&
           verifier.VerifyString(protocol()) &&
           VerifyField<uint64_t>(verifier, VT_MESSAGESSENT, 8) &&
           VerifyField<uint64_t>(verifier, VT_BYTESSENT, 8) &&
           VerifyField<uint32_t>(verifier, VT_BUFFEREDAMOUNT, 4) &&
           verifier.EndTable();
  }
  GetStatsResponseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(GetStatsResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<GetStatsResponse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const GetStatsResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct GetStatsResponseBuilder {
  typedef GetStatsResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_timestamp(uint64_t timestamp) {
    fbb_.AddElement<uint64_t>(GetStatsResponse::VT_TIMESTAMP, timestamp, 0);
  }
  void add_label(::flatbuffers::Offset<::flatbuffers::String> label) {
    fbb_.AddOffset(GetStatsResponse::VT_LABEL, label);
  }
  void add_protocol(::flatbuffers::Offset<::flatbuffers::String> protocol) {
    fbb_.AddOffset(GetStatsResponse::VT_PROTOCOL, protocol);
  }
  void add_messagesSent(uint64_t messagesSent) {
    fbb_.AddElement<uint64_t>(GetStatsResponse::VT_MESSAGESSENT, messagesSent, 0);
  }
  void add_bytesSent(uint64_t bytesSent) {
    fbb_.AddElement<uint64_t>(GetStatsResponse::VT_BYTESSENT, bytesSent, 0);
  }
  void add_bufferedAmount(uint32_t bufferedAmount) {
    fbb_.AddElement<uint32_t>(GetStatsResponse::VT_BUFFEREDAMOUNT, bufferedAmount, 0);
  }
  explicit GetStatsResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GetStatsResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GetStatsResponse>(end);
    fbb_.Required(o, GetStatsResponse::VT_LABEL);
    fbb_.Required(o, GetStatsResponse::VT_PROTOCOL);
    return o;
  }
};

inline ::flatbuffers::Offset<GetStatsResponse> CreateGetStatsResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t timestamp = 0,
    ::flatbuffers::Offset<::flatbuffers::String> label = 0,
    ::flatbuffers::Offset<::flatbuffers::String> protocol = 0,
    uint64_t messagesSent = 0,
    uint64_t bytesSent = 0,
    uint32_t bufferedAmount = 0) {
  GetStatsResponseBuilder builder_(_fbb);
  builder_.add_bytesSent(bytesSent);
  builder_.add_messagesSent(messagesSent);
  builder_.add_timestamp(timestamp);
  builder_.add_bufferedAmount(bufferedAmount);
  builder_.add_protocol(protocol);
  builder_.add_label(label);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<GetStatsResponse> CreateGetStatsResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t timestamp = 0,
    const char *label = nullptr,
    const char *protocol = nullptr,
    uint64_t messagesSent = 0,
    uint64_t bytesSent = 0,
    uint32_t bufferedAmount = 0) {
  auto label__ = label ? _fbb.CreateString(label) : 0;
  auto protocol__ = protocol ? _fbb.CreateString(protocol) : 0;
  return FBS::DataConsumer::CreateGetStatsResponse(
      _fbb,
      timestamp,
      label__,
      protocol__,
      messagesSent,
      bytesSent,
      bufferedAmount);
}

::flatbuffers::Offset<GetStatsResponse> CreateGetStatsResponse(::flatbuffers::FlatBufferBuilder &_fbb, const GetStatsResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SendRequestT : public ::flatbuffers::NativeTable {
  typedef SendRequest TableType;
  uint32_t ppid = 0;
  std::vector<uint8_t> data{};
};

struct SendRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SendRequestT NativeTableType;
  typedef SendRequestBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return SendRequestTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PPID = 4,
    VT_DATA = 6
  };
  uint32_t ppid() const {
    return GetField<uint32_t>(VT_PPID, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_PPID, 4) &&
           VerifyOffsetRequired(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           verifier.EndTable();
  }
  SendRequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SendRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SendRequest> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SendRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SendRequestBuilder {
  typedef SendRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_ppid(uint32_t ppid) {
    fbb_.AddElement<uint32_t>(SendRequest::VT_PPID, ppid, 0);
  }
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data) {
    fbb_.AddOffset(SendRequest::VT_DATA, data);
  }
  explicit SendRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SendRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SendRequest>(end);
    fbb_.Required(o, SendRequest::VT_DATA);
    return o;
  }
};

inline ::flatbuffers::Offset<SendRequest> CreateSendRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t ppid = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data = 0) {
  SendRequestBuilder builder_(_fbb);
  builder_.add_data(data);
  builder_.add_ppid(ppid);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SendRequest> CreateSendRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t ppid = 0,
    const std::vector<uint8_t> *data = nullptr) {
  auto data__ = data ? _fbb.CreateVector<uint8_t>(*data) : 0;
  return FBS::DataConsumer::CreateSendRequest(
      _fbb,
      ppid,
      data__);
}

::flatbuffers::Offset<SendRequest> CreateSendRequest(::flatbuffers::FlatBufferBuilder &_fbb, const SendRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SetSubchannelsRequestT : public ::flatbuffers::NativeTable {
  typedef SetSubchannelsRequest TableType;
  std::vector<uint16_t> subchannels{};
};

struct SetSubchannelsRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SetSubchannelsRequestT NativeTableType;
  typedef SetSubchannelsRequestBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return SetSubchannelsRequestTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SUBCHANNELS = 4
  };
  const ::flatbuffers::Vector<uint16_t> *subchannels() const {
    return GetPointer<const ::flatbuffers::Vector<uint16_t> *>(VT_SUBCHANNELS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_SUBCHANNELS) &&
           verifier.VerifyVector(subchannels()) &&
           verifier.EndTable();
  }
  SetSubchannelsRequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SetSubchannelsRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SetSubchannelsRequest> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SetSubchannelsRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SetSubchannelsRequestBuilder {
  typedef SetSubchannelsRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_subchannels(::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> subchannels) {
    fbb_.AddOffset(SetSubchannelsRequest::VT_SUBCHANNELS, subchannels);
  }
  explicit SetSubchannelsRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SetSubchannelsRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SetSubchannelsRequest>(end);
    fbb_.Required(o, SetSubchannelsRequest::VT_SUBCHANNELS);
    return o;
  }
};

inline ::flatbuffers::Offset<SetSubchannelsRequest> CreateSetSubchannelsRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> subchannels = 0) {
  SetSubchannelsRequestBuilder builder_(_fbb);
  builder_.add_subchannels(subchannels);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SetSubchannelsRequest> CreateSetSubchannelsRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint16_t> *subchannels = nullptr) {
  auto subchannels__ = subchannels ? _fbb.CreateVector<uint16_t>(*subchannels) : 0;
  return FBS::DataConsumer::CreateSetSubchannelsRequest(
      _fbb,
      subchannels__);
}

::flatbuffers::Offset<SetSubchannelsRequest> CreateSetSubchannelsRequest(::flatbuffers::FlatBufferBuilder &_fbb, const SetSubchannelsRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SetSubchannelsResponseT : public ::flatbuffers::NativeTable {
  typedef SetSubchannelsResponse TableType;
  std::vector<uint16_t> subchannels{};
};

struct SetSubchannelsResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SetSubchannelsResponseT NativeTableType;
  typedef SetSubchannelsResponseBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return SetSubchannelsResponseTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SUBCHANNELS = 4
  };
  const ::flatbuffers::Vector<uint16_t> *subchannels() const {
    return GetPointer<const ::flatbuffers::Vector<uint16_t> *>(VT_SUBCHANNELS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_SUBCHANNELS) &&
           verifier.VerifyVector(subchannels()) &&
           verifier.EndTable();
  }
  SetSubchannelsResponseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SetSubchannelsResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SetSubchannelsResponse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SetSubchannelsResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SetSubchannelsResponseBuilder {
  typedef SetSubchannelsResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_subchannels(::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> subchannels) {
    fbb_.AddOffset(SetSubchannelsResponse::VT_SUBCHANNELS, subchannels);
  }
  explicit SetSubchannelsResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SetSubchannelsResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SetSubchannelsResponse>(end);
    fbb_.Required(o, SetSubchannelsResponse::VT_SUBCHANNELS);
    return o;
  }
};

inline ::flatbuffers::Offset<SetSubchannelsResponse> CreateSetSubchannelsResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> subchannels = 0) {
  SetSubchannelsResponseBuilder builder_(_fbb);
  builder_.add_subchannels(subchannels);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SetSubchannelsResponse> CreateSetSubchannelsResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint16_t> *subchannels = nullptr) {
  auto subchannels__ = subchannels ? _fbb.CreateVector<uint16_t>(*subchannels) : 0;
  return FBS::DataConsumer::CreateSetSubchannelsResponse(
      _fbb,
      subchannels__);
}

::flatbuffers::Offset<SetSubchannelsResponse> CreateSetSubchannelsResponse(::flatbuffers::FlatBufferBuilder &_fbb, const SetSubchannelsResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct AddSubchannelRequestT : public ::flatbuffers::NativeTable {
  typedef AddSubchannelRequest TableType;
  uint16_t subchannel = 0;
};

struct AddSubchannelRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AddSubchannelRequestT NativeTableType;
  typedef AddSubchannelRequestBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return AddSubchannelRequestTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SUBCHANNEL = 4
  };
  uint16_t subchannel() const {
    return GetField<uint16_t>(VT_SUBCHANNEL, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_SUBCHANNEL, 2) &&
           verifier.EndTable();
  }
  AddSubchannelRequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(AddSubchannelRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<AddSubchannelRequest> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const AddSubchannelRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct AddSubchannelRequestBuilder {
  typedef AddSubchannelRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_subchannel(uint16_t subchannel) {
    fbb_.AddElement<uint16_t>(AddSubchannelRequest::VT_SUBCHANNEL, subchannel, 0);
  }
  explicit AddSubchannelRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AddSubchannelRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AddSubchannelRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AddSubchannelRequest> CreateAddSubchannelRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t subchannel = 0) {
  AddSubchannelRequestBuilder builder_(_fbb);
  builder_.add_subchannel(subchannel);
  return builder_.Finish();
}

::flatbuffers::Offset<AddSubchannelRequest> CreateAddSubchannelRequest(::flatbuffers::FlatBufferBuilder &_fbb, const AddSubchannelRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct AddSubchannelResponseT : public ::flatbuffers::NativeTable {
  typedef AddSubchannelResponse TableType;
  std::vector<uint16_t> subchannels{};
};

struct AddSubchannelResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AddSubchannelResponseT NativeTableType;
  typedef AddSubchannelResponseBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return AddSubchannelResponseTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SUBCHANNELS = 4
  };
  const ::flatbuffers::Vector<uint16_t> *subchannels() const {
    return GetPointer<const ::flatbuffers::Vector<uint16_t> *>(VT_SUBCHANNELS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_SUBCHANNELS) &&
           verifier.VerifyVector(subchannels()) &&
           verifier.EndTable();
  }
  AddSubchannelResponseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(AddSubchannelResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<AddSubchannelResponse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const AddSubchannelResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct AddSubchannelResponseBuilder {
  typedef AddSubchannelResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_subchannels(::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> subchannels) {
    fbb_.AddOffset(AddSubchannelResponse::VT_SUBCHANNELS, subchannels);
  }
  explicit AddSubchannelResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AddSubchannelResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AddSubchannelResponse>(end);
    fbb_.Required(o, AddSubchannelResponse::VT_SUBCHANNELS);
    return o;
  }
};

inline ::flatbuffers::Offset<AddSubchannelResponse> CreateAddSubchannelResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> subchannels = 0) {
  AddSubchannelResponseBuilder builder_(_fbb);
  builder_.add_subchannels(subchannels);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AddSubchannelResponse> CreateAddSubchannelResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint16_t> *subchannels = nullptr) {
  auto subchannels__ = subchannels ? _fbb.CreateVector<uint16_t>(*subchannels) : 0;
  return FBS::DataConsumer::CreateAddSubchannelResponse(
      _fbb,
      subchannels__);
}

::flatbuffers::Offset<AddSubchannelResponse> CreateAddSubchannelResponse(::flatbuffers::FlatBufferBuilder &_fbb, const AddSubchannelResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct RemoveSubchannelRequestT : public ::flatbuffers::NativeTable {
  typedef RemoveSubchannelRequest TableType;
  uint16_t subchannel = 0;
};

struct RemoveSubchannelRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RemoveSubchannelRequestT NativeTableType;
  typedef RemoveSubchannelRequestBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return RemoveSubchannelRequestTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SUBCHANNEL = 4
  };
  uint16_t subchannel() const {
    return GetField<uint16_t>(VT_SUBCHANNEL, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_SUBCHANNEL, 2) &&
           verifier.EndTable();
  }
  RemoveSubchannelRequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(RemoveSubchannelRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<RemoveSubchannelRequest> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RemoveSubchannelRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct RemoveSubchannelRequestBuilder {
  typedef RemoveSubchannelRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_subchannel(uint16_t subchannel) {
    fbb_.AddElement<uint16_t>(RemoveSubchannelRequest::VT_SUBCHANNEL, subchannel, 0);
  }
  explicit RemoveSubchannelRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RemoveSubchannelRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RemoveSubchannelRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RemoveSubchannelRequest> CreateRemoveSubchannelRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t subchannel = 0) {
  RemoveSubchannelRequestBuilder builder_(_fbb);
  builder_.add_subchannel(subchannel);
  return builder_.Finish();
}

::flatbuffers::Offset<RemoveSubchannelRequest> CreateRemoveSubchannelRequest(::flatbuffers::FlatBufferBuilder &_fbb, const RemoveSubchannelRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct RemoveSubchannelResponseT : public ::flatbuffers::NativeTable {
  typedef RemoveSubchannelResponse TableType;
  std::vector<uint16_t> subchannels{};
};

struct RemoveSubchannelResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RemoveSubchannelResponseT NativeTableType;
  typedef RemoveSubchannelResponseBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return RemoveSubchannelResponseTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SUBCHANNELS = 4
  };
  const ::flatbuffers::Vector<uint16_t> *subchannels() const {
    return GetPointer<const ::flatbuffers::Vector<uint16_t> *>(VT_SUBCHANNELS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_SUBCHANNELS) &&
           verifier.VerifyVector(subchannels()) &&
           verifier.EndTable();
  }
  RemoveSubchannelResponseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(RemoveSubchannelResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<RemoveSubchannelResponse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RemoveSubchannelResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct RemoveSubchannelResponseBuilder {
  typedef RemoveSubchannelResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_subchannels(::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> subchannels) {
    fbb_.AddOffset(RemoveSubchannelResponse::VT_SUBCHANNELS, subchannels);
  }
  explicit RemoveSubchannelResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RemoveSubchannelResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RemoveSubchannelResponse>(end);
    fbb_.Required(o, RemoveSubchannelResponse::VT_SUBCHANNELS);
    return o;
  }
};

inline ::flatbuffers::Offset<RemoveSubchannelResponse> CreateRemoveSubchannelResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> subchannels = 0) {
  RemoveSubchannelResponseBuilder builder_(_fbb);
  builder_.add_subchannels(subchannels);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<RemoveSubchannelResponse> CreateRemoveSubchannelResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint16_t> *subchannels = nullptr) {
  auto subchannels__ = subchannels ? _fbb.CreateVector<uint16_t>(*subchannels) : 0;
  return FBS::DataConsumer::CreateRemoveSubchannelResponse(
      _fbb,
      subchannels__);
}

::flatbuffers::Offset<RemoveSubchannelResponse> CreateRemoveSubchannelResponse(::flatbuffers::FlatBufferBuilder &_fbb, const RemoveSubchannelResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct BufferedAmountLowNotificationT : public ::flatbuffers::NativeTable {
  typedef BufferedAmountLowNotification TableType;
  uint32_t bufferedAmount = 0;
};

struct BufferedAmountLowNotification FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BufferedAmountLowNotificationT NativeTableType;
  typedef BufferedAmountLowNotificationBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return BufferedAmountLowNotificationTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BUFFEREDAMOUNT = 4
  };
  uint32_t bufferedAmount() const {
    return GetField<uint32_t>(VT_BUFFEREDAMOUNT, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_BUFFEREDAMOUNT, 4) &&
           verifier.EndTable();
  }
  BufferedAmountLowNotificationT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(BufferedAmountLowNotificationT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<BufferedAmountLowNotification> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BufferedAmountLowNotificationT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct BufferedAmountLowNotificationBuilder {
  typedef BufferedAmountLowNotification Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_bufferedAmount(uint32_t bufferedAmount) {
    fbb_.AddElement<uint32_t>(BufferedAmountLowNotification::VT_BUFFEREDAMOUNT, bufferedAmount, 0);
  }
  explicit BufferedAmountLowNotificationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BufferedAmountLowNotification> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BufferedAmountLowNotification>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BufferedAmountLowNotification> CreateBufferedAmountLowNotification(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t bufferedAmount = 0) {
  BufferedAmountLowNotificationBuilder builder_(_fbb);
  builder_.add_bufferedAmount(bufferedAmount);
  return builder_.Finish();
}

::flatbuffers::Offset<BufferedAmountLowNotification> CreateBufferedAmountLowNotification(::flatbuffers::FlatBufferBuilder &_fbb, const BufferedAmountLowNotificationT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct MessageNotificationT : public ::flatbuffers::NativeTable {
  typedef MessageNotification TableType;
  uint32_t ppid = 0;
  std::vector<uint8_t> data{};
};

struct MessageNotification FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MessageNotificationT NativeTableType;
  typedef MessageNotificationBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return MessageNotificationTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PPID = 4,
    VT_DATA = 6
  };
  uint32_t ppid() const {
    return GetField<uint32_t>(VT_PPID, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_PPID, 4) &&
           VerifyOffsetRequired(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           verifier.EndTable();
  }
  MessageNotificationT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(MessageNotificationT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<MessageNotification> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MessageNotificationT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct MessageNotificationBuilder {
  typedef MessageNotification Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_ppid(uint32_t ppid) {
    fbb_.AddElement<uint32_t>(MessageNotification::VT_PPID, ppid, 0);
  }
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data) {
    fbb_.AddOffset(MessageNotification::VT_DATA, data);
  }
  explicit MessageNotificationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MessageNotification> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MessageNotification>(end);
    fbb_.Required(o, MessageNotification::VT_DATA);
    return o;
  }
};

inline ::flatbuffers::Offset<MessageNotification> CreateMessageNotification(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t ppid = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data = 0) {
  MessageNotificationBuilder builder_(_fbb);
  builder_.add_data(data);
  builder_.add_ppid(ppid);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MessageNotification> CreateMessageNotificationDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t ppid = 0,
    const std::vector<uint8_t> *data = nullptr) {
  auto data__ = data ? _fbb.CreateVector<uint8_t>(*data) : 0;
  return FBS::DataConsumer::CreateMessageNotification(
      _fbb,
      ppid,
      data__);
}

::flatbuffers::Offset<MessageNotification> CreateMessageNotification(::flatbuffers::FlatBufferBuilder &_fbb, const MessageNotificationT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline GetBufferedAmountResponseT *GetBufferedAmountResponse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<GetBufferedAmountResponseT>(new GetBufferedAmountResponseT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void GetBufferedAmountResponse::UnPackTo(GetBufferedAmountResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = bufferedAmount(); _o->bufferedAmount = _e; }
}

inline ::flatbuffers::Offset<GetBufferedAmountResponse> GetBufferedAmountResponse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const GetBufferedAmountResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateGetBufferedAmountResponse(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<GetBufferedAmountResponse> CreateGetBufferedAmountResponse(::flatbuffers::FlatBufferBuilder &_fbb, const GetBufferedAmountResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const GetBufferedAmountResponseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _bufferedAmount = _o->bufferedAmount;
  return FBS::DataConsumer::CreateGetBufferedAmountResponse(
      _fbb,
      _bufferedAmount);
}

inline SetBufferedAmountLowThresholdRequestT *SetBufferedAmountLowThresholdRequest::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SetBufferedAmountLowThresholdRequestT>(new SetBufferedAmountLowThresholdRequestT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SetBufferedAmountLowThresholdRequest::UnPackTo(SetBufferedAmountLowThresholdRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = threshold(); _o->threshold = _e; }
}

inline ::flatbuffers::Offset<SetBufferedAmountLowThresholdRequest> SetBufferedAmountLowThresholdRequest::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SetBufferedAmountLowThresholdRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSetBufferedAmountLowThresholdRequest(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SetBufferedAmountLowThresholdRequest> CreateSetBufferedAmountLowThresholdRequest(::flatbuffers::FlatBufferBuilder &_fbb, const SetBufferedAmountLowThresholdRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SetBufferedAmountLowThresholdRequestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _threshold = _o->threshold;
  return FBS::DataConsumer::CreateSetBufferedAmountLowThresholdRequest(
      _fbb,
      _threshold);
}

inline DumpResponseT::DumpResponseT(const DumpResponseT &o)
      : id(o.id),
        dataProducerId(o.dataProducerId),
        type(o.type),
        sctpStreamParameters((o.sctpStreamParameters) ? new FBS::SctpParameters::SctpStreamParametersT(*o.sctpStreamParameters) : nullptr),
        label(o.label),
        protocol(o.protocol),
        bufferedAmountLowThreshold(o.bufferedAmountLowThreshold),
        paused(o.paused),
        dataProducerPaused(o.dataProducerPaused),
        subchannels(o.subchannels) {
}

inline DumpResponseT &DumpResponseT::operator=(DumpResponseT o) FLATBUFFERS_NOEXCEPT {
  std::swap(id, o.id);
  std::swap(dataProducerId, o.dataProducerId);
  std::swap(type, o.type);
  std::swap(sctpStreamParameters, o.sctpStreamParameters);
  std::swap(label, o.label);
  std::swap(protocol, o.protocol);
  std::swap(bufferedAmountLowThreshold, o.bufferedAmountLowThreshold);
  std::swap(paused, o.paused);
  std::swap(dataProducerPaused, o.dataProducerPaused);
  std::swap(subchannels, o.subchannels);
  return *this;
}

inline DumpResponseT *DumpResponse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<DumpResponseT>(new DumpResponseT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void DumpResponse::UnPackTo(DumpResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = id(); if (_e) _o->id = _e->str(); }
  { auto _e = dataProducerId(); if (_e) _o->dataProducerId = _e->str(); }
  { auto _e = type(); _o->type = _e; }
  { auto _e = sctpStreamParameters(); if (_e) { if(_o->sctpStreamParameters) { _e->UnPackTo(_o->sctpStreamParameters.get(), _resolver); } else { _o->sctpStreamParameters = std::unique_ptr<FBS::SctpParameters::SctpStreamParametersT>(_e->UnPack(_resolver)); } } else if (_o->sctpStreamParameters) { _o->sctpStreamParameters.reset(); } }
  { auto _e = label(); if (_e) _o->label = _e->str(); }
  { auto _e = protocol(); if (_e) _o->protocol = _e->str(); }
  { auto _e = bufferedAmountLowThreshold(); _o->bufferedAmountLowThreshold = _e; }
  { auto _e = paused(); _o->paused = _e; }
  { auto _e = dataProducerPaused(); _o->dataProducerPaused = _e; }
  { auto _e = subchannels(); if (_e) { _o->subchannels.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->subchannels[_i] = _e->Get(_i); } } else { _o->subchannels.resize(0); } }
}

inline ::flatbuffers::Offset<DumpResponse> DumpResponse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DumpResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateDumpResponse(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<DumpResponse> CreateDumpResponse(::flatbuffers::FlatBufferBuilder &_fbb, const DumpResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const DumpResponseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _id = _fbb.CreateString(_o->id);
  auto _dataProducerId = _fbb.CreateString(_o->dataProducerId);
  auto _type = _o->type;
  auto _sctpStreamParameters = _o->sctpStreamParameters ? CreateSctpStreamParameters(_fbb, _o->sctpStreamParameters.get(), _rehasher) : 0;
  auto _label = _fbb.CreateString(_o->label);
  auto _protocol = _fbb.CreateString(_o->protocol);
  auto _bufferedAmountLowThreshold = _o->bufferedAmountLowThreshold;
  auto _paused = _o->paused;
  auto _dataProducerPaused = _o->dataProducerPaused;
  auto _subchannels = _fbb.CreateVector(_o->subchannels);
  return FBS::DataConsumer::CreateDumpResponse(
      _fbb,
      _id,
      _dataProducerId,
      _type,
      _sctpStreamParameters,
      _label,
      _protocol,
      _bufferedAmountLowThreshold,
      _paused,
      _dataProducerPaused,
      _subchannels);
}

inline GetStatsResponseT *GetStatsResponse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<GetStatsResponseT>(new GetStatsResponseT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void GetStatsResponse::UnPackTo(GetStatsResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = timestamp(); _o->timestamp = _e; }
  { auto _e = label(); if (_e) _o->label = _e->str(); }
  { auto _e = protocol(); if (_e) _o->protocol = _e->str(); }
  { auto _e = messagesSent(); _o->messagesSent = _e; }
  { auto _e = bytesSent(); _o->bytesSent = _e; }
  { auto _e = bufferedAmount(); _o->bufferedAmount = _e; }
}

inline ::flatbuffers::Offset<GetStatsResponse> GetStatsResponse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const GetStatsResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateGetStatsResponse(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<GetStatsResponse> CreateGetStatsResponse(::flatbuffers::FlatBufferBuilder &_fbb, const GetStatsResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const GetStatsResponseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _timestamp = _o->timestamp;
  auto _label = _fbb.CreateString(_o->label);
  auto _protocol = _fbb.CreateString(_o->protocol);
  auto _messagesSent = _o->messagesSent;
  auto _bytesSent = _o->bytesSent;
  auto _bufferedAmount = _o->bufferedAmount;
  return FBS::DataConsumer::CreateGetStatsResponse(
      _fbb,
      _timestamp,
      _label,
      _protocol,
      _messagesSent,
      _bytesSent,
      _bufferedAmount);
}

inline SendRequestT *SendRequest::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SendRequestT>(new SendRequestT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SendRequest::UnPackTo(SendRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = ppid(); _o->ppid = _e; }
  { auto _e = data(); if (_e) { _o->data.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->data.begin()); } }
}

inline ::flatbuffers::Offset<SendRequest> SendRequest::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SendRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSendRequest(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SendRequest> CreateSendRequest(::flatbuffers::FlatBufferBuilder &_fbb, const SendRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SendRequestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _ppid = _o->ppid;
  auto _data = _fbb.CreateVector(_o->data);
  return FBS::DataConsumer::CreateSendRequest(
      _fbb,
      _ppid,
      _data);
}

inline SetSubchannelsRequestT *SetSubchannelsRequest::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SetSubchannelsRequestT>(new SetSubchannelsRequestT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SetSubchannelsRequest::UnPackTo(SetSubchannelsRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = subchannels(); if (_e) { _o->subchannels.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->subchannels[_i] = _e->Get(_i); } } else { _o->subchannels.resize(0); } }
}

inline ::flatbuffers::Offset<SetSubchannelsRequest> SetSubchannelsRequest::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SetSubchannelsRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSetSubchannelsRequest(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SetSubchannelsRequest> CreateSetSubchannelsRequest(::flatbuffers::FlatBufferBuilder &_fbb, const SetSubchannelsRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SetSubchannelsRequestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _subchannels = _fbb.CreateVector(_o->subchannels);
  return FBS::DataConsumer::CreateSetSubchannelsRequest(
      _fbb,
      _subchannels);
}

inline SetSubchannelsResponseT *SetSubchannelsResponse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SetSubchannelsResponseT>(new SetSubchannelsResponseT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SetSubchannelsResponse::UnPackTo(SetSubchannelsResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = subchannels(); if (_e) { _o->subchannels.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->subchannels[_i] = _e->Get(_i); } } else { _o->subchannels.resize(0); } }
}

inline ::flatbuffers::Offset<SetSubchannelsResponse> SetSubchannelsResponse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SetSubchannelsResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSetSubchannelsResponse(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SetSubchannelsResponse> CreateSetSubchannelsResponse(::flatbuffers::FlatBufferBuilder &_fbb, const SetSubchannelsResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SetSubchannelsResponseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _subchannels = _fbb.CreateVector(_o->subchannels);
  return FBS::DataConsumer::CreateSetSubchannelsResponse(
      _fbb,
      _subchannels);
}

inline AddSubchannelRequestT *AddSubchannelRequest::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<AddSubchannelRequestT>(new AddSubchannelRequestT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void AddSubchannelRequest::UnPackTo(AddSubchannelRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = subchannel(); _o->subchannel = _e; }
}

inline ::flatbuffers::Offset<AddSubchannelRequest> AddSubchannelRequest::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const AddSubchannelRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateAddSubchannelRequest(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<AddSubchannelRequest> CreateAddSubchannelRequest(::flatbuffers::FlatBufferBuilder &_fbb, const AddSubchannelRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const AddSubchannelRequestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _subchannel = _o->subchannel;
  return FBS::DataConsumer::CreateAddSubchannelRequest(
      _fbb,
      _subchannel);
}

inline AddSubchannelResponseT *AddSubchannelResponse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<AddSubchannelResponseT>(new AddSubchannelResponseT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void AddSubchannelResponse::UnPackTo(AddSubchannelResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = subchannels(); if (_e) { _o->subchannels.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->subchannels[_i] = _e->Get(_i); } } else { _o->subchannels.resize(0); } }
}

inline ::flatbuffers::Offset<AddSubchannelResponse> AddSubchannelResponse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const AddSubchannelResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateAddSubchannelResponse(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<AddSubchannelResponse> CreateAddSubchannelResponse(::flatbuffers::FlatBufferBuilder &_fbb, const AddSubchannelResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const AddSubchannelResponseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _subchannels = _fbb.CreateVector(_o->subchannels);
  return FBS::DataConsumer::CreateAddSubchannelResponse(
      _fbb,
      _subchannels);
}

inline RemoveSubchannelRequestT *RemoveSubchannelRequest::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<RemoveSubchannelRequestT>(new RemoveSubchannelRequestT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void RemoveSubchannelRequest::UnPackTo(RemoveSubchannelRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = subchannel(); _o->subchannel = _e; }
}

inline ::flatbuffers::Offset<RemoveSubchannelRequest> RemoveSubchannelRequest::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RemoveSubchannelRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateRemoveSubchannelRequest(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<RemoveSubchannelRequest> CreateRemoveSubchannelRequest(::flatbuffers::FlatBufferBuilder &_fbb, const RemoveSubchannelRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const RemoveSubchannelRequestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _subchannel = _o->subchannel;
  return FBS::DataConsumer::CreateRemoveSubchannelRequest(
      _fbb,
      _subchannel);
}

inline RemoveSubchannelResponseT *RemoveSubchannelResponse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<RemoveSubchannelResponseT>(new RemoveSubchannelResponseT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void RemoveSubchannelResponse::UnPackTo(RemoveSubchannelResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = subchannels(); if (_e) { _o->subchannels.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->subchannels[_i] = _e->Get(_i); } } else { _o->subchannels.resize(0); } }
}

inline ::flatbuffers::Offset<RemoveSubchannelResponse> RemoveSubchannelResponse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RemoveSubchannelResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateRemoveSubchannelResponse(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<RemoveSubchannelResponse> CreateRemoveSubchannelResponse(::flatbuffers::FlatBufferBuilder &_fbb, const RemoveSubchannelResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const RemoveSubchannelResponseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _subchannels = _fbb.CreateVector(_o->subchannels);
  return FBS::DataConsumer::CreateRemoveSubchannelResponse(
      _fbb,
      _subchannels);
}

inline BufferedAmountLowNotificationT *BufferedAmountLowNotification::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<BufferedAmountLowNotificationT>(new BufferedAmountLowNotificationT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void BufferedAmountLowNotification::UnPackTo(BufferedAmountLowNotificationT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = bufferedAmount(); _o->bufferedAmount = _e; }
}

inline ::flatbuffers::Offset<BufferedAmountLowNotification> BufferedAmountLowNotification::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BufferedAmountLowNotificationT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateBufferedAmountLowNotification(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<BufferedAmountLowNotification> CreateBufferedAmountLowNotification(::flatbuffers::FlatBufferBuilder &_fbb, const BufferedAmountLowNotificationT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const BufferedAmountLowNotificationT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _bufferedAmount = _o->bufferedAmount;
  return FBS::DataConsumer::CreateBufferedAmountLowNotification(
      _fbb,
      _bufferedAmount);
}

inline MessageNotificationT *MessageNotification::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<MessageNotificationT>(new MessageNotificationT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void MessageNotification::UnPackTo(MessageNotificationT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = ppid(); _o->ppid = _e; }
  { auto _e = data(); if (_e) { _o->data.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->data.begin()); } }
}

inline ::flatbuffers::Offset<MessageNotification> MessageNotification::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MessageNotificationT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateMessageNotification(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<MessageNotification> CreateMessageNotification(::flatbuffers::FlatBufferBuilder &_fbb, const MessageNotificationT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const MessageNotificationT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _ppid = _o->ppid;
  auto _data = _fbb.CreateVector(_o->data);
  return FBS::DataConsumer::CreateMessageNotification(
      _fbb,
      _ppid,
      _data);
}

inline const ::flatbuffers::TypeTable *GetBufferedAmountResponseTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_UINT, 0, -1 }
  };
  static const char * const names[] = {
    "bufferedAmount"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 1, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *SetBufferedAmountLowThresholdRequestTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_UINT, 0, -1 }
  };
  static const char * const names[] = {
    "threshold"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 1, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *DumpResponseTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_UCHAR, 0, 0 },
    { ::flatbuffers::ET_SEQUENCE, 0, 1 },
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_UINT, 0, -1 },
    { ::flatbuffers::ET_BOOL, 0, -1 },
    { ::flatbuffers::ET_BOOL, 0, -1 },
    { ::flatbuffers::ET_USHORT, 1, -1 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    FBS::DataProducer::TypeTypeTable,
    FBS::SctpParameters::SctpStreamParametersTypeTable
  };
  static const char * const names[] = {
    "id",
    "dataProducerId",
    "type",
    "sctpStreamParameters",
    "label",
    "protocol",
    "bufferedAmountLowThreshold",
    "paused",
    "dataProducerPaused",
    "subchannels"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 10, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *GetStatsResponseTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_ULONG, 0, -1 },
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_ULONG, 0, -1 },
    { ::flatbuffers::ET_ULONG, 0, -1 },
    { ::flatbuffers::ET_UINT, 0, -1 }
  };
  static const char * const names[] = {
    "timestamp",
    "label",
    "protocol",
    "messagesSent",
    "bytesSent",
    "bufferedAmount"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 6, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *SendRequestTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_UINT, 0, -1 },
    { ::flatbuffers::ET_UCHAR, 1, -1 }
  };
  static const char * const names[] = {
    "ppid",
    "data"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *SetSubchannelsRequestTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_USHORT, 1, -1 }
  };
  static const char * const names[] = {
    "subchannels"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 1, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *SetSubchannelsResponseTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_USHORT, 1, -1 }
  };
  static const char * const names[] = {
    "subchannels"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 1, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *AddSubchannelRequestTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_USHORT, 0, -1 }
  };
  static const char * const names[] = {
    "subchannel"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 1, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *AddSubchannelResponseTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_USHORT, 1, -1 }
  };
  static const char * const names[] = {
    "subchannels"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 1, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *RemoveSubchannelRequestTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_USHORT, 0, -1 }
  };
  static const char * const names[] = {
    "subchannel"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 1, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *RemoveSubchannelResponseTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_USHORT, 1, -1 }
  };
  static const char * const names[] = {
    "subchannels"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 1, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *BufferedAmountLowNotificationTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_UINT, 0, -1 }
  };
  static const char * const names[] = {
    "bufferedAmount"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 1, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *MessageNotificationTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_UINT, 0, -1 },
    { ::flatbuffers::ET_UCHAR, 1, -1 }
  };
  static const char * const names[] = {
    "ppid",
    "data"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

}  // namespace DataConsumer
}  // namespace FBS

#endif  // FLATBUFFERS_GENERATED_DATACONSUMER_FBS_DATACONSUMER_H_
