// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DIRECTTRANSPORT_FBS_DIRECTTRANSPORT_H_
#define FLATBUFFERS_GENERATED_DIRECTTRANSPORT_FBS_DIRECTTRANSPORT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "transport_generated.h"

namespace FBS {
namespace DirectTransport {

struct DirectTransportOptions;
struct DirectTransportOptionsBuilder;
struct DirectTransportOptionsT;

struct DumpResponse;
struct DumpResponseBuilder;
struct DumpResponseT;

struct GetStatsResponse;
struct GetStatsResponseBuilder;
struct GetStatsResponseT;

struct RtcpNotification;
struct RtcpNotificationBuilder;
struct RtcpNotificationT;

inline const ::flatbuffers::TypeTable *DirectTransportOptionsTypeTable();

inline const ::flatbuffers::TypeTable *DumpResponseTypeTable();

inline const ::flatbuffers::TypeTable *GetStatsResponseTypeTable();

inline const ::flatbuffers::TypeTable *RtcpNotificationTypeTable();

struct DirectTransportOptionsT : public ::flatbuffers::NativeTable {
  typedef DirectTransportOptions TableType;
  std::unique_ptr<FBS::Transport::OptionsT> base{};
  DirectTransportOptionsT() = default;
  DirectTransportOptionsT(const DirectTransportOptionsT &o);
  DirectTransportOptionsT(DirectTransportOptionsT&&) FLATBUFFERS_NOEXCEPT = default;
  DirectTransportOptionsT &operator=(DirectTransportOptionsT o) FLATBUFFERS_NOEXCEPT;
};

struct DirectTransportOptions FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DirectTransportOptionsT NativeTableType;
  typedef DirectTransportOptionsBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return DirectTransportOptionsTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BASE = 4
  };
  const FBS::Transport::Options *base() const {
    return GetPointer<const FBS::Transport::Options *>(VT_BASE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_BASE) &&
           verifier.VerifyTable(base()) &&
           verifier.EndTable();
  }
  DirectTransportOptionsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(DirectTransportOptionsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<DirectTransportOptions> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DirectTransportOptionsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct DirectTransportOptionsBuilder {
  typedef DirectTransportOptions Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_base(::flatbuffers::Offset<FBS::Transport::Options> base) {
    fbb_.AddOffset(DirectTransportOptions::VT_BASE, base);
  }
  explicit DirectTransportOptionsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DirectTransportOptions> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DirectTransportOptions>(end);
    fbb_.Required(o, DirectTransportOptions::VT_BASE);
    return o;
  }
};

inline ::flatbuffers::Offset<DirectTransportOptions> CreateDirectTransportOptions(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<FBS::Transport::Options> base = 0) {
  DirectTransportOptionsBuilder builder_(_fbb);
  builder_.add_base(base);
  return builder_.Finish();
}

::flatbuffers::Offset<DirectTransportOptions> CreateDirectTransportOptions(::flatbuffers::FlatBufferBuilder &_fbb, const DirectTransportOptionsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct DumpResponseT : public ::flatbuffers::NativeTable {
  typedef DumpResponse TableType;
  std::unique_ptr<FBS::Transport::DumpT> base{};
  DumpResponseT() = default;
  DumpResponseT(const DumpResponseT &o);
  DumpResponseT(DumpResponseT&&) FLATBUFFERS_NOEXCEPT = default;
  DumpResponseT &operator=(DumpResponseT o) FLATBUFFERS_NOEXCEPT;
};

struct DumpResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DumpResponseT NativeTableType;
  typedef DumpResponseBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return DumpResponseTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BASE = 4
  };
  const FBS::Transport::Dump *base() const {
    return GetPointer<const FBS::Transport::Dump *>(VT_BASE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_BASE) &&
           verifier.VerifyTable(base()) &&
           verifier.EndTable();
  }
  DumpResponseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(DumpResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<DumpResponse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DumpResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct DumpResponseBuilder {
  typedef DumpResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_base(::flatbuffers::Offset<FBS::Transport::Dump> base) {
    fbb_.AddOffset(DumpResponse::VT_BASE, base);
  }
  explicit DumpResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DumpResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DumpResponse>(end);
    fbb_.Required(o, DumpResponse::VT_BASE);
    return o;
  }
};

inline ::flatbuffers::Offset<DumpResponse> CreateDumpResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<FBS::Transport::Dump> base = 0) {
  DumpResponseBuilder builder_(_fbb);
  builder_.add_base(base);
  return builder_.Finish();
}

::flatbuffers::Offset<DumpResponse> CreateDumpResponse(::flatbuffers::FlatBufferBuilder &_fbb, const DumpResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct GetStatsResponseT : public ::flatbuffers::NativeTable {
  typedef GetStatsResponse TableType;
  std::unique_ptr<FBS::Transport::StatsT> base{};
  GetStatsResponseT() = default;
  GetStatsResponseT(const GetStatsResponseT &o);
  GetStatsResponseT(GetStatsResponseT&&) FLATBUFFERS_NOEXCEPT = default;
  GetStatsResponseT &operator=(GetStatsResponseT o) FLATBUFFERS_NOEXCEPT;
};

struct GetStatsResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GetStatsResponseT NativeTableType;
  typedef GetStatsResponseBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return GetStatsResponseTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BASE = 4
  };
  const FBS::Transport::Stats *base() const {
    return GetPointer<const FBS::Transport::Stats *>(VT_BASE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_BASE) &&
           verifier.VerifyTable(base()) &&
           verifier.EndTable();
  }
  GetStatsResponseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(GetStatsResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<GetStatsResponse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const GetStatsResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct GetStatsResponseBuilder {
  typedef GetStatsResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_base(::flatbuffers::Offset<FBS::Transport::Stats> base) {
    fbb_.AddOffset(GetStatsResponse::VT_BASE, base);
  }
  explicit GetStatsResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GetStatsResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GetStatsResponse>(end);
    fbb_.Required(o, GetStatsResponse::VT_BASE);
    return o;
  }
};

inline ::flatbuffers::Offset<GetStatsResponse> CreateGetStatsResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<FBS::Transport::Stats> base = 0) {
  GetStatsResponseBuilder builder_(_fbb);
  builder_.add_base(base);
  return builder_.Finish();
}

::flatbuffers::Offset<GetStatsResponse> CreateGetStatsResponse(::flatbuffers::FlatBufferBuilder &_fbb, const GetStatsResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct RtcpNotificationT : public ::flatbuffers::NativeTable {
  typedef RtcpNotification TableType;
  std::vector<uint8_t> data{};
};

struct RtcpNotification FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RtcpNotificationT NativeTableType;
  typedef RtcpNotificationBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return RtcpNotificationTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATA = 4
  };
  const ::flatbuffers::Vector<uint8_t> *data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           verifier.EndTable();
  }
  RtcpNotificationT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(RtcpNotificationT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<RtcpNotification> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RtcpNotificationT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct RtcpNotificationBuilder {
  typedef RtcpNotification Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data) {
    fbb_.AddOffset(RtcpNotification::VT_DATA, data);
  }
  explicit RtcpNotificationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RtcpNotification> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RtcpNotification>(end);
    fbb_.Required(o, RtcpNotification::VT_DATA);
    return o;
  }
};

inline ::flatbuffers::Offset<RtcpNotification> CreateRtcpNotification(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data = 0) {
  RtcpNotificationBuilder builder_(_fbb);
  builder_.add_data(data);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<RtcpNotification> CreateRtcpNotificationDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *data = nullptr) {
  auto data__ = data ? _fbb.CreateVector<uint8_t>(*data) : 0;
  return FBS::DirectTransport::CreateRtcpNotification(
      _fbb,
      data__);
}

::flatbuffers::Offset<RtcpNotification> CreateRtcpNotification(::flatbuffers::FlatBufferBuilder &_fbb, const RtcpNotificationT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline DirectTransportOptionsT::DirectTransportOptionsT(const DirectTransportOptionsT &o)
      : base((o.base) ? new FBS::Transport::OptionsT(*o.base) : nullptr) {
}

inline DirectTransportOptionsT &DirectTransportOptionsT::operator=(DirectTransportOptionsT o) FLATBUFFERS_NOEXCEPT {
  std::swap(base, o.base);
  return *this;
}

inline DirectTransportOptionsT *DirectTransportOptions::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<DirectTransportOptionsT>(new DirectTransportOptionsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void DirectTransportOptions::UnPackTo(DirectTransportOptionsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = base(); if (_e) { if(_o->base) { _e->UnPackTo(_o->base.get(), _resolver); } else { _o->base = std::unique_ptr<FBS::Transport::OptionsT>(_e->UnPack(_resolver)); } } else if (_o->base) { _o->base.reset(); } }
}

inline ::flatbuffers::Offset<DirectTransportOptions> DirectTransportOptions::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DirectTransportOptionsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateDirectTransportOptions(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<DirectTransportOptions> CreateDirectTransportOptions(::flatbuffers::FlatBufferBuilder &_fbb, const DirectTransportOptionsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const DirectTransportOptionsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _base = _o->base ? CreateOptions(_fbb, _o->base.get(), _rehasher) : 0;
  return FBS::DirectTransport::CreateDirectTransportOptions(
      _fbb,
      _base);
}

inline DumpResponseT::DumpResponseT(const DumpResponseT &o)
      : base((o.base) ? new FBS::Transport::DumpT(*o.base) : nullptr) {
}

inline DumpResponseT &DumpResponseT::operator=(DumpResponseT o) FLATBUFFERS_NOEXCEPT {
  std::swap(base, o.base);
  return *this;
}

inline DumpResponseT *DumpResponse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<DumpResponseT>(new DumpResponseT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void DumpResponse::UnPackTo(DumpResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = base(); if (_e) { if(_o->base) { _e->UnPackTo(_o->base.get(), _resolver); } else { _o->base = std::unique_ptr<FBS::Transport::DumpT>(_e->UnPack(_resolver)); } } else if (_o->base) { _o->base.reset(); } }
}

inline ::flatbuffers::Offset<DumpResponse> DumpResponse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DumpResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateDumpResponse(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<DumpResponse> CreateDumpResponse(::flatbuffers::FlatBufferBuilder &_fbb, const DumpResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const DumpResponseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _base = _o->base ? CreateDump(_fbb, _o->base.get(), _rehasher) : 0;
  return FBS::DirectTransport::CreateDumpResponse(
      _fbb,
      _base);
}

inline GetStatsResponseT::GetStatsResponseT(const GetStatsResponseT &o)
      : base((o.base) ? new FBS::Transport::StatsT(*o.base) : nullptr) {
}

inline GetStatsResponseT &GetStatsResponseT::operator=(GetStatsResponseT o) FLATBUFFERS_NOEXCEPT {
  std::swap(base, o.base);
  return *this;
}

inline GetStatsResponseT *GetStatsResponse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<GetStatsResponseT>(new GetStatsResponseT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void GetStatsResponse::UnPackTo(GetStatsResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = base(); if (_e) { if(_o->base) { _e->UnPackTo(_o->base.get(), _resolver); } else { _o->base = std::unique_ptr<FBS::Transport::StatsT>(_e->UnPack(_resolver)); } } else if (_o->base) { _o->base.reset(); } }
}

inline ::flatbuffers::Offset<GetStatsResponse> GetStatsResponse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const GetStatsResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateGetStatsResponse(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<GetStatsResponse> CreateGetStatsResponse(::flatbuffers::FlatBufferBuilder &_fbb, const GetStatsResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const GetStatsResponseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _base = _o->base ? CreateStats(_fbb, _o->base.get(), _rehasher) : 0;
  return FBS::DirectTransport::CreateGetStatsResponse(
      _fbb,
      _base);
}

inline RtcpNotificationT *RtcpNotification::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<RtcpNotificationT>(new RtcpNotificationT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void RtcpNotification::UnPackTo(RtcpNotificationT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = data(); if (_e) { _o->data.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->data.begin()); } }
}

inline ::flatbuffers::Offset<RtcpNotification> RtcpNotification::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RtcpNotificationT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateRtcpNotification(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<RtcpNotification> CreateRtcpNotification(::flatbuffers::FlatBufferBuilder &_fbb, const RtcpNotificationT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const RtcpNotificationT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _data = _fbb.CreateVector(_o->data);
  return FBS::DirectTransport::CreateRtcpNotification(
      _fbb,
      _data);
}

inline const ::flatbuffers::TypeTable *DirectTransportOptionsTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SEQUENCE, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    FBS::Transport::OptionsTypeTable
  };
  static const char * const names[] = {
    "base"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 1, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *DumpResponseTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SEQUENCE, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    FBS::Transport::DumpTypeTable
  };
  static const char * const names[] = {
    "base"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 1, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *GetStatsResponseTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SEQUENCE, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    FBS::Transport::StatsTypeTable
  };
  static const char * const names[] = {
    "base"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 1, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *RtcpNotificationTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_UCHAR, 1, -1 }
  };
  static const char * const names[] = {
    "data"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 1, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

}  // namespace DirectTransport
}  // namespace FBS

#endif  // FLATBUFFERS_GENERATED_DIRECTTRANSPORT_FBS_DIRECTTRANSPORT_H_
