// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PLAINTRANSPORT_FBS_PLAINTRANSPORT_H_
#define FLATBUFFERS_GENERATED_PLAINTRANSPORT_FBS_PLAINTRANSPORT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "sctpParameters_generated.h"
#include "srtpParameters_generated.h"
#include "transport_generated.h"

namespace FBS {
namespace PlainTransport {

struct PlainTransportOptions;
struct PlainTransportOptionsBuilder;
struct PlainTransportOptionsT;

struct ConnectRequest;
struct ConnectRequestBuilder;
struct ConnectRequestT;

struct ConnectResponse;
struct ConnectResponseBuilder;
struct ConnectResponseT;

struct DumpResponse;
struct DumpResponseBuilder;
struct DumpResponseT;

struct GetStatsResponse;
struct GetStatsResponseBuilder;
struct GetStatsResponseT;

struct TupleNotification;
struct TupleNotificationBuilder;
struct TupleNotificationT;

struct RtcpTupleNotification;
struct RtcpTupleNotificationBuilder;
struct RtcpTupleNotificationT;

inline const ::flatbuffers::TypeTable *PlainTransportOptionsTypeTable();

inline const ::flatbuffers::TypeTable *ConnectRequestTypeTable();

inline const ::flatbuffers::TypeTable *ConnectResponseTypeTable();

inline const ::flatbuffers::TypeTable *DumpResponseTypeTable();

inline const ::flatbuffers::TypeTable *GetStatsResponseTypeTable();

inline const ::flatbuffers::TypeTable *TupleNotificationTypeTable();

inline const ::flatbuffers::TypeTable *RtcpTupleNotificationTypeTable();

struct PlainTransportOptionsT : public ::flatbuffers::NativeTable {
  typedef PlainTransportOptions TableType;
  std::unique_ptr<FBS::Transport::OptionsT> base{};
  std::unique_ptr<FBS::Transport::ListenInfoT> listenInfo{};
  std::unique_ptr<FBS::Transport::ListenInfoT> rtcpListenInfo{};
  bool rtcpMux = false;
  bool comedia = false;
  bool enableSrtp = false;
  ::flatbuffers::Optional<FBS::SrtpParameters::SrtpCryptoSuite> srtpCryptoSuite = ::flatbuffers::nullopt;
  PlainTransportOptionsT() = default;
  PlainTransportOptionsT(const PlainTransportOptionsT &o);
  PlainTransportOptionsT(PlainTransportOptionsT&&) FLATBUFFERS_NOEXCEPT = default;
  PlainTransportOptionsT &operator=(PlainTransportOptionsT o) FLATBUFFERS_NOEXCEPT;
};

struct PlainTransportOptions FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PlainTransportOptionsT NativeTableType;
  typedef PlainTransportOptionsBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return PlainTransportOptionsTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BASE = 4,
    VT_LISTENINFO = 6,
    VT_RTCPLISTENINFO = 8,
    VT_RTCPMUX = 10,
    VT_COMEDIA = 12,
    VT_ENABLESRTP = 14,
    VT_SRTPCRYPTOSUITE = 16
  };
  const FBS::Transport::Options *base() const {
    return GetPointer<const FBS::Transport::Options *>(VT_BASE);
  }
  const FBS::Transport::ListenInfo *listenInfo() const {
    return GetPointer<const FBS::Transport::ListenInfo *>(VT_LISTENINFO);
  }
  const FBS::Transport::ListenInfo *rtcpListenInfo() const {
    return GetPointer<const FBS::Transport::ListenInfo *>(VT_RTCPLISTENINFO);
  }
  bool rtcpMux() const {
    return GetField<uint8_t>(VT_RTCPMUX, 0) != 0;
  }
  bool comedia() const {
    return GetField<uint8_t>(VT_COMEDIA, 0) != 0;
  }
  bool enableSrtp() const {
    return GetField<uint8_t>(VT_ENABLESRTP, 0) != 0;
  }
  ::flatbuffers::Optional<FBS::SrtpParameters::SrtpCryptoSuite> srtpCryptoSuite() const {
    return GetOptional<uint8_t, FBS::SrtpParameters::SrtpCryptoSuite>(VT_SRTPCRYPTOSUITE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_BASE) &&
           verifier.VerifyTable(base()) &&
           VerifyOffsetRequired(verifier, VT_LISTENINFO) &&
           verifier.VerifyTable(listenInfo()) &&
           VerifyOffset(verifier, VT_RTCPLISTENINFO) &&
           verifier.VerifyTable(rtcpListenInfo()) &&
           VerifyField<uint8_t>(verifier, VT_RTCPMUX, 1) &&
           VerifyField<uint8_t>(verifier, VT_COMEDIA, 1) &&
           VerifyField<uint8_t>(verifier, VT_ENABLESRTP, 1) &&
           VerifyField<uint8_t>(verifier, VT_SRTPCRYPTOSUITE, 1) &&
           verifier.EndTable();
  }
  PlainTransportOptionsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(PlainTransportOptionsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<PlainTransportOptions> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PlainTransportOptionsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct PlainTransportOptionsBuilder {
  typedef PlainTransportOptions Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_base(::flatbuffers::Offset<FBS::Transport::Options> base) {
    fbb_.AddOffset(PlainTransportOptions::VT_BASE, base);
  }
  void add_listenInfo(::flatbuffers::Offset<FBS::Transport::ListenInfo> listenInfo) {
    fbb_.AddOffset(PlainTransportOptions::VT_LISTENINFO, listenInfo);
  }
  void add_rtcpListenInfo(::flatbuffers::Offset<FBS::Transport::ListenInfo> rtcpListenInfo) {
    fbb_.AddOffset(PlainTransportOptions::VT_RTCPLISTENINFO, rtcpListenInfo);
  }
  void add_rtcpMux(bool rtcpMux) {
    fbb_.AddElement<uint8_t>(PlainTransportOptions::VT_RTCPMUX, static_cast<uint8_t>(rtcpMux), 0);
  }
  void add_comedia(bool comedia) {
    fbb_.AddElement<uint8_t>(PlainTransportOptions::VT_COMEDIA, static_cast<uint8_t>(comedia), 0);
  }
  void add_enableSrtp(bool enableSrtp) {
    fbb_.AddElement<uint8_t>(PlainTransportOptions::VT_ENABLESRTP, static_cast<uint8_t>(enableSrtp), 0);
  }
  void add_srtpCryptoSuite(FBS::SrtpParameters::SrtpCryptoSuite srtpCryptoSuite) {
    fbb_.AddElement<uint8_t>(PlainTransportOptions::VT_SRTPCRYPTOSUITE, static_cast<uint8_t>(srtpCryptoSuite));
  }
  explicit PlainTransportOptionsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PlainTransportOptions> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PlainTransportOptions>(end);
    fbb_.Required(o, PlainTransportOptions::VT_BASE);
    fbb_.Required(o, PlainTransportOptions::VT_LISTENINFO);
    return o;
  }
};

inline ::flatbuffers::Offset<PlainTransportOptions> CreatePlainTransportOptions(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<FBS::Transport::Options> base = 0,
    ::flatbuffers::Offset<FBS::Transport::ListenInfo> listenInfo = 0,
    ::flatbuffers::Offset<FBS::Transport::ListenInfo> rtcpListenInfo = 0,
    bool rtcpMux = false,
    bool comedia = false,
    bool enableSrtp = false,
    ::flatbuffers::Optional<FBS::SrtpParameters::SrtpCryptoSuite> srtpCryptoSuite = ::flatbuffers::nullopt) {
  PlainTransportOptionsBuilder builder_(_fbb);
  builder_.add_rtcpListenInfo(rtcpListenInfo);
  builder_.add_listenInfo(listenInfo);
  builder_.add_base(base);
  if(srtpCryptoSuite) { builder_.add_srtpCryptoSuite(*srtpCryptoSuite); }
  builder_.add_enableSrtp(enableSrtp);
  builder_.add_comedia(comedia);
  builder_.add_rtcpMux(rtcpMux);
  return builder_.Finish();
}

::flatbuffers::Offset<PlainTransportOptions> CreatePlainTransportOptions(::flatbuffers::FlatBufferBuilder &_fbb, const PlainTransportOptionsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ConnectRequestT : public ::flatbuffers::NativeTable {
  typedef ConnectRequest TableType;
  std::string ip{};
  ::flatbuffers::Optional<uint16_t> port = ::flatbuffers::nullopt;
  ::flatbuffers::Optional<uint16_t> rtcpPort = ::flatbuffers::nullopt;
  std::unique_ptr<FBS::SrtpParameters::SrtpParametersT> srtpParameters{};
  ConnectRequestT() = default;
  ConnectRequestT(const ConnectRequestT &o);
  ConnectRequestT(ConnectRequestT&&) FLATBUFFERS_NOEXCEPT = default;
  ConnectRequestT &operator=(ConnectRequestT o) FLATBUFFERS_NOEXCEPT;
};

struct ConnectRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ConnectRequestT NativeTableType;
  typedef ConnectRequestBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return ConnectRequestTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_IP = 4,
    VT_PORT = 6,
    VT_RTCPPORT = 8,
    VT_SRTPPARAMETERS = 10
  };
  const ::flatbuffers::String *ip() const {
    return GetPointer<const ::flatbuffers::String *>(VT_IP);
  }
  ::flatbuffers::Optional<uint16_t> port() const {
    return GetOptional<uint16_t, uint16_t>(VT_PORT);
  }
  ::flatbuffers::Optional<uint16_t> rtcpPort() const {
    return GetOptional<uint16_t, uint16_t>(VT_RTCPPORT);
  }
  const FBS::SrtpParameters::SrtpParameters *srtpParameters() const {
    return GetPointer<const FBS::SrtpParameters::SrtpParameters *>(VT_SRTPPARAMETERS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_IP) &&
           verifier.VerifyString(ip()) &&
           VerifyField<uint16_t>(verifier, VT_PORT, 2) &&
           VerifyField<uint16_t>(verifier, VT_RTCPPORT, 2) &&
           VerifyOffset(verifier, VT_SRTPPARAMETERS) &&
           verifier.VerifyTable(srtpParameters()) &&
           verifier.EndTable();
  }
  ConnectRequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ConnectRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ConnectRequest> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ConnectRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ConnectRequestBuilder {
  typedef ConnectRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_ip(::flatbuffers::Offset<::flatbuffers::String> ip) {
    fbb_.AddOffset(ConnectRequest::VT_IP, ip);
  }
  void add_port(uint16_t port) {
    fbb_.AddElement<uint16_t>(ConnectRequest::VT_PORT, port);
  }
  void add_rtcpPort(uint16_t rtcpPort) {
    fbb_.AddElement<uint16_t>(ConnectRequest::VT_RTCPPORT, rtcpPort);
  }
  void add_srtpParameters(::flatbuffers::Offset<FBS::SrtpParameters::SrtpParameters> srtpParameters) {
    fbb_.AddOffset(ConnectRequest::VT_SRTPPARAMETERS, srtpParameters);
  }
  explicit ConnectRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ConnectRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ConnectRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ConnectRequest> CreateConnectRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> ip = 0,
    ::flatbuffers::Optional<uint16_t> port = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<uint16_t> rtcpPort = ::flatbuffers::nullopt,
    ::flatbuffers::Offset<FBS::SrtpParameters::SrtpParameters> srtpParameters = 0) {
  ConnectRequestBuilder builder_(_fbb);
  builder_.add_srtpParameters(srtpParameters);
  builder_.add_ip(ip);
  if(rtcpPort) { builder_.add_rtcpPort(*rtcpPort); }
  if(port) { builder_.add_port(*port); }
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ConnectRequest> CreateConnectRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *ip = nullptr,
    ::flatbuffers::Optional<uint16_t> port = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<uint16_t> rtcpPort = ::flatbuffers::nullopt,
    ::flatbuffers::Offset<FBS::SrtpParameters::SrtpParameters> srtpParameters = 0) {
  auto ip__ = ip ? _fbb.CreateString(ip) : 0;
  return FBS::PlainTransport::CreateConnectRequest(
      _fbb,
      ip__,
      port,
      rtcpPort,
      srtpParameters);
}

::flatbuffers::Offset<ConnectRequest> CreateConnectRequest(::flatbuffers::FlatBufferBuilder &_fbb, const ConnectRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ConnectResponseT : public ::flatbuffers::NativeTable {
  typedef ConnectResponse TableType;
  std::unique_ptr<FBS::Transport::TupleT> tuple{};
  std::unique_ptr<FBS::Transport::TupleT> rtcpTuple{};
  std::unique_ptr<FBS::SrtpParameters::SrtpParametersT> srtpParameters{};
  ConnectResponseT() = default;
  ConnectResponseT(const ConnectResponseT &o);
  ConnectResponseT(ConnectResponseT&&) FLATBUFFERS_NOEXCEPT = default;
  ConnectResponseT &operator=(ConnectResponseT o) FLATBUFFERS_NOEXCEPT;
};

struct ConnectResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ConnectResponseT NativeTableType;
  typedef ConnectResponseBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return ConnectResponseTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TUPLE = 4,
    VT_RTCPTUPLE = 6,
    VT_SRTPPARAMETERS = 8
  };
  const FBS::Transport::Tuple *tuple() const {
    return GetPointer<const FBS::Transport::Tuple *>(VT_TUPLE);
  }
  const FBS::Transport::Tuple *rtcpTuple() const {
    return GetPointer<const FBS::Transport::Tuple *>(VT_RTCPTUPLE);
  }
  const FBS::SrtpParameters::SrtpParameters *srtpParameters() const {
    return GetPointer<const FBS::SrtpParameters::SrtpParameters *>(VT_SRTPPARAMETERS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_TUPLE) &&
           verifier.VerifyTable(tuple()) &&
           VerifyOffset(verifier, VT_RTCPTUPLE) &&
           verifier.VerifyTable(rtcpTuple()) &&
           VerifyOffset(verifier, VT_SRTPPARAMETERS) &&
           verifier.VerifyTable(srtpParameters()) &&
           verifier.EndTable();
  }
  ConnectResponseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ConnectResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ConnectResponse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ConnectResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ConnectResponseBuilder {
  typedef ConnectResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_tuple(::flatbuffers::Offset<FBS::Transport::Tuple> tuple) {
    fbb_.AddOffset(ConnectResponse::VT_TUPLE, tuple);
  }
  void add_rtcpTuple(::flatbuffers::Offset<FBS::Transport::Tuple> rtcpTuple) {
    fbb_.AddOffset(ConnectResponse::VT_RTCPTUPLE, rtcpTuple);
  }
  void add_srtpParameters(::flatbuffers::Offset<FBS::SrtpParameters::SrtpParameters> srtpParameters) {
    fbb_.AddOffset(ConnectResponse::VT_SRTPPARAMETERS, srtpParameters);
  }
  explicit ConnectResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ConnectResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ConnectResponse>(end);
    fbb_.Required(o, ConnectResponse::VT_TUPLE);
    return o;
  }
};

inline ::flatbuffers::Offset<ConnectResponse> CreateConnectResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<FBS::Transport::Tuple> tuple = 0,
    ::flatbuffers::Offset<FBS::Transport::Tuple> rtcpTuple = 0,
    ::flatbuffers::Offset<FBS::SrtpParameters::SrtpParameters> srtpParameters = 0) {
  ConnectResponseBuilder builder_(_fbb);
  builder_.add_srtpParameters(srtpParameters);
  builder_.add_rtcpTuple(rtcpTuple);
  builder_.add_tuple(tuple);
  return builder_.Finish();
}

::flatbuffers::Offset<ConnectResponse> CreateConnectResponse(::flatbuffers::FlatBufferBuilder &_fbb, const ConnectResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct DumpResponseT : public ::flatbuffers::NativeTable {
  typedef DumpResponse TableType;
  std::unique_ptr<FBS::Transport::DumpT> base{};
  bool rtcpMux = false;
  bool comedia = false;
  std::unique_ptr<FBS::Transport::TupleT> tuple{};
  std::unique_ptr<FBS::Transport::TupleT> rtcpTuple{};
  std::unique_ptr<FBS::SrtpParameters::SrtpParametersT> srtpParameters{};
  DumpResponseT() = default;
  DumpResponseT(const DumpResponseT &o);
  DumpResponseT(DumpResponseT&&) FLATBUFFERS_NOEXCEPT = default;
  DumpResponseT &operator=(DumpResponseT o) FLATBUFFERS_NOEXCEPT;
};

struct DumpResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DumpResponseT NativeTableType;
  typedef DumpResponseBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return DumpResponseTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BASE = 4,
    VT_RTCPMUX = 6,
    VT_COMEDIA = 8,
    VT_TUPLE = 10,
    VT_RTCPTUPLE = 12,
    VT_SRTPPARAMETERS = 14
  };
  const FBS::Transport::Dump *base() const {
    return GetPointer<const FBS::Transport::Dump *>(VT_BASE);
  }
  bool rtcpMux() const {
    return GetField<uint8_t>(VT_RTCPMUX, 0) != 0;
  }
  bool comedia() const {
    return GetField<uint8_t>(VT_COMEDIA, 0) != 0;
  }
  const FBS::Transport::Tuple *tuple() const {
    return GetPointer<const FBS::Transport::Tuple *>(VT_TUPLE);
  }
  const FBS::Transport::Tuple *rtcpTuple() const {
    return GetPointer<const FBS::Transport::Tuple *>(VT_RTCPTUPLE);
  }
  const FBS::SrtpParameters::SrtpParameters *srtpParameters() const {
    return GetPointer<const FBS::SrtpParameters::SrtpParameters *>(VT_SRTPPARAMETERS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_BASE) &&
           verifier.VerifyTable(base()) &&
           VerifyField<uint8_t>(verifier, VT_RTCPMUX, 1) &&
           VerifyField<uint8_t>(verifier, VT_COMEDIA, 1) &&
           VerifyOffsetRequired(verifier, VT_TUPLE) &&
           verifier.VerifyTable(tuple()) &&
           VerifyOffset(verifier, VT_RTCPTUPLE) &&
           verifier.VerifyTable(rtcpTuple()) &&
           VerifyOffset(verifier, VT_SRTPPARAMETERS) &&
           verifier.VerifyTable(srtpParameters()) &&
           verifier.EndTable();
  }
  DumpResponseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(DumpResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<DumpResponse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DumpResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct DumpResponseBuilder {
  typedef DumpResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_base(::flatbuffers::Offset<FBS::Transport::Dump> base) {
    fbb_.AddOffset(DumpResponse::VT_BASE, base);
  }
  void add_rtcpMux(bool rtcpMux) {
    fbb_.AddElement<uint8_t>(DumpResponse::VT_RTCPMUX, static_cast<uint8_t>(rtcpMux), 0);
  }
  void add_comedia(bool comedia) {
    fbb_.AddElement<uint8_t>(DumpResponse::VT_COMEDIA, static_cast<uint8_t>(comedia), 0);
  }
  void add_tuple(::flatbuffers::Offset<FBS::Transport::Tuple> tuple) {
    fbb_.AddOffset(DumpResponse::VT_TUPLE, tuple);
  }
  void add_rtcpTuple(::flatbuffers::Offset<FBS::Transport::Tuple> rtcpTuple) {
    fbb_.AddOffset(DumpResponse::VT_RTCPTUPLE, rtcpTuple);
  }
  void add_srtpParameters(::flatbuffers::Offset<FBS::SrtpParameters::SrtpParameters> srtpParameters) {
    fbb_.AddOffset(DumpResponse::VT_SRTPPARAMETERS, srtpParameters);
  }
  explicit DumpResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DumpResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DumpResponse>(end);
    fbb_.Required(o, DumpResponse::VT_BASE);
    fbb_.Required(o, DumpResponse::VT_TUPLE);
    return o;
  }
};

inline ::flatbuffers::Offset<DumpResponse> CreateDumpResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<FBS::Transport::Dump> base = 0,
    bool rtcpMux = false,
    bool comedia = false,
    ::flatbuffers::Offset<FBS::Transport::Tuple> tuple = 0,
    ::flatbuffers::Offset<FBS::Transport::Tuple> rtcpTuple = 0,
    ::flatbuffers::Offset<FBS::SrtpParameters::SrtpParameters> srtpParameters = 0) {
  DumpResponseBuilder builder_(_fbb);
  builder_.add_srtpParameters(srtpParameters);
  builder_.add_rtcpTuple(rtcpTuple);
  builder_.add_tuple(tuple);
  builder_.add_base(base);
  builder_.add_comedia(comedia);
  builder_.add_rtcpMux(rtcpMux);
  return builder_.Finish();
}

::flatbuffers::Offset<DumpResponse> CreateDumpResponse(::flatbuffers::FlatBufferBuilder &_fbb, const DumpResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct GetStatsResponseT : public ::flatbuffers::NativeTable {
  typedef GetStatsResponse TableType;
  std::unique_ptr<FBS::Transport::StatsT> base{};
  bool rtcpMux = false;
  bool comedia = false;
  std::unique_ptr<FBS::Transport::TupleT> tuple{};
  std::unique_ptr<FBS::Transport::TupleT> rtcpTuple{};
  GetStatsResponseT() = default;
  GetStatsResponseT(const GetStatsResponseT &o);
  GetStatsResponseT(GetStatsResponseT&&) FLATBUFFERS_NOEXCEPT = default;
  GetStatsResponseT &operator=(GetStatsResponseT o) FLATBUFFERS_NOEXCEPT;
};

struct GetStatsResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GetStatsResponseT NativeTableType;
  typedef GetStatsResponseBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return GetStatsResponseTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BASE = 4,
    VT_RTCPMUX = 6,
    VT_COMEDIA = 8,
    VT_TUPLE = 10,
    VT_RTCPTUPLE = 12
  };
  const FBS::Transport::Stats *base() const {
    return GetPointer<const FBS::Transport::Stats *>(VT_BASE);
  }
  bool rtcpMux() const {
    return GetField<uint8_t>(VT_RTCPMUX, 0) != 0;
  }
  bool comedia() const {
    return GetField<uint8_t>(VT_COMEDIA, 0) != 0;
  }
  const FBS::Transport::Tuple *tuple() const {
    return GetPointer<const FBS::Transport::Tuple *>(VT_TUPLE);
  }
  const FBS::Transport::Tuple *rtcpTuple() const {
    return GetPointer<const FBS::Transport::Tuple *>(VT_RTCPTUPLE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_BASE) &&
           verifier.VerifyTable(base()) &&
           VerifyField<uint8_t>(verifier, VT_RTCPMUX, 1) &&
           VerifyField<uint8_t>(verifier, VT_COMEDIA, 1) &&
           VerifyOffsetRequired(verifier, VT_TUPLE) &&
           verifier.VerifyTable(tuple()) &&
           VerifyOffset(verifier, VT_RTCPTUPLE) &&
           verifier.VerifyTable(rtcpTuple()) &&
           verifier.EndTable();
  }
  GetStatsResponseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(GetStatsResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<GetStatsResponse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const GetStatsResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct GetStatsResponseBuilder {
  typedef GetStatsResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_base(::flatbuffers::Offset<FBS::Transport::Stats> base) {
    fbb_.AddOffset(GetStatsResponse::VT_BASE, base);
  }
  void add_rtcpMux(bool rtcpMux) {
    fbb_.AddElement<uint8_t>(GetStatsResponse::VT_RTCPMUX, static_cast<uint8_t>(rtcpMux), 0);
  }
  void add_comedia(bool comedia) {
    fbb_.AddElement<uint8_t>(GetStatsResponse::VT_COMEDIA, static_cast<uint8_t>(comedia), 0);
  }
  void add_tuple(::flatbuffers::Offset<FBS::Transport::Tuple> tuple) {
    fbb_.AddOffset(GetStatsResponse::VT_TUPLE, tuple);
  }
  void add_rtcpTuple(::flatbuffers::Offset<FBS::Transport::Tuple> rtcpTuple) {
    fbb_.AddOffset(GetStatsResponse::VT_RTCPTUPLE, rtcpTuple);
  }
  explicit GetStatsResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GetStatsResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GetStatsResponse>(end);
    fbb_.Required(o, GetStatsResponse::VT_BASE);
    fbb_.Required(o, GetStatsResponse::VT_TUPLE);
    return o;
  }
};

inline ::flatbuffers::Offset<GetStatsResponse> CreateGetStatsResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<FBS::Transport::Stats> base = 0,
    bool rtcpMux = false,
    bool comedia = false,
    ::flatbuffers::Offset<FBS::Transport::Tuple> tuple = 0,
    ::flatbuffers::Offset<FBS::Transport::Tuple> rtcpTuple = 0) {
  GetStatsResponseBuilder builder_(_fbb);
  builder_.add_rtcpTuple(rtcpTuple);
  builder_.add_tuple(tuple);
  builder_.add_base(base);
  builder_.add_comedia(comedia);
  builder_.add_rtcpMux(rtcpMux);
  return builder_.Finish();
}

::flatbuffers::Offset<GetStatsResponse> CreateGetStatsResponse(::flatbuffers::FlatBufferBuilder &_fbb, const GetStatsResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct TupleNotificationT : public ::flatbuffers::NativeTable {
  typedef TupleNotification TableType;
  std::unique_ptr<FBS::Transport::TupleT> tuple{};
  TupleNotificationT() = default;
  TupleNotificationT(const TupleNotificationT &o);
  TupleNotificationT(TupleNotificationT&&) FLATBUFFERS_NOEXCEPT = default;
  TupleNotificationT &operator=(TupleNotificationT o) FLATBUFFERS_NOEXCEPT;
};

struct TupleNotification FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TupleNotificationT NativeTableType;
  typedef TupleNotificationBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return TupleNotificationTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TUPLE = 4
  };
  const FBS::Transport::Tuple *tuple() const {
    return GetPointer<const FBS::Transport::Tuple *>(VT_TUPLE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_TUPLE) &&
           verifier.VerifyTable(tuple()) &&
           verifier.EndTable();
  }
  TupleNotificationT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(TupleNotificationT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<TupleNotification> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TupleNotificationT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct TupleNotificationBuilder {
  typedef TupleNotification Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_tuple(::flatbuffers::Offset<FBS::Transport::Tuple> tuple) {
    fbb_.AddOffset(TupleNotification::VT_TUPLE, tuple);
  }
  explicit TupleNotificationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TupleNotification> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TupleNotification>(end);
    fbb_.Required(o, TupleNotification::VT_TUPLE);
    return o;
  }
};

inline ::flatbuffers::Offset<TupleNotification> CreateTupleNotification(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<FBS::Transport::Tuple> tuple = 0) {
  TupleNotificationBuilder builder_(_fbb);
  builder_.add_tuple(tuple);
  return builder_.Finish();
}

::flatbuffers::Offset<TupleNotification> CreateTupleNotification(::flatbuffers::FlatBufferBuilder &_fbb, const TupleNotificationT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct RtcpTupleNotificationT : public ::flatbuffers::NativeTable {
  typedef RtcpTupleNotification TableType;
  std::unique_ptr<FBS::Transport::TupleT> tuple{};
  RtcpTupleNotificationT() = default;
  RtcpTupleNotificationT(const RtcpTupleNotificationT &o);
  RtcpTupleNotificationT(RtcpTupleNotificationT&&) FLATBUFFERS_NOEXCEPT = default;
  RtcpTupleNotificationT &operator=(RtcpTupleNotificationT o) FLATBUFFERS_NOEXCEPT;
};

struct RtcpTupleNotification FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RtcpTupleNotificationT NativeTableType;
  typedef RtcpTupleNotificationBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return RtcpTupleNotificationTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TUPLE = 4
  };
  const FBS::Transport::Tuple *tuple() const {
    return GetPointer<const FBS::Transport::Tuple *>(VT_TUPLE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_TUPLE) &&
           verifier.VerifyTable(tuple()) &&
           verifier.EndTable();
  }
  RtcpTupleNotificationT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(RtcpTupleNotificationT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<RtcpTupleNotification> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RtcpTupleNotificationT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct RtcpTupleNotificationBuilder {
  typedef RtcpTupleNotification Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_tuple(::flatbuffers::Offset<FBS::Transport::Tuple> tuple) {
    fbb_.AddOffset(RtcpTupleNotification::VT_TUPLE, tuple);
  }
  explicit RtcpTupleNotificationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RtcpTupleNotification> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RtcpTupleNotification>(end);
    fbb_.Required(o, RtcpTupleNotification::VT_TUPLE);
    return o;
  }
};

inline ::flatbuffers::Offset<RtcpTupleNotification> CreateRtcpTupleNotification(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<FBS::Transport::Tuple> tuple = 0) {
  RtcpTupleNotificationBuilder builder_(_fbb);
  builder_.add_tuple(tuple);
  return builder_.Finish();
}

::flatbuffers::Offset<RtcpTupleNotification> CreateRtcpTupleNotification(::flatbuffers::FlatBufferBuilder &_fbb, const RtcpTupleNotificationT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline PlainTransportOptionsT::PlainTransportOptionsT(const PlainTransportOptionsT &o)
      : base((o.base) ? new FBS::Transport::OptionsT(*o.base) : nullptr),
        listenInfo((o.listenInfo) ? new FBS::Transport::ListenInfoT(*o.listenInfo) : nullptr),
        rtcpListenInfo((o.rtcpListenInfo) ? new FBS::Transport::ListenInfoT(*o.rtcpListenInfo) : nullptr),
        rtcpMux(o.rtcpMux),
        comedia(o.comedia),
        enableSrtp(o.enableSrtp),
        srtpCryptoSuite(o.srtpCryptoSuite) {
}

inline PlainTransportOptionsT &PlainTransportOptionsT::operator=(PlainTransportOptionsT o) FLATBUFFERS_NOEXCEPT {
  std::swap(base, o.base);
  std::swap(listenInfo, o.listenInfo);
  std::swap(rtcpListenInfo, o.rtcpListenInfo);
  std::swap(rtcpMux, o.rtcpMux);
  std::swap(comedia, o.comedia);
  std::swap(enableSrtp, o.enableSrtp);
  std::swap(srtpCryptoSuite, o.srtpCryptoSuite);
  return *this;
}

inline PlainTransportOptionsT *PlainTransportOptions::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<PlainTransportOptionsT>(new PlainTransportOptionsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void PlainTransportOptions::UnPackTo(PlainTransportOptionsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = base(); if (_e) { if(_o->base) { _e->UnPackTo(_o->base.get(), _resolver); } else { _o->base = std::unique_ptr<FBS::Transport::OptionsT>(_e->UnPack(_resolver)); } } else if (_o->base) { _o->base.reset(); } }
  { auto _e = listenInfo(); if (_e) { if(_o->listenInfo) { _e->UnPackTo(_o->listenInfo.get(), _resolver); } else { _o->listenInfo = std::unique_ptr<FBS::Transport::ListenInfoT>(_e->UnPack(_resolver)); } } else if (_o->listenInfo) { _o->listenInfo.reset(); } }
  { auto _e = rtcpListenInfo(); if (_e) { if(_o->rtcpListenInfo) { _e->UnPackTo(_o->rtcpListenInfo.get(), _resolver); } else { _o->rtcpListenInfo = std::unique_ptr<FBS::Transport::ListenInfoT>(_e->UnPack(_resolver)); } } else if (_o->rtcpListenInfo) { _o->rtcpListenInfo.reset(); } }
  { auto _e = rtcpMux(); _o->rtcpMux = _e; }
  { auto _e = comedia(); _o->comedia = _e; }
  { auto _e = enableSrtp(); _o->enableSrtp = _e; }
  { auto _e = srtpCryptoSuite(); _o->srtpCryptoSuite = _e; }
}

inline ::flatbuffers::Offset<PlainTransportOptions> PlainTransportOptions::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PlainTransportOptionsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreatePlainTransportOptions(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<PlainTransportOptions> CreatePlainTransportOptions(::flatbuffers::FlatBufferBuilder &_fbb, const PlainTransportOptionsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const PlainTransportOptionsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _base = _o->base ? CreateOptions(_fbb, _o->base.get(), _rehasher) : 0;
  auto _listenInfo = _o->listenInfo ? CreateListenInfo(_fbb, _o->listenInfo.get(), _rehasher) : 0;
  auto _rtcpListenInfo = _o->rtcpListenInfo ? CreateListenInfo(_fbb, _o->rtcpListenInfo.get(), _rehasher) : 0;
  auto _rtcpMux = _o->rtcpMux;
  auto _comedia = _o->comedia;
  auto _enableSrtp = _o->enableSrtp;
  auto _srtpCryptoSuite = _o->srtpCryptoSuite;
  return FBS::PlainTransport::CreatePlainTransportOptions(
      _fbb,
      _base,
      _listenInfo,
      _rtcpListenInfo,
      _rtcpMux,
      _comedia,
      _enableSrtp,
      _srtpCryptoSuite);
}

inline ConnectRequestT::ConnectRequestT(const ConnectRequestT &o)
      : ip(o.ip),
        port(o.port),
        rtcpPort(o.rtcpPort),
        srtpParameters((o.srtpParameters) ? new FBS::SrtpParameters::SrtpParametersT(*o.srtpParameters) : nullptr) {
}

inline ConnectRequestT &ConnectRequestT::operator=(ConnectRequestT o) FLATBUFFERS_NOEXCEPT {
  std::swap(ip, o.ip);
  std::swap(port, o.port);
  std::swap(rtcpPort, o.rtcpPort);
  std::swap(srtpParameters, o.srtpParameters);
  return *this;
}

inline ConnectRequestT *ConnectRequest::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ConnectRequestT>(new ConnectRequestT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ConnectRequest::UnPackTo(ConnectRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = ip(); if (_e) _o->ip = _e->str(); }
  { auto _e = port(); _o->port = _e; }
  { auto _e = rtcpPort(); _o->rtcpPort = _e; }
  { auto _e = srtpParameters(); if (_e) { if(_o->srtpParameters) { _e->UnPackTo(_o->srtpParameters.get(), _resolver); } else { _o->srtpParameters = std::unique_ptr<FBS::SrtpParameters::SrtpParametersT>(_e->UnPack(_resolver)); } } else if (_o->srtpParameters) { _o->srtpParameters.reset(); } }
}

inline ::flatbuffers::Offset<ConnectRequest> ConnectRequest::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ConnectRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateConnectRequest(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ConnectRequest> CreateConnectRequest(::flatbuffers::FlatBufferBuilder &_fbb, const ConnectRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ConnectRequestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _ip = _o->ip.empty() ? 0 : _fbb.CreateString(_o->ip);
  auto _port = _o->port;
  auto _rtcpPort = _o->rtcpPort;
  auto _srtpParameters = _o->srtpParameters ? CreateSrtpParameters(_fbb, _o->srtpParameters.get(), _rehasher) : 0;
  return FBS::PlainTransport::CreateConnectRequest(
      _fbb,
      _ip,
      _port,
      _rtcpPort,
      _srtpParameters);
}

inline ConnectResponseT::ConnectResponseT(const ConnectResponseT &o)
      : tuple((o.tuple) ? new FBS::Transport::TupleT(*o.tuple) : nullptr),
        rtcpTuple((o.rtcpTuple) ? new FBS::Transport::TupleT(*o.rtcpTuple) : nullptr),
        srtpParameters((o.srtpParameters) ? new FBS::SrtpParameters::SrtpParametersT(*o.srtpParameters) : nullptr) {
}

inline ConnectResponseT &ConnectResponseT::operator=(ConnectResponseT o) FLATBUFFERS_NOEXCEPT {
  std::swap(tuple, o.tuple);
  std::swap(rtcpTuple, o.rtcpTuple);
  std::swap(srtpParameters, o.srtpParameters);
  return *this;
}

inline ConnectResponseT *ConnectResponse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ConnectResponseT>(new ConnectResponseT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ConnectResponse::UnPackTo(ConnectResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = tuple(); if (_e) { if(_o->tuple) { _e->UnPackTo(_o->tuple.get(), _resolver); } else { _o->tuple = std::unique_ptr<FBS::Transport::TupleT>(_e->UnPack(_resolver)); } } else if (_o->tuple) { _o->tuple.reset(); } }
  { auto _e = rtcpTuple(); if (_e) { if(_o->rtcpTuple) { _e->UnPackTo(_o->rtcpTuple.get(), _resolver); } else { _o->rtcpTuple = std::unique_ptr<FBS::Transport::TupleT>(_e->UnPack(_resolver)); } } else if (_o->rtcpTuple) { _o->rtcpTuple.reset(); } }
  { auto _e = srtpParameters(); if (_e) { if(_o->srtpParameters) { _e->UnPackTo(_o->srtpParameters.get(), _resolver); } else { _o->srtpParameters = std::unique_ptr<FBS::SrtpParameters::SrtpParametersT>(_e->UnPack(_resolver)); } } else if (_o->srtpParameters) { _o->srtpParameters.reset(); } }
}

inline ::flatbuffers::Offset<ConnectResponse> ConnectResponse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ConnectResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateConnectResponse(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ConnectResponse> CreateConnectResponse(::flatbuffers::FlatBufferBuilder &_fbb, const ConnectResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ConnectResponseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _tuple = _o->tuple ? CreateTuple(_fbb, _o->tuple.get(), _rehasher) : 0;
  auto _rtcpTuple = _o->rtcpTuple ? CreateTuple(_fbb, _o->rtcpTuple.get(), _rehasher) : 0;
  auto _srtpParameters = _o->srtpParameters ? CreateSrtpParameters(_fbb, _o->srtpParameters.get(), _rehasher) : 0;
  return FBS::PlainTransport::CreateConnectResponse(
      _fbb,
      _tuple,
      _rtcpTuple,
      _srtpParameters);
}

inline DumpResponseT::DumpResponseT(const DumpResponseT &o)
      : base((o.base) ? new FBS::Transport::DumpT(*o.base) : nullptr),
        rtcpMux(o.rtcpMux),
        comedia(o.comedia),
        tuple((o.tuple) ? new FBS::Transport::TupleT(*o.tuple) : nullptr),
        rtcpTuple((o.rtcpTuple) ? new FBS::Transport::TupleT(*o.rtcpTuple) : nullptr),
        srtpParameters((o.srtpParameters) ? new FBS::SrtpParameters::SrtpParametersT(*o.srtpParameters) : nullptr) {
}

inline DumpResponseT &DumpResponseT::operator=(DumpResponseT o) FLATBUFFERS_NOEXCEPT {
  std::swap(base, o.base);
  std::swap(rtcpMux, o.rtcpMux);
  std::swap(comedia, o.comedia);
  std::swap(tuple, o.tuple);
  std::swap(rtcpTuple, o.rtcpTuple);
  std::swap(srtpParameters, o.srtpParameters);
  return *this;
}

inline DumpResponseT *DumpResponse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<DumpResponseT>(new DumpResponseT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void DumpResponse::UnPackTo(DumpResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = base(); if (_e) { if(_o->base) { _e->UnPackTo(_o->base.get(), _resolver); } else { _o->base = std::unique_ptr<FBS::Transport::DumpT>(_e->UnPack(_resolver)); } } else if (_o->base) { _o->base.reset(); } }
  { auto _e = rtcpMux(); _o->rtcpMux = _e; }
  { auto _e = comedia(); _o->comedia = _e; }
  { auto _e = tuple(); if (_e) { if(_o->tuple) { _e->UnPackTo(_o->tuple.get(), _resolver); } else { _o->tuple = std::unique_ptr<FBS::Transport::TupleT>(_e->UnPack(_resolver)); } } else if (_o->tuple) { _o->tuple.reset(); } }
  { auto _e = rtcpTuple(); if (_e) { if(_o->rtcpTuple) { _e->UnPackTo(_o->rtcpTuple.get(), _resolver); } else { _o->rtcpTuple = std::unique_ptr<FBS::Transport::TupleT>(_e->UnPack(_resolver)); } } else if (_o->rtcpTuple) { _o->rtcpTuple.reset(); } }
  { auto _e = srtpParameters(); if (_e) { if(_o->srtpParameters) { _e->UnPackTo(_o->srtpParameters.get(), _resolver); } else { _o->srtpParameters = std::unique_ptr<FBS::SrtpParameters::SrtpParametersT>(_e->UnPack(_resolver)); } } else if (_o->srtpParameters) { _o->srtpParameters.reset(); } }
}

inline ::flatbuffers::Offset<DumpResponse> DumpResponse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DumpResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateDumpResponse(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<DumpResponse> CreateDumpResponse(::flatbuffers::FlatBufferBuilder &_fbb, const DumpResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const DumpResponseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _base = _o->base ? CreateDump(_fbb, _o->base.get(), _rehasher) : 0;
  auto _rtcpMux = _o->rtcpMux;
  auto _comedia = _o->comedia;
  auto _tuple = _o->tuple ? CreateTuple(_fbb, _o->tuple.get(), _rehasher) : 0;
  auto _rtcpTuple = _o->rtcpTuple ? CreateTuple(_fbb, _o->rtcpTuple.get(), _rehasher) : 0;
  auto _srtpParameters = _o->srtpParameters ? CreateSrtpParameters(_fbb, _o->srtpParameters.get(), _rehasher) : 0;
  return FBS::PlainTransport::CreateDumpResponse(
      _fbb,
      _base,
      _rtcpMux,
      _comedia,
      _tuple,
      _rtcpTuple,
      _srtpParameters);
}

inline GetStatsResponseT::GetStatsResponseT(const GetStatsResponseT &o)
      : base((o.base) ? new FBS::Transport::StatsT(*o.base) : nullptr),
        rtcpMux(o.rtcpMux),
        comedia(o.comedia),
        tuple((o.tuple) ? new FBS::Transport::TupleT(*o.tuple) : nullptr),
        rtcpTuple((o.rtcpTuple) ? new FBS::Transport::TupleT(*o.rtcpTuple) : nullptr) {
}

inline GetStatsResponseT &GetStatsResponseT::operator=(GetStatsResponseT o) FLATBUFFERS_NOEXCEPT {
  std::swap(base, o.base);
  std::swap(rtcpMux, o.rtcpMux);
  std::swap(comedia, o.comedia);
  std::swap(tuple, o.tuple);
  std::swap(rtcpTuple, o.rtcpTuple);
  return *this;
}

inline GetStatsResponseT *GetStatsResponse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<GetStatsResponseT>(new GetStatsResponseT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void GetStatsResponse::UnPackTo(GetStatsResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = base(); if (_e) { if(_o->base) { _e->UnPackTo(_o->base.get(), _resolver); } else { _o->base = std::unique_ptr<FBS::Transport::StatsT>(_e->UnPack(_resolver)); } } else if (_o->base) { _o->base.reset(); } }
  { auto _e = rtcpMux(); _o->rtcpMux = _e; }
  { auto _e = comedia(); _o->comedia = _e; }
  { auto _e = tuple(); if (_e) { if(_o->tuple) { _e->UnPackTo(_o->tuple.get(), _resolver); } else { _o->tuple = std::unique_ptr<FBS::Transport::TupleT>(_e->UnPack(_resolver)); } } else if (_o->tuple) { _o->tuple.reset(); } }
  { auto _e = rtcpTuple(); if (_e) { if(_o->rtcpTuple) { _e->UnPackTo(_o->rtcpTuple.get(), _resolver); } else { _o->rtcpTuple = std::unique_ptr<FBS::Transport::TupleT>(_e->UnPack(_resolver)); } } else if (_o->rtcpTuple) { _o->rtcpTuple.reset(); } }
}

inline ::flatbuffers::Offset<GetStatsResponse> GetStatsResponse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const GetStatsResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateGetStatsResponse(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<GetStatsResponse> CreateGetStatsResponse(::flatbuffers::FlatBufferBuilder &_fbb, const GetStatsResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const GetStatsResponseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _base = _o->base ? CreateStats(_fbb, _o->base.get(), _rehasher) : 0;
  auto _rtcpMux = _o->rtcpMux;
  auto _comedia = _o->comedia;
  auto _tuple = _o->tuple ? CreateTuple(_fbb, _o->tuple.get(), _rehasher) : 0;
  auto _rtcpTuple = _o->rtcpTuple ? CreateTuple(_fbb, _o->rtcpTuple.get(), _rehasher) : 0;
  return FBS::PlainTransport::CreateGetStatsResponse(
      _fbb,
      _base,
      _rtcpMux,
      _comedia,
      _tuple,
      _rtcpTuple);
}

inline TupleNotificationT::TupleNotificationT(const TupleNotificationT &o)
      : tuple((o.tuple) ? new FBS::Transport::TupleT(*o.tuple) : nullptr) {
}

inline TupleNotificationT &TupleNotificationT::operator=(TupleNotificationT o) FLATBUFFERS_NOEXCEPT {
  std::swap(tuple, o.tuple);
  return *this;
}

inline TupleNotificationT *TupleNotification::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<TupleNotificationT>(new TupleNotificationT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void TupleNotification::UnPackTo(TupleNotificationT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = tuple(); if (_e) { if(_o->tuple) { _e->UnPackTo(_o->tuple.get(), _resolver); } else { _o->tuple = std::unique_ptr<FBS::Transport::TupleT>(_e->UnPack(_resolver)); } } else if (_o->tuple) { _o->tuple.reset(); } }
}

inline ::flatbuffers::Offset<TupleNotification> TupleNotification::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TupleNotificationT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateTupleNotification(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<TupleNotification> CreateTupleNotification(::flatbuffers::FlatBufferBuilder &_fbb, const TupleNotificationT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const TupleNotificationT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _tuple = _o->tuple ? CreateTuple(_fbb, _o->tuple.get(), _rehasher) : 0;
  return FBS::PlainTransport::CreateTupleNotification(
      _fbb,
      _tuple);
}

inline RtcpTupleNotificationT::RtcpTupleNotificationT(const RtcpTupleNotificationT &o)
      : tuple((o.tuple) ? new FBS::Transport::TupleT(*o.tuple) : nullptr) {
}

inline RtcpTupleNotificationT &RtcpTupleNotificationT::operator=(RtcpTupleNotificationT o) FLATBUFFERS_NOEXCEPT {
  std::swap(tuple, o.tuple);
  return *this;
}

inline RtcpTupleNotificationT *RtcpTupleNotification::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<RtcpTupleNotificationT>(new RtcpTupleNotificationT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void RtcpTupleNotification::UnPackTo(RtcpTupleNotificationT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = tuple(); if (_e) { if(_o->tuple) { _e->UnPackTo(_o->tuple.get(), _resolver); } else { _o->tuple = std::unique_ptr<FBS::Transport::TupleT>(_e->UnPack(_resolver)); } } else if (_o->tuple) { _o->tuple.reset(); } }
}

inline ::flatbuffers::Offset<RtcpTupleNotification> RtcpTupleNotification::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RtcpTupleNotificationT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateRtcpTupleNotification(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<RtcpTupleNotification> CreateRtcpTupleNotification(::flatbuffers::FlatBufferBuilder &_fbb, const RtcpTupleNotificationT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const RtcpTupleNotificationT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _tuple = _o->tuple ? CreateTuple(_fbb, _o->tuple.get(), _rehasher) : 0;
  return FBS::PlainTransport::CreateRtcpTupleNotification(
      _fbb,
      _tuple);
}

inline const ::flatbuffers::TypeTable *PlainTransportOptionsTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SEQUENCE, 0, 0 },
    { ::flatbuffers::ET_SEQUENCE, 0, 1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 1 },
    { ::flatbuffers::ET_BOOL, 0, -1 },
    { ::flatbuffers::ET_BOOL, 0, -1 },
    { ::flatbuffers::ET_BOOL, 0, -1 },
    { ::flatbuffers::ET_UCHAR, 0, 2 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    FBS::Transport::OptionsTypeTable,
    FBS::Transport::ListenInfoTypeTable,
    FBS::SrtpParameters::SrtpCryptoSuiteTypeTable
  };
  static const char * const names[] = {
    "base",
    "listenInfo",
    "rtcpListenInfo",
    "rtcpMux",
    "comedia",
    "enableSrtp",
    "srtpCryptoSuite"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 7, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *ConnectRequestTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_USHORT, 0, -1 },
    { ::flatbuffers::ET_USHORT, 0, -1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    FBS::SrtpParameters::SrtpParametersTypeTable
  };
  static const char * const names[] = {
    "ip",
    "port",
    "rtcpPort",
    "srtpParameters"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 4, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *ConnectResponseTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SEQUENCE, 0, 0 },
    { ::flatbuffers::ET_SEQUENCE, 0, 0 },
    { ::flatbuffers::ET_SEQUENCE, 0, 1 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    FBS::Transport::TupleTypeTable,
    FBS::SrtpParameters::SrtpParametersTypeTable
  };
  static const char * const names[] = {
    "tuple",
    "rtcpTuple",
    "srtpParameters"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 3, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *DumpResponseTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SEQUENCE, 0, 0 },
    { ::flatbuffers::ET_BOOL, 0, -1 },
    { ::flatbuffers::ET_BOOL, 0, -1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 2 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    FBS::Transport::DumpTypeTable,
    FBS::Transport::TupleTypeTable,
    FBS::SrtpParameters::SrtpParametersTypeTable
  };
  static const char * const names[] = {
    "base",
    "rtcpMux",
    "comedia",
    "tuple",
    "rtcpTuple",
    "srtpParameters"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 6, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *GetStatsResponseTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SEQUENCE, 0, 0 },
    { ::flatbuffers::ET_BOOL, 0, -1 },
    { ::flatbuffers::ET_BOOL, 0, -1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 1 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    FBS::Transport::StatsTypeTable,
    FBS::Transport::TupleTypeTable
  };
  static const char * const names[] = {
    "base",
    "rtcpMux",
    "comedia",
    "tuple",
    "rtcpTuple"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 5, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *TupleNotificationTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SEQUENCE, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    FBS::Transport::TupleTypeTable
  };
  static const char * const names[] = {
    "tuple"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 1, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *RtcpTupleNotificationTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SEQUENCE, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    FBS::Transport::TupleTypeTable
  };
  static const char * const names[] = {
    "tuple"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 1, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

}  // namespace PlainTransport
}  // namespace FBS

#endif  // FLATBUFFERS_GENERATED_PLAINTRANSPORT_FBS_PLAINTRANSPORT_H_
