// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_RESPONSE_FBS_RESPONSE_H_
#define FLATBUFFERS_GENERATED_RESPONSE_FBS_RESPONSE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "consumer_generated.h"
#include "dataConsumer_generated.h"
#include "dataProducer_generated.h"
#include "producer_generated.h"
#include "router_generated.h"
#include "transport_generated.h"
#include "webRtcServer_generated.h"
#include "worker_generated.h"

namespace FBS {
namespace Response {

struct Response;
struct ResponseBuilder;
struct ResponseT;

inline const ::flatbuffers::TypeTable *ResponseTypeTable();

enum class Body : uint8_t {
  NONE = 0,
  Worker_DumpResponse = 1,
  Worker_ResourceUsageResponse = 2,
  WebRtcServer_DumpResponse = 3,
  Router_DumpResponse = 4,
  Transport_ProduceResponse = 5,
  Transport_ConsumeResponse = 6,
  Transport_RestartIceResponse = 7,
  PlainTransport_ConnectResponse = 8,
  PlainTransport_DumpResponse = 9,
  PlainTransport_GetStatsResponse = 10,
  PipeTransport_ConnectResponse = 11,
  PipeTransport_DumpResponse = 12,
  PipeTransport_GetStatsResponse = 13,
  DirectTransport_DumpResponse = 14,
  DirectTransport_GetStatsResponse = 15,
  WebRtcTransport_ConnectResponse = 16,
  WebRtcTransport_DumpResponse = 17,
  WebRtcTransport_GetStatsResponse = 18,
  Producer_DumpResponse = 19,
  Producer_GetStatsResponse = 20,
  Consumer_DumpResponse = 21,
  Consumer_GetStatsResponse = 22,
  Consumer_SetPreferredLayersResponse = 23,
  Consumer_SetPriorityResponse = 24,
  DataProducer_DumpResponse = 25,
  DataProducer_GetStatsResponse = 26,
  DataConsumer_GetBufferedAmountResponse = 27,
  DataConsumer_DumpResponse = 28,
  DataConsumer_GetStatsResponse = 29,
  DataConsumer_SetSubchannelsResponse = 30,
  DataConsumer_AddSubchannelResponse = 31,
  DataConsumer_RemoveSubchannelResponse = 32,
  MIN = NONE,
  MAX = DataConsumer_RemoveSubchannelResponse
};

inline const Body (&EnumValuesBody())[33] {
  static const Body values[] = {
    Body::NONE,
    Body::Worker_DumpResponse,
    Body::Worker_ResourceUsageResponse,
    Body::WebRtcServer_DumpResponse,
    Body::Router_DumpResponse,
    Body::Transport_ProduceResponse,
    Body::Transport_ConsumeResponse,
    Body::Transport_RestartIceResponse,
    Body::PlainTransport_ConnectResponse,
    Body::PlainTransport_DumpResponse,
    Body::PlainTransport_GetStatsResponse,
    Body::PipeTransport_ConnectResponse,
    Body::PipeTransport_DumpResponse,
    Body::PipeTransport_GetStatsResponse,
    Body::DirectTransport_DumpResponse,
    Body::DirectTransport_GetStatsResponse,
    Body::WebRtcTransport_ConnectResponse,
    Body::WebRtcTransport_DumpResponse,
    Body::WebRtcTransport_GetStatsResponse,
    Body::Producer_DumpResponse,
    Body::Producer_GetStatsResponse,
    Body::Consumer_DumpResponse,
    Body::Consumer_GetStatsResponse,
    Body::Consumer_SetPreferredLayersResponse,
    Body::Consumer_SetPriorityResponse,
    Body::DataProducer_DumpResponse,
    Body::DataProducer_GetStatsResponse,
    Body::DataConsumer_GetBufferedAmountResponse,
    Body::DataConsumer_DumpResponse,
    Body::DataConsumer_GetStatsResponse,
    Body::DataConsumer_SetSubchannelsResponse,
    Body::DataConsumer_AddSubchannelResponse,
    Body::DataConsumer_RemoveSubchannelResponse
  };
  return values;
}

inline const char * const *EnumNamesBody() {
  static const char * const names[34] = {
    "NONE",
    "Worker_DumpResponse",
    "Worker_ResourceUsageResponse",
    "WebRtcServer_DumpResponse",
    "Router_DumpResponse",
    "Transport_ProduceResponse",
    "Transport_ConsumeResponse",
    "Transport_RestartIceResponse",
    "PlainTransport_ConnectResponse",
    "PlainTransport_DumpResponse",
    "PlainTransport_GetStatsResponse",
    "PipeTransport_ConnectResponse",
    "PipeTransport_DumpResponse",
    "PipeTransport_GetStatsResponse",
    "DirectTransport_DumpResponse",
    "DirectTransport_GetStatsResponse",
    "WebRtcTransport_ConnectResponse",
    "WebRtcTransport_DumpResponse",
    "WebRtcTransport_GetStatsResponse",
    "Producer_DumpResponse",
    "Producer_GetStatsResponse",
    "Consumer_DumpResponse",
    "Consumer_GetStatsResponse",
    "Consumer_SetPreferredLayersResponse",
    "Consumer_SetPriorityResponse",
    "DataProducer_DumpResponse",
    "DataProducer_GetStatsResponse",
    "DataConsumer_GetBufferedAmountResponse",
    "DataConsumer_DumpResponse",
    "DataConsumer_GetStatsResponse",
    "DataConsumer_SetSubchannelsResponse",
    "DataConsumer_AddSubchannelResponse",
    "DataConsumer_RemoveSubchannelResponse",
    nullptr
  };
  return names;
}

inline const char *EnumNameBody(Body e) {
  if (::flatbuffers::IsOutRange(e, Body::NONE, Body::DataConsumer_RemoveSubchannelResponse)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesBody()[index];
}

template<typename T> struct BodyTraits {
  static const Body enum_value = Body::NONE;
};

template<> struct BodyTraits<FBS::Worker::DumpResponse> {
  static const Body enum_value = Body::Worker_DumpResponse;
};

template<> struct BodyTraits<FBS::Worker::ResourceUsageResponse> {
  static const Body enum_value = Body::Worker_ResourceUsageResponse;
};

template<> struct BodyTraits<FBS::WebRtcServer::DumpResponse> {
  static const Body enum_value = Body::WebRtcServer_DumpResponse;
};

template<> struct BodyTraits<FBS::Router::DumpResponse> {
  static const Body enum_value = Body::Router_DumpResponse;
};

template<> struct BodyTraits<FBS::Transport::ProduceResponse> {
  static const Body enum_value = Body::Transport_ProduceResponse;
};

template<> struct BodyTraits<FBS::Transport::ConsumeResponse> {
  static const Body enum_value = Body::Transport_ConsumeResponse;
};

template<> struct BodyTraits<FBS::Transport::RestartIceResponse> {
  static const Body enum_value = Body::Transport_RestartIceResponse;
};

template<> struct BodyTraits<FBS::PlainTransport::ConnectResponse> {
  static const Body enum_value = Body::PlainTransport_ConnectResponse;
};

template<> struct BodyTraits<FBS::PlainTransport::DumpResponse> {
  static const Body enum_value = Body::PlainTransport_DumpResponse;
};

template<> struct BodyTraits<FBS::PlainTransport::GetStatsResponse> {
  static const Body enum_value = Body::PlainTransport_GetStatsResponse;
};

template<> struct BodyTraits<FBS::PipeTransport::ConnectResponse> {
  static const Body enum_value = Body::PipeTransport_ConnectResponse;
};

template<> struct BodyTraits<FBS::PipeTransport::DumpResponse> {
  static const Body enum_value = Body::PipeTransport_DumpResponse;
};

template<> struct BodyTraits<FBS::PipeTransport::GetStatsResponse> {
  static const Body enum_value = Body::PipeTransport_GetStatsResponse;
};

template<> struct BodyTraits<FBS::DirectTransport::DumpResponse> {
  static const Body enum_value = Body::DirectTransport_DumpResponse;
};

template<> struct BodyTraits<FBS::DirectTransport::GetStatsResponse> {
  static const Body enum_value = Body::DirectTransport_GetStatsResponse;
};

template<> struct BodyTraits<FBS::WebRtcTransport::ConnectResponse> {
  static const Body enum_value = Body::WebRtcTransport_ConnectResponse;
};

template<> struct BodyTraits<FBS::WebRtcTransport::DumpResponse> {
  static const Body enum_value = Body::WebRtcTransport_DumpResponse;
};

template<> struct BodyTraits<FBS::WebRtcTransport::GetStatsResponse> {
  static const Body enum_value = Body::WebRtcTransport_GetStatsResponse;
};

template<> struct BodyTraits<FBS::Producer::DumpResponse> {
  static const Body enum_value = Body::Producer_DumpResponse;
};

template<> struct BodyTraits<FBS::Producer::GetStatsResponse> {
  static const Body enum_value = Body::Producer_GetStatsResponse;
};

template<> struct BodyTraits<FBS::Consumer::DumpResponse> {
  static const Body enum_value = Body::Consumer_DumpResponse;
};

template<> struct BodyTraits<FBS::Consumer::GetStatsResponse> {
  static const Body enum_value = Body::Consumer_GetStatsResponse;
};

template<> struct BodyTraits<FBS::Consumer::SetPreferredLayersResponse> {
  static const Body enum_value = Body::Consumer_SetPreferredLayersResponse;
};

template<> struct BodyTraits<FBS::Consumer::SetPriorityResponse> {
  static const Body enum_value = Body::Consumer_SetPriorityResponse;
};

template<> struct BodyTraits<FBS::DataProducer::DumpResponse> {
  static const Body enum_value = Body::DataProducer_DumpResponse;
};

template<> struct BodyTraits<FBS::DataProducer::GetStatsResponse> {
  static const Body enum_value = Body::DataProducer_GetStatsResponse;
};

template<> struct BodyTraits<FBS::DataConsumer::GetBufferedAmountResponse> {
  static const Body enum_value = Body::DataConsumer_GetBufferedAmountResponse;
};

template<> struct BodyTraits<FBS::DataConsumer::DumpResponse> {
  static const Body enum_value = Body::DataConsumer_DumpResponse;
};

template<> struct BodyTraits<FBS::DataConsumer::GetStatsResponse> {
  static const Body enum_value = Body::DataConsumer_GetStatsResponse;
};

template<> struct BodyTraits<FBS::DataConsumer::SetSubchannelsResponse> {
  static const Body enum_value = Body::DataConsumer_SetSubchannelsResponse;
};

template<> struct BodyTraits<FBS::DataConsumer::AddSubchannelResponse> {
  static const Body enum_value = Body::DataConsumer_AddSubchannelResponse;
};

template<> struct BodyTraits<FBS::DataConsumer::RemoveSubchannelResponse> {
  static const Body enum_value = Body::DataConsumer_RemoveSubchannelResponse;
};

template<typename T> struct BodyUnionTraits {
  static const Body enum_value = Body::NONE;
};

template<> struct BodyUnionTraits<FBS::Worker::DumpResponseT> {
  static const Body enum_value = Body::Worker_DumpResponse;
};

template<> struct BodyUnionTraits<FBS::Worker::ResourceUsageResponseT> {
  static const Body enum_value = Body::Worker_ResourceUsageResponse;
};

template<> struct BodyUnionTraits<FBS::WebRtcServer::DumpResponseT> {
  static const Body enum_value = Body::WebRtcServer_DumpResponse;
};

template<> struct BodyUnionTraits<FBS::Router::DumpResponseT> {
  static const Body enum_value = Body::Router_DumpResponse;
};

template<> struct BodyUnionTraits<FBS::Transport::ProduceResponseT> {
  static const Body enum_value = Body::Transport_ProduceResponse;
};

template<> struct BodyUnionTraits<FBS::Transport::ConsumeResponseT> {
  static const Body enum_value = Body::Transport_ConsumeResponse;
};

template<> struct BodyUnionTraits<FBS::Transport::RestartIceResponseT> {
  static const Body enum_value = Body::Transport_RestartIceResponse;
};

template<> struct BodyUnionTraits<FBS::PlainTransport::ConnectResponseT> {
  static const Body enum_value = Body::PlainTransport_ConnectResponse;
};

template<> struct BodyUnionTraits<FBS::PlainTransport::DumpResponseT> {
  static const Body enum_value = Body::PlainTransport_DumpResponse;
};

template<> struct BodyUnionTraits<FBS::PlainTransport::GetStatsResponseT> {
  static const Body enum_value = Body::PlainTransport_GetStatsResponse;
};

template<> struct BodyUnionTraits<FBS::PipeTransport::ConnectResponseT> {
  static const Body enum_value = Body::PipeTransport_ConnectResponse;
};

template<> struct BodyUnionTraits<FBS::PipeTransport::DumpResponseT> {
  static const Body enum_value = Body::PipeTransport_DumpResponse;
};

template<> struct BodyUnionTraits<FBS::PipeTransport::GetStatsResponseT> {
  static const Body enum_value = Body::PipeTransport_GetStatsResponse;
};

template<> struct BodyUnionTraits<FBS::DirectTransport::DumpResponseT> {
  static const Body enum_value = Body::DirectTransport_DumpResponse;
};

template<> struct BodyUnionTraits<FBS::DirectTransport::GetStatsResponseT> {
  static const Body enum_value = Body::DirectTransport_GetStatsResponse;
};

template<> struct BodyUnionTraits<FBS::WebRtcTransport::ConnectResponseT> {
  static const Body enum_value = Body::WebRtcTransport_ConnectResponse;
};

template<> struct BodyUnionTraits<FBS::WebRtcTransport::DumpResponseT> {
  static const Body enum_value = Body::WebRtcTransport_DumpResponse;
};

template<> struct BodyUnionTraits<FBS::WebRtcTransport::GetStatsResponseT> {
  static const Body enum_value = Body::WebRtcTransport_GetStatsResponse;
};

template<> struct BodyUnionTraits<FBS::Producer::DumpResponseT> {
  static const Body enum_value = Body::Producer_DumpResponse;
};

template<> struct BodyUnionTraits<FBS::Producer::GetStatsResponseT> {
  static const Body enum_value = Body::Producer_GetStatsResponse;
};

template<> struct BodyUnionTraits<FBS::Consumer::DumpResponseT> {
  static const Body enum_value = Body::Consumer_DumpResponse;
};

template<> struct BodyUnionTraits<FBS::Consumer::GetStatsResponseT> {
  static const Body enum_value = Body::Consumer_GetStatsResponse;
};

template<> struct BodyUnionTraits<FBS::Consumer::SetPreferredLayersResponseT> {
  static const Body enum_value = Body::Consumer_SetPreferredLayersResponse;
};

template<> struct BodyUnionTraits<FBS::Consumer::SetPriorityResponseT> {
  static const Body enum_value = Body::Consumer_SetPriorityResponse;
};

template<> struct BodyUnionTraits<FBS::DataProducer::DumpResponseT> {
  static const Body enum_value = Body::DataProducer_DumpResponse;
};

template<> struct BodyUnionTraits<FBS::DataProducer::GetStatsResponseT> {
  static const Body enum_value = Body::DataProducer_GetStatsResponse;
};

template<> struct BodyUnionTraits<FBS::DataConsumer::GetBufferedAmountResponseT> {
  static const Body enum_value = Body::DataConsumer_GetBufferedAmountResponse;
};

template<> struct BodyUnionTraits<FBS::DataConsumer::DumpResponseT> {
  static const Body enum_value = Body::DataConsumer_DumpResponse;
};

template<> struct BodyUnionTraits<FBS::DataConsumer::GetStatsResponseT> {
  static const Body enum_value = Body::DataConsumer_GetStatsResponse;
};

template<> struct BodyUnionTraits<FBS::DataConsumer::SetSubchannelsResponseT> {
  static const Body enum_value = Body::DataConsumer_SetSubchannelsResponse;
};

template<> struct BodyUnionTraits<FBS::DataConsumer::AddSubchannelResponseT> {
  static const Body enum_value = Body::DataConsumer_AddSubchannelResponse;
};

template<> struct BodyUnionTraits<FBS::DataConsumer::RemoveSubchannelResponseT> {
  static const Body enum_value = Body::DataConsumer_RemoveSubchannelResponse;
};

struct BodyUnion {
  Body type;
  void *value;

  BodyUnion() : type(Body::NONE), value(nullptr) {}
  BodyUnion(BodyUnion&& u) FLATBUFFERS_NOEXCEPT :
    type(Body::NONE), value(nullptr)
    { std::swap(type, u.type); std::swap(value, u.value); }
  BodyUnion(const BodyUnion &);
  BodyUnion &operator=(const BodyUnion &u)
    { BodyUnion t(u); std::swap(type, t.type); std::swap(value, t.value); return *this; }
  BodyUnion &operator=(BodyUnion &&u) FLATBUFFERS_NOEXCEPT
    { std::swap(type, u.type); std::swap(value, u.value); return *this; }
  ~BodyUnion() { Reset(); }

  void Reset();

  template <typename T>
  void Set(T&& val) {
    typedef typename std::remove_reference<T>::type RT;
    Reset();
    type = BodyUnionTraits<RT>::enum_value;
    if (type != Body::NONE) {
      value = new RT(std::forward<T>(val));
    }
  }

  static void *UnPack(const void *obj, Body type, const ::flatbuffers::resolver_function_t *resolver);
  ::flatbuffers::Offset<void> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr) const;

  FBS::Worker::DumpResponseT *AsWorker_DumpResponse() {
    return type == Body::Worker_DumpResponse ?
      reinterpret_cast<FBS::Worker::DumpResponseT *>(value) : nullptr;
  }
  const FBS::Worker::DumpResponseT *AsWorker_DumpResponse() const {
    return type == Body::Worker_DumpResponse ?
      reinterpret_cast<const FBS::Worker::DumpResponseT *>(value) : nullptr;
  }
  FBS::Worker::ResourceUsageResponseT *AsWorker_ResourceUsageResponse() {
    return type == Body::Worker_ResourceUsageResponse ?
      reinterpret_cast<FBS::Worker::ResourceUsageResponseT *>(value) : nullptr;
  }
  const FBS::Worker::ResourceUsageResponseT *AsWorker_ResourceUsageResponse() const {
    return type == Body::Worker_ResourceUsageResponse ?
      reinterpret_cast<const FBS::Worker::ResourceUsageResponseT *>(value) : nullptr;
  }
  FBS::WebRtcServer::DumpResponseT *AsWebRtcServer_DumpResponse() {
    return type == Body::WebRtcServer_DumpResponse ?
      reinterpret_cast<FBS::WebRtcServer::DumpResponseT *>(value) : nullptr;
  }
  const FBS::WebRtcServer::DumpResponseT *AsWebRtcServer_DumpResponse() const {
    return type == Body::WebRtcServer_DumpResponse ?
      reinterpret_cast<const FBS::WebRtcServer::DumpResponseT *>(value) : nullptr;
  }
  FBS::Router::DumpResponseT *AsRouter_DumpResponse() {
    return type == Body::Router_DumpResponse ?
      reinterpret_cast<FBS::Router::DumpResponseT *>(value) : nullptr;
  }
  const FBS::Router::DumpResponseT *AsRouter_DumpResponse() const {
    return type == Body::Router_DumpResponse ?
      reinterpret_cast<const FBS::Router::DumpResponseT *>(value) : nullptr;
  }
  FBS::Transport::ProduceResponseT *AsTransport_ProduceResponse() {
    return type == Body::Transport_ProduceResponse ?
      reinterpret_cast<FBS::Transport::ProduceResponseT *>(value) : nullptr;
  }
  const FBS::Transport::ProduceResponseT *AsTransport_ProduceResponse() const {
    return type == Body::Transport_ProduceResponse ?
      reinterpret_cast<const FBS::Transport::ProduceResponseT *>(value) : nullptr;
  }
  FBS::Transport::ConsumeResponseT *AsTransport_ConsumeResponse() {
    return type == Body::Transport_ConsumeResponse ?
      reinterpret_cast<FBS::Transport::ConsumeResponseT *>(value) : nullptr;
  }
  const FBS::Transport::ConsumeResponseT *AsTransport_ConsumeResponse() const {
    return type == Body::Transport_ConsumeResponse ?
      reinterpret_cast<const FBS::Transport::ConsumeResponseT *>(value) : nullptr;
  }
  FBS::Transport::RestartIceResponseT *AsTransport_RestartIceResponse() {
    return type == Body::Transport_RestartIceResponse ?
      reinterpret_cast<FBS::Transport::RestartIceResponseT *>(value) : nullptr;
  }
  const FBS::Transport::RestartIceResponseT *AsTransport_RestartIceResponse() const {
    return type == Body::Transport_RestartIceResponse ?
      reinterpret_cast<const FBS::Transport::RestartIceResponseT *>(value) : nullptr;
  }
  FBS::PlainTransport::ConnectResponseT *AsPlainTransport_ConnectResponse() {
    return type == Body::PlainTransport_ConnectResponse ?
      reinterpret_cast<FBS::PlainTransport::ConnectResponseT *>(value) : nullptr;
  }
  const FBS::PlainTransport::ConnectResponseT *AsPlainTransport_ConnectResponse() const {
    return type == Body::PlainTransport_ConnectResponse ?
      reinterpret_cast<const FBS::PlainTransport::ConnectResponseT *>(value) : nullptr;
  }
  FBS::PlainTransport::DumpResponseT *AsPlainTransport_DumpResponse() {
    return type == Body::PlainTransport_DumpResponse ?
      reinterpret_cast<FBS::PlainTransport::DumpResponseT *>(value) : nullptr;
  }
  const FBS::PlainTransport::DumpResponseT *AsPlainTransport_DumpResponse() const {
    return type == Body::PlainTransport_DumpResponse ?
      reinterpret_cast<const FBS::PlainTransport::DumpResponseT *>(value) : nullptr;
  }
  FBS::PlainTransport::GetStatsResponseT *AsPlainTransport_GetStatsResponse() {
    return type == Body::PlainTransport_GetStatsResponse ?
      reinterpret_cast<FBS::PlainTransport::GetStatsResponseT *>(value) : nullptr;
  }
  const FBS::PlainTransport::GetStatsResponseT *AsPlainTransport_GetStatsResponse() const {
    return type == Body::PlainTransport_GetStatsResponse ?
      reinterpret_cast<const FBS::PlainTransport::GetStatsResponseT *>(value) : nullptr;
  }
  FBS::PipeTransport::ConnectResponseT *AsPipeTransport_ConnectResponse() {
    return type == Body::PipeTransport_ConnectResponse ?
      reinterpret_cast<FBS::PipeTransport::ConnectResponseT *>(value) : nullptr;
  }
  const FBS::PipeTransport::ConnectResponseT *AsPipeTransport_ConnectResponse() const {
    return type == Body::PipeTransport_ConnectResponse ?
      reinterpret_cast<const FBS::PipeTransport::ConnectResponseT *>(value) : nullptr;
  }
  FBS::PipeTransport::DumpResponseT *AsPipeTransport_DumpResponse() {
    return type == Body::PipeTransport_DumpResponse ?
      reinterpret_cast<FBS::PipeTransport::DumpResponseT *>(value) : nullptr;
  }
  const FBS::PipeTransport::DumpResponseT *AsPipeTransport_DumpResponse() const {
    return type == Body::PipeTransport_DumpResponse ?
      reinterpret_cast<const FBS::PipeTransport::DumpResponseT *>(value) : nullptr;
  }
  FBS::PipeTransport::GetStatsResponseT *AsPipeTransport_GetStatsResponse() {
    return type == Body::PipeTransport_GetStatsResponse ?
      reinterpret_cast<FBS::PipeTransport::GetStatsResponseT *>(value) : nullptr;
  }
  const FBS::PipeTransport::GetStatsResponseT *AsPipeTransport_GetStatsResponse() const {
    return type == Body::PipeTransport_GetStatsResponse ?
      reinterpret_cast<const FBS::PipeTransport::GetStatsResponseT *>(value) : nullptr;
  }
  FBS::DirectTransport::DumpResponseT *AsDirectTransport_DumpResponse() {
    return type == Body::DirectTransport_DumpResponse ?
      reinterpret_cast<FBS::DirectTransport::DumpResponseT *>(value) : nullptr;
  }
  const FBS::DirectTransport::DumpResponseT *AsDirectTransport_DumpResponse() const {
    return type == Body::DirectTransport_DumpResponse ?
      reinterpret_cast<const FBS::DirectTransport::DumpResponseT *>(value) : nullptr;
  }
  FBS::DirectTransport::GetStatsResponseT *AsDirectTransport_GetStatsResponse() {
    return type == Body::DirectTransport_GetStatsResponse ?
      reinterpret_cast<FBS::DirectTransport::GetStatsResponseT *>(value) : nullptr;
  }
  const FBS::DirectTransport::GetStatsResponseT *AsDirectTransport_GetStatsResponse() const {
    return type == Body::DirectTransport_GetStatsResponse ?
      reinterpret_cast<const FBS::DirectTransport::GetStatsResponseT *>(value) : nullptr;
  }
  FBS::WebRtcTransport::ConnectResponseT *AsWebRtcTransport_ConnectResponse() {
    return type == Body::WebRtcTransport_ConnectResponse ?
      reinterpret_cast<FBS::WebRtcTransport::ConnectResponseT *>(value) : nullptr;
  }
  const FBS::WebRtcTransport::ConnectResponseT *AsWebRtcTransport_ConnectResponse() const {
    return type == Body::WebRtcTransport_ConnectResponse ?
      reinterpret_cast<const FBS::WebRtcTransport::ConnectResponseT *>(value) : nullptr;
  }
  FBS::WebRtcTransport::DumpResponseT *AsWebRtcTransport_DumpResponse() {
    return type == Body::WebRtcTransport_DumpResponse ?
      reinterpret_cast<FBS::WebRtcTransport::DumpResponseT *>(value) : nullptr;
  }
  const FBS::WebRtcTransport::DumpResponseT *AsWebRtcTransport_DumpResponse() const {
    return type == Body::WebRtcTransport_DumpResponse ?
      reinterpret_cast<const FBS::WebRtcTransport::DumpResponseT *>(value) : nullptr;
  }
  FBS::WebRtcTransport::GetStatsResponseT *AsWebRtcTransport_GetStatsResponse() {
    return type == Body::WebRtcTransport_GetStatsResponse ?
      reinterpret_cast<FBS::WebRtcTransport::GetStatsResponseT *>(value) : nullptr;
  }
  const FBS::WebRtcTransport::GetStatsResponseT *AsWebRtcTransport_GetStatsResponse() const {
    return type == Body::WebRtcTransport_GetStatsResponse ?
      reinterpret_cast<const FBS::WebRtcTransport::GetStatsResponseT *>(value) : nullptr;
  }
  FBS::Producer::DumpResponseT *AsProducer_DumpResponse() {
    return type == Body::Producer_DumpResponse ?
      reinterpret_cast<FBS::Producer::DumpResponseT *>(value) : nullptr;
  }
  const FBS::Producer::DumpResponseT *AsProducer_DumpResponse() const {
    return type == Body::Producer_DumpResponse ?
      reinterpret_cast<const FBS::Producer::DumpResponseT *>(value) : nullptr;
  }
  FBS::Producer::GetStatsResponseT *AsProducer_GetStatsResponse() {
    return type == Body::Producer_GetStatsResponse ?
      reinterpret_cast<FBS::Producer::GetStatsResponseT *>(value) : nullptr;
  }
  const FBS::Producer::GetStatsResponseT *AsProducer_GetStatsResponse() const {
    return type == Body::Producer_GetStatsResponse ?
      reinterpret_cast<const FBS::Producer::GetStatsResponseT *>(value) : nullptr;
  }
  FBS::Consumer::DumpResponseT *AsConsumer_DumpResponse() {
    return type == Body::Consumer_DumpResponse ?
      reinterpret_cast<FBS::Consumer::DumpResponseT *>(value) : nullptr;
  }
  const FBS::Consumer::DumpResponseT *AsConsumer_DumpResponse() const {
    return type == Body::Consumer_DumpResponse ?
      reinterpret_cast<const FBS::Consumer::DumpResponseT *>(value) : nullptr;
  }
  FBS::Consumer::GetStatsResponseT *AsConsumer_GetStatsResponse() {
    return type == Body::Consumer_GetStatsResponse ?
      reinterpret_cast<FBS::Consumer::GetStatsResponseT *>(value) : nullptr;
  }
  const FBS::Consumer::GetStatsResponseT *AsConsumer_GetStatsResponse() const {
    return type == Body::Consumer_GetStatsResponse ?
      reinterpret_cast<const FBS::Consumer::GetStatsResponseT *>(value) : nullptr;
  }
  FBS::Consumer::SetPreferredLayersResponseT *AsConsumer_SetPreferredLayersResponse() {
    return type == Body::Consumer_SetPreferredLayersResponse ?
      reinterpret_cast<FBS::Consumer::SetPreferredLayersResponseT *>(value) : nullptr;
  }
  const FBS::Consumer::SetPreferredLayersResponseT *AsConsumer_SetPreferredLayersResponse() const {
    return type == Body::Consumer_SetPreferredLayersResponse ?
      reinterpret_cast<const FBS::Consumer::SetPreferredLayersResponseT *>(value) : nullptr;
  }
  FBS::Consumer::SetPriorityResponseT *AsConsumer_SetPriorityResponse() {
    return type == Body::Consumer_SetPriorityResponse ?
      reinterpret_cast<FBS::Consumer::SetPriorityResponseT *>(value) : nullptr;
  }
  const FBS::Consumer::SetPriorityResponseT *AsConsumer_SetPriorityResponse() const {
    return type == Body::Consumer_SetPriorityResponse ?
      reinterpret_cast<const FBS::Consumer::SetPriorityResponseT *>(value) : nullptr;
  }
  FBS::DataProducer::DumpResponseT *AsDataProducer_DumpResponse() {
    return type == Body::DataProducer_DumpResponse ?
      reinterpret_cast<FBS::DataProducer::DumpResponseT *>(value) : nullptr;
  }
  const FBS::DataProducer::DumpResponseT *AsDataProducer_DumpResponse() const {
    return type == Body::DataProducer_DumpResponse ?
      reinterpret_cast<const FBS::DataProducer::DumpResponseT *>(value) : nullptr;
  }
  FBS::DataProducer::GetStatsResponseT *AsDataProducer_GetStatsResponse() {
    return type == Body::DataProducer_GetStatsResponse ?
      reinterpret_cast<FBS::DataProducer::GetStatsResponseT *>(value) : nullptr;
  }
  const FBS::DataProducer::GetStatsResponseT *AsDataProducer_GetStatsResponse() const {
    return type == Body::DataProducer_GetStatsResponse ?
      reinterpret_cast<const FBS::DataProducer::GetStatsResponseT *>(value) : nullptr;
  }
  FBS::DataConsumer::GetBufferedAmountResponseT *AsDataConsumer_GetBufferedAmountResponse() {
    return type == Body::DataConsumer_GetBufferedAmountResponse ?
      reinterpret_cast<FBS::DataConsumer::GetBufferedAmountResponseT *>(value) : nullptr;
  }
  const FBS::DataConsumer::GetBufferedAmountResponseT *AsDataConsumer_GetBufferedAmountResponse() const {
    return type == Body::DataConsumer_GetBufferedAmountResponse ?
      reinterpret_cast<const FBS::DataConsumer::GetBufferedAmountResponseT *>(value) : nullptr;
  }
  FBS::DataConsumer::DumpResponseT *AsDataConsumer_DumpResponse() {
    return type == Body::DataConsumer_DumpResponse ?
      reinterpret_cast<FBS::DataConsumer::DumpResponseT *>(value) : nullptr;
  }
  const FBS::DataConsumer::DumpResponseT *AsDataConsumer_DumpResponse() const {
    return type == Body::DataConsumer_DumpResponse ?
      reinterpret_cast<const FBS::DataConsumer::DumpResponseT *>(value) : nullptr;
  }
  FBS::DataConsumer::GetStatsResponseT *AsDataConsumer_GetStatsResponse() {
    return type == Body::DataConsumer_GetStatsResponse ?
      reinterpret_cast<FBS::DataConsumer::GetStatsResponseT *>(value) : nullptr;
  }
  const FBS::DataConsumer::GetStatsResponseT *AsDataConsumer_GetStatsResponse() const {
    return type == Body::DataConsumer_GetStatsResponse ?
      reinterpret_cast<const FBS::DataConsumer::GetStatsResponseT *>(value) : nullptr;
  }
  FBS::DataConsumer::SetSubchannelsResponseT *AsDataConsumer_SetSubchannelsResponse() {
    return type == Body::DataConsumer_SetSubchannelsResponse ?
      reinterpret_cast<FBS::DataConsumer::SetSubchannelsResponseT *>(value) : nullptr;
  }
  const FBS::DataConsumer::SetSubchannelsResponseT *AsDataConsumer_SetSubchannelsResponse() const {
    return type == Body::DataConsumer_SetSubchannelsResponse ?
      reinterpret_cast<const FBS::DataConsumer::SetSubchannelsResponseT *>(value) : nullptr;
  }
  FBS::DataConsumer::AddSubchannelResponseT *AsDataConsumer_AddSubchannelResponse() {
    return type == Body::DataConsumer_AddSubchannelResponse ?
      reinterpret_cast<FBS::DataConsumer::AddSubchannelResponseT *>(value) : nullptr;
  }
  const FBS::DataConsumer::AddSubchannelResponseT *AsDataConsumer_AddSubchannelResponse() const {
    return type == Body::DataConsumer_AddSubchannelResponse ?
      reinterpret_cast<const FBS::DataConsumer::AddSubchannelResponseT *>(value) : nullptr;
  }
  FBS::DataConsumer::RemoveSubchannelResponseT *AsDataConsumer_RemoveSubchannelResponse() {
    return type == Body::DataConsumer_RemoveSubchannelResponse ?
      reinterpret_cast<FBS::DataConsumer::RemoveSubchannelResponseT *>(value) : nullptr;
  }
  const FBS::DataConsumer::RemoveSubchannelResponseT *AsDataConsumer_RemoveSubchannelResponse() const {
    return type == Body::DataConsumer_RemoveSubchannelResponse ?
      reinterpret_cast<const FBS::DataConsumer::RemoveSubchannelResponseT *>(value) : nullptr;
  }
};

bool VerifyBody(::flatbuffers::Verifier &verifier, const void *obj, Body type);
bool VerifyBodyVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<Body> *types);

struct ResponseT : public ::flatbuffers::NativeTable {
  typedef Response TableType;
  uint32_t id = 0;
  bool accepted = false;
  FBS::Response::BodyUnion body{};
  std::string error{};
  std::string reason{};
};

struct Response FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ResponseT NativeTableType;
  typedef ResponseBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return ResponseTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_ACCEPTED = 6,
    VT_BODY_TYPE = 8,
    VT_BODY = 10,
    VT_ERROR = 12,
    VT_REASON = 14
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  bool accepted() const {
    return GetField<uint8_t>(VT_ACCEPTED, 0) != 0;
  }
  FBS::Response::Body body_type() const {
    return static_cast<FBS::Response::Body>(GetField<uint8_t>(VT_BODY_TYPE, 0));
  }
  const void *body() const {
    return GetPointer<const void *>(VT_BODY);
  }
  template<typename T> const T *body_as() const;
  const FBS::Worker::DumpResponse *body_as_Worker_DumpResponse() const {
    return body_type() == FBS::Response::Body::Worker_DumpResponse ? static_cast<const FBS::Worker::DumpResponse *>(body()) : nullptr;
  }
  const FBS::Worker::ResourceUsageResponse *body_as_Worker_ResourceUsageResponse() const {
    return body_type() == FBS::Response::Body::Worker_ResourceUsageResponse ? static_cast<const FBS::Worker::ResourceUsageResponse *>(body()) : nullptr;
  }
  const FBS::WebRtcServer::DumpResponse *body_as_WebRtcServer_DumpResponse() const {
    return body_type() == FBS::Response::Body::WebRtcServer_DumpResponse ? static_cast<const FBS::WebRtcServer::DumpResponse *>(body()) : nullptr;
  }
  const FBS::Router::DumpResponse *body_as_Router_DumpResponse() const {
    return body_type() == FBS::Response::Body::Router_DumpResponse ? static_cast<const FBS::Router::DumpResponse *>(body()) : nullptr;
  }
  const FBS::Transport::ProduceResponse *body_as_Transport_ProduceResponse() const {
    return body_type() == FBS::Response::Body::Transport_ProduceResponse ? static_cast<const FBS::Transport::ProduceResponse *>(body()) : nullptr;
  }
  const FBS::Transport::ConsumeResponse *body_as_Transport_ConsumeResponse() const {
    return body_type() == FBS::Response::Body::Transport_ConsumeResponse ? static_cast<const FBS::Transport::ConsumeResponse *>(body()) : nullptr;
  }
  const FBS::Transport::RestartIceResponse *body_as_Transport_RestartIceResponse() const {
    return body_type() == FBS::Response::Body::Transport_RestartIceResponse ? static_cast<const FBS::Transport::RestartIceResponse *>(body()) : nullptr;
  }
  const FBS::PlainTransport::ConnectResponse *body_as_PlainTransport_ConnectResponse() const {
    return body_type() == FBS::Response::Body::PlainTransport_ConnectResponse ? static_cast<const FBS::PlainTransport::ConnectResponse *>(body()) : nullptr;
  }
  const FBS::PlainTransport::DumpResponse *body_as_PlainTransport_DumpResponse() const {
    return body_type() == FBS::Response::Body::PlainTransport_DumpResponse ? static_cast<const FBS::PlainTransport::DumpResponse *>(body()) : nullptr;
  }
  const FBS::PlainTransport::GetStatsResponse *body_as_PlainTransport_GetStatsResponse() const {
    return body_type() == FBS::Response::Body::PlainTransport_GetStatsResponse ? static_cast<const FBS::PlainTransport::GetStatsResponse *>(body()) : nullptr;
  }
  const FBS::PipeTransport::ConnectResponse *body_as_PipeTransport_ConnectResponse() const {
    return body_type() == FBS::Response::Body::PipeTransport_ConnectResponse ? static_cast<const FBS::PipeTransport::ConnectResponse *>(body()) : nullptr;
  }
  const FBS::PipeTransport::DumpResponse *body_as_PipeTransport_DumpResponse() const {
    return body_type() == FBS::Response::Body::PipeTransport_DumpResponse ? static_cast<const FBS::PipeTransport::DumpResponse *>(body()) : nullptr;
  }
  const FBS::PipeTransport::GetStatsResponse *body_as_PipeTransport_GetStatsResponse() const {
    return body_type() == FBS::Response::Body::PipeTransport_GetStatsResponse ? static_cast<const FBS::PipeTransport::GetStatsResponse *>(body()) : nullptr;
  }
  const FBS::DirectTransport::DumpResponse *body_as_DirectTransport_DumpResponse() const {
    return body_type() == FBS::Response::Body::DirectTransport_DumpResponse ? static_cast<const FBS::DirectTransport::DumpResponse *>(body()) : nullptr;
  }
  const FBS::DirectTransport::GetStatsResponse *body_as_DirectTransport_GetStatsResponse() const {
    return body_type() == FBS::Response::Body::DirectTransport_GetStatsResponse ? static_cast<const FBS::DirectTransport::GetStatsResponse *>(body()) : nullptr;
  }
  const FBS::WebRtcTransport::ConnectResponse *body_as_WebRtcTransport_ConnectResponse() const {
    return body_type() == FBS::Response::Body::WebRtcTransport_ConnectResponse ? static_cast<const FBS::WebRtcTransport::ConnectResponse *>(body()) : nullptr;
  }
  const FBS::WebRtcTransport::DumpResponse *body_as_WebRtcTransport_DumpResponse() const {
    return body_type() == FBS::Response::Body::WebRtcTransport_DumpResponse ? static_cast<const FBS::WebRtcTransport::DumpResponse *>(body()) : nullptr;
  }
  const FBS::WebRtcTransport::GetStatsResponse *body_as_WebRtcTransport_GetStatsResponse() const {
    return body_type() == FBS::Response::Body::WebRtcTransport_GetStatsResponse ? static_cast<const FBS::WebRtcTransport::GetStatsResponse *>(body()) : nullptr;
  }
  const FBS::Producer::DumpResponse *body_as_Producer_DumpResponse() const {
    return body_type() == FBS::Response::Body::Producer_DumpResponse ? static_cast<const FBS::Producer::DumpResponse *>(body()) : nullptr;
  }
  const FBS::Producer::GetStatsResponse *body_as_Producer_GetStatsResponse() const {
    return body_type() == FBS::Response::Body::Producer_GetStatsResponse ? static_cast<const FBS::Producer::GetStatsResponse *>(body()) : nullptr;
  }
  const FBS::Consumer::DumpResponse *body_as_Consumer_DumpResponse() const {
    return body_type() == FBS::Response::Body::Consumer_DumpResponse ? static_cast<const FBS::Consumer::DumpResponse *>(body()) : nullptr;
  }
  const FBS::Consumer::GetStatsResponse *body_as_Consumer_GetStatsResponse() const {
    return body_type() == FBS::Response::Body::Consumer_GetStatsResponse ? static_cast<const FBS::Consumer::GetStatsResponse *>(body()) : nullptr;
  }
  const FBS::Consumer::SetPreferredLayersResponse *body_as_Consumer_SetPreferredLayersResponse() const {
    return body_type() == FBS::Response::Body::Consumer_SetPreferredLayersResponse ? static_cast<const FBS::Consumer::SetPreferredLayersResponse *>(body()) : nullptr;
  }
  const FBS::Consumer::SetPriorityResponse *body_as_Consumer_SetPriorityResponse() const {
    return body_type() == FBS::Response::Body::Consumer_SetPriorityResponse ? static_cast<const FBS::Consumer::SetPriorityResponse *>(body()) : nullptr;
  }
  const FBS::DataProducer::DumpResponse *body_as_DataProducer_DumpResponse() const {
    return body_type() == FBS::Response::Body::DataProducer_DumpResponse ? static_cast<const FBS::DataProducer::DumpResponse *>(body()) : nullptr;
  }
  const FBS::DataProducer::GetStatsResponse *body_as_DataProducer_GetStatsResponse() const {
    return body_type() == FBS::Response::Body::DataProducer_GetStatsResponse ? static_cast<const FBS::DataProducer::GetStatsResponse *>(body()) : nullptr;
  }
  const FBS::DataConsumer::GetBufferedAmountResponse *body_as_DataConsumer_GetBufferedAmountResponse() const {
    return body_type() == FBS::Response::Body::DataConsumer_GetBufferedAmountResponse ? static_cast<const FBS::DataConsumer::GetBufferedAmountResponse *>(body()) : nullptr;
  }
  const FBS::DataConsumer::DumpResponse *body_as_DataConsumer_DumpResponse() const {
    return body_type() == FBS::Response::Body::DataConsumer_DumpResponse ? static_cast<const FBS::DataConsumer::DumpResponse *>(body()) : nullptr;
  }
  const FBS::DataConsumer::GetStatsResponse *body_as_DataConsumer_GetStatsResponse() const {
    return body_type() == FBS::Response::Body::DataConsumer_GetStatsResponse ? static_cast<const FBS::DataConsumer::GetStatsResponse *>(body()) : nullptr;
  }
  const FBS::DataConsumer::SetSubchannelsResponse *body_as_DataConsumer_SetSubchannelsResponse() const {
    return body_type() == FBS::Response::Body::DataConsumer_SetSubchannelsResponse ? static_cast<const FBS::DataConsumer::SetSubchannelsResponse *>(body()) : nullptr;
  }
  const FBS::DataConsumer::AddSubchannelResponse *body_as_DataConsumer_AddSubchannelResponse() const {
    return body_type() == FBS::Response::Body::DataConsumer_AddSubchannelResponse ? static_cast<const FBS::DataConsumer::AddSubchannelResponse *>(body()) : nullptr;
  }
  const FBS::DataConsumer::RemoveSubchannelResponse *body_as_DataConsumer_RemoveSubchannelResponse() const {
    return body_type() == FBS::Response::Body::DataConsumer_RemoveSubchannelResponse ? static_cast<const FBS::DataConsumer::RemoveSubchannelResponse *>(body()) : nullptr;
  }
  const ::flatbuffers::String *error() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ERROR);
  }
  const ::flatbuffers::String *reason() const {
    return GetPointer<const ::flatbuffers::String *>(VT_REASON);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           VerifyField<uint8_t>(verifier, VT_ACCEPTED, 1) &&
           VerifyField<uint8_t>(verifier, VT_BODY_TYPE, 1) &&
           VerifyOffset(verifier, VT_BODY) &&
           VerifyBody(verifier, body(), body_type()) &&
           VerifyOffset(verifier, VT_ERROR) &&
           verifier.VerifyString(error()) &&
           VerifyOffset(verifier, VT_REASON) &&
           verifier.VerifyString(reason()) &&
           verifier.EndTable();
  }
  ResponseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Response> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

template<> inline const FBS::Worker::DumpResponse *Response::body_as<FBS::Worker::DumpResponse>() const {
  return body_as_Worker_DumpResponse();
}

template<> inline const FBS::Worker::ResourceUsageResponse *Response::body_as<FBS::Worker::ResourceUsageResponse>() const {
  return body_as_Worker_ResourceUsageResponse();
}

template<> inline const FBS::WebRtcServer::DumpResponse *Response::body_as<FBS::WebRtcServer::DumpResponse>() const {
  return body_as_WebRtcServer_DumpResponse();
}

template<> inline const FBS::Router::DumpResponse *Response::body_as<FBS::Router::DumpResponse>() const {
  return body_as_Router_DumpResponse();
}

template<> inline const FBS::Transport::ProduceResponse *Response::body_as<FBS::Transport::ProduceResponse>() const {
  return body_as_Transport_ProduceResponse();
}

template<> inline const FBS::Transport::ConsumeResponse *Response::body_as<FBS::Transport::ConsumeResponse>() const {
  return body_as_Transport_ConsumeResponse();
}

template<> inline const FBS::Transport::RestartIceResponse *Response::body_as<FBS::Transport::RestartIceResponse>() const {
  return body_as_Transport_RestartIceResponse();
}

template<> inline const FBS::PlainTransport::ConnectResponse *Response::body_as<FBS::PlainTransport::ConnectResponse>() const {
  return body_as_PlainTransport_ConnectResponse();
}

template<> inline const FBS::PlainTransport::DumpResponse *Response::body_as<FBS::PlainTransport::DumpResponse>() const {
  return body_as_PlainTransport_DumpResponse();
}

template<> inline const FBS::PlainTransport::GetStatsResponse *Response::body_as<FBS::PlainTransport::GetStatsResponse>() const {
  return body_as_PlainTransport_GetStatsResponse();
}

template<> inline const FBS::PipeTransport::ConnectResponse *Response::body_as<FBS::PipeTransport::ConnectResponse>() const {
  return body_as_PipeTransport_ConnectResponse();
}

template<> inline const FBS::PipeTransport::DumpResponse *Response::body_as<FBS::PipeTransport::DumpResponse>() const {
  return body_as_PipeTransport_DumpResponse();
}

template<> inline const FBS::PipeTransport::GetStatsResponse *Response::body_as<FBS::PipeTransport::GetStatsResponse>() const {
  return body_as_PipeTransport_GetStatsResponse();
}

template<> inline const FBS::DirectTransport::DumpResponse *Response::body_as<FBS::DirectTransport::DumpResponse>() const {
  return body_as_DirectTransport_DumpResponse();
}

template<> inline const FBS::DirectTransport::GetStatsResponse *Response::body_as<FBS::DirectTransport::GetStatsResponse>() const {
  return body_as_DirectTransport_GetStatsResponse();
}

template<> inline const FBS::WebRtcTransport::ConnectResponse *Response::body_as<FBS::WebRtcTransport::ConnectResponse>() const {
  return body_as_WebRtcTransport_ConnectResponse();
}

template<> inline const FBS::WebRtcTransport::DumpResponse *Response::body_as<FBS::WebRtcTransport::DumpResponse>() const {
  return body_as_WebRtcTransport_DumpResponse();
}

template<> inline const FBS::WebRtcTransport::GetStatsResponse *Response::body_as<FBS::WebRtcTransport::GetStatsResponse>() const {
  return body_as_WebRtcTransport_GetStatsResponse();
}

template<> inline const FBS::Producer::DumpResponse *Response::body_as<FBS::Producer::DumpResponse>() const {
  return body_as_Producer_DumpResponse();
}

template<> inline const FBS::Producer::GetStatsResponse *Response::body_as<FBS::Producer::GetStatsResponse>() const {
  return body_as_Producer_GetStatsResponse();
}

template<> inline const FBS::Consumer::DumpResponse *Response::body_as<FBS::Consumer::DumpResponse>() const {
  return body_as_Consumer_DumpResponse();
}

template<> inline const FBS::Consumer::GetStatsResponse *Response::body_as<FBS::Consumer::GetStatsResponse>() const {
  return body_as_Consumer_GetStatsResponse();
}

template<> inline const FBS::Consumer::SetPreferredLayersResponse *Response::body_as<FBS::Consumer::SetPreferredLayersResponse>() const {
  return body_as_Consumer_SetPreferredLayersResponse();
}

template<> inline const FBS::Consumer::SetPriorityResponse *Response::body_as<FBS::Consumer::SetPriorityResponse>() const {
  return body_as_Consumer_SetPriorityResponse();
}

template<> inline const FBS::DataProducer::DumpResponse *Response::body_as<FBS::DataProducer::DumpResponse>() const {
  return body_as_DataProducer_DumpResponse();
}

template<> inline const FBS::DataProducer::GetStatsResponse *Response::body_as<FBS::DataProducer::GetStatsResponse>() const {
  return body_as_DataProducer_GetStatsResponse();
}

template<> inline const FBS::DataConsumer::GetBufferedAmountResponse *Response::body_as<FBS::DataConsumer::GetBufferedAmountResponse>() const {
  return body_as_DataConsumer_GetBufferedAmountResponse();
}

template<> inline const FBS::DataConsumer::DumpResponse *Response::body_as<FBS::DataConsumer::DumpResponse>() const {
  return body_as_DataConsumer_DumpResponse();
}

template<> inline const FBS::DataConsumer::GetStatsResponse *Response::body_as<FBS::DataConsumer::GetStatsResponse>() const {
  return body_as_DataConsumer_GetStatsResponse();
}

template<> inline const FBS::DataConsumer::SetSubchannelsResponse *Response::body_as<FBS::DataConsumer::SetSubchannelsResponse>() const {
  return body_as_DataConsumer_SetSubchannelsResponse();
}

template<> inline const FBS::DataConsumer::AddSubchannelResponse *Response::body_as<FBS::DataConsumer::AddSubchannelResponse>() const {
  return body_as_DataConsumer_AddSubchannelResponse();
}

template<> inline const FBS::DataConsumer::RemoveSubchannelResponse *Response::body_as<FBS::DataConsumer::RemoveSubchannelResponse>() const {
  return body_as_DataConsumer_RemoveSubchannelResponse();
}

struct ResponseBuilder {
  typedef Response Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(Response::VT_ID, id, 0);
  }
  void add_accepted(bool accepted) {
    fbb_.AddElement<uint8_t>(Response::VT_ACCEPTED, static_cast<uint8_t>(accepted), 0);
  }
  void add_body_type(FBS::Response::Body body_type) {
    fbb_.AddElement<uint8_t>(Response::VT_BODY_TYPE, static_cast<uint8_t>(body_type), 0);
  }
  void add_body(::flatbuffers::Offset<void> body) {
    fbb_.AddOffset(Response::VT_BODY, body);
  }
  void add_error(::flatbuffers::Offset<::flatbuffers::String> error) {
    fbb_.AddOffset(Response::VT_ERROR, error);
  }
  void add_reason(::flatbuffers::Offset<::flatbuffers::String> reason) {
    fbb_.AddOffset(Response::VT_REASON, reason);
  }
  explicit ResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Response> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Response>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Response> CreateResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    bool accepted = false,
    FBS::Response::Body body_type = FBS::Response::Body::NONE,
    ::flatbuffers::Offset<void> body = 0,
    ::flatbuffers::Offset<::flatbuffers::String> error = 0,
    ::flatbuffers::Offset<::flatbuffers::String> reason = 0) {
  ResponseBuilder builder_(_fbb);
  builder_.add_reason(reason);
  builder_.add_error(error);
  builder_.add_body(body);
  builder_.add_id(id);
  builder_.add_body_type(body_type);
  builder_.add_accepted(accepted);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Response> CreateResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    bool accepted = false,
    FBS::Response::Body body_type = FBS::Response::Body::NONE,
    ::flatbuffers::Offset<void> body = 0,
    const char *error = nullptr,
    const char *reason = nullptr) {
  auto error__ = error ? _fbb.CreateString(error) : 0;
  auto reason__ = reason ? _fbb.CreateString(reason) : 0;
  return FBS::Response::CreateResponse(
      _fbb,
      id,
      accepted,
      body_type,
      body,
      error__,
      reason__);
}

::flatbuffers::Offset<Response> CreateResponse(::flatbuffers::FlatBufferBuilder &_fbb, const ResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline ResponseT *Response::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ResponseT>(new ResponseT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Response::UnPackTo(ResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = id(); _o->id = _e; }
  { auto _e = accepted(); _o->accepted = _e; }
  { auto _e = body_type(); _o->body.type = _e; }
  { auto _e = body(); if (_e) _o->body.value = FBS::Response::BodyUnion::UnPack(_e, body_type(), _resolver); }
  { auto _e = error(); if (_e) _o->error = _e->str(); }
  { auto _e = reason(); if (_e) _o->reason = _e->str(); }
}

inline ::flatbuffers::Offset<Response> Response::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateResponse(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Response> CreateResponse(::flatbuffers::FlatBufferBuilder &_fbb, const ResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ResponseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _id = _o->id;
  auto _accepted = _o->accepted;
  auto _body_type = _o->body.type;
  auto _body = _o->body.Pack(_fbb);
  auto _error = _o->error.empty() ? 0 : _fbb.CreateString(_o->error);
  auto _reason = _o->reason.empty() ? 0 : _fbb.CreateString(_o->reason);
  return FBS::Response::CreateResponse(
      _fbb,
      _id,
      _accepted,
      _body_type,
      _body,
      _error,
      _reason);
}

inline bool VerifyBody(::flatbuffers::Verifier &verifier, const void *obj, Body type) {
  switch (type) {
    case Body::NONE: {
      return true;
    }
    case Body::Worker_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::Worker::DumpResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::Worker_ResourceUsageResponse: {
      auto ptr = reinterpret_cast<const FBS::Worker::ResourceUsageResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::WebRtcServer_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::WebRtcServer::DumpResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::Router_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::Router::DumpResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::Transport_ProduceResponse: {
      auto ptr = reinterpret_cast<const FBS::Transport::ProduceResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::Transport_ConsumeResponse: {
      auto ptr = reinterpret_cast<const FBS::Transport::ConsumeResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::Transport_RestartIceResponse: {
      auto ptr = reinterpret_cast<const FBS::Transport::RestartIceResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::PlainTransport_ConnectResponse: {
      auto ptr = reinterpret_cast<const FBS::PlainTransport::ConnectResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::PlainTransport_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::PlainTransport::DumpResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::PlainTransport_GetStatsResponse: {
      auto ptr = reinterpret_cast<const FBS::PlainTransport::GetStatsResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::PipeTransport_ConnectResponse: {
      auto ptr = reinterpret_cast<const FBS::PipeTransport::ConnectResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::PipeTransport_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::PipeTransport::DumpResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::PipeTransport_GetStatsResponse: {
      auto ptr = reinterpret_cast<const FBS::PipeTransport::GetStatsResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::DirectTransport_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::DirectTransport::DumpResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::DirectTransport_GetStatsResponse: {
      auto ptr = reinterpret_cast<const FBS::DirectTransport::GetStatsResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::WebRtcTransport_ConnectResponse: {
      auto ptr = reinterpret_cast<const FBS::WebRtcTransport::ConnectResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::WebRtcTransport_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::WebRtcTransport::DumpResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::WebRtcTransport_GetStatsResponse: {
      auto ptr = reinterpret_cast<const FBS::WebRtcTransport::GetStatsResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::Producer_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::Producer::DumpResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::Producer_GetStatsResponse: {
      auto ptr = reinterpret_cast<const FBS::Producer::GetStatsResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::Consumer_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::Consumer::DumpResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::Consumer_GetStatsResponse: {
      auto ptr = reinterpret_cast<const FBS::Consumer::GetStatsResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::Consumer_SetPreferredLayersResponse: {
      auto ptr = reinterpret_cast<const FBS::Consumer::SetPreferredLayersResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::Consumer_SetPriorityResponse: {
      auto ptr = reinterpret_cast<const FBS::Consumer::SetPriorityResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::DataProducer_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::DataProducer::DumpResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::DataProducer_GetStatsResponse: {
      auto ptr = reinterpret_cast<const FBS::DataProducer::GetStatsResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::DataConsumer_GetBufferedAmountResponse: {
      auto ptr = reinterpret_cast<const FBS::DataConsumer::GetBufferedAmountResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::DataConsumer_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::DataConsumer::DumpResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::DataConsumer_GetStatsResponse: {
      auto ptr = reinterpret_cast<const FBS::DataConsumer::GetStatsResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::DataConsumer_SetSubchannelsResponse: {
      auto ptr = reinterpret_cast<const FBS::DataConsumer::SetSubchannelsResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::DataConsumer_AddSubchannelResponse: {
      auto ptr = reinterpret_cast<const FBS::DataConsumer::AddSubchannelResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Body::DataConsumer_RemoveSubchannelResponse: {
      auto ptr = reinterpret_cast<const FBS::DataConsumer::RemoveSubchannelResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyBodyVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<Body> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyBody(
        verifier,  values->Get(i), types->GetEnum<Body>(i))) {
      return false;
    }
  }
  return true;
}

inline void *BodyUnion::UnPack(const void *obj, Body type, const ::flatbuffers::resolver_function_t *resolver) {
  (void)resolver;
  switch (type) {
    case Body::Worker_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::Worker::DumpResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::Worker_ResourceUsageResponse: {
      auto ptr = reinterpret_cast<const FBS::Worker::ResourceUsageResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::WebRtcServer_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::WebRtcServer::DumpResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::Router_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::Router::DumpResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::Transport_ProduceResponse: {
      auto ptr = reinterpret_cast<const FBS::Transport::ProduceResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::Transport_ConsumeResponse: {
      auto ptr = reinterpret_cast<const FBS::Transport::ConsumeResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::Transport_RestartIceResponse: {
      auto ptr = reinterpret_cast<const FBS::Transport::RestartIceResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::PlainTransport_ConnectResponse: {
      auto ptr = reinterpret_cast<const FBS::PlainTransport::ConnectResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::PlainTransport_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::PlainTransport::DumpResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::PlainTransport_GetStatsResponse: {
      auto ptr = reinterpret_cast<const FBS::PlainTransport::GetStatsResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::PipeTransport_ConnectResponse: {
      auto ptr = reinterpret_cast<const FBS::PipeTransport::ConnectResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::PipeTransport_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::PipeTransport::DumpResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::PipeTransport_GetStatsResponse: {
      auto ptr = reinterpret_cast<const FBS::PipeTransport::GetStatsResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::DirectTransport_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::DirectTransport::DumpResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::DirectTransport_GetStatsResponse: {
      auto ptr = reinterpret_cast<const FBS::DirectTransport::GetStatsResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::WebRtcTransport_ConnectResponse: {
      auto ptr = reinterpret_cast<const FBS::WebRtcTransport::ConnectResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::WebRtcTransport_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::WebRtcTransport::DumpResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::WebRtcTransport_GetStatsResponse: {
      auto ptr = reinterpret_cast<const FBS::WebRtcTransport::GetStatsResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::Producer_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::Producer::DumpResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::Producer_GetStatsResponse: {
      auto ptr = reinterpret_cast<const FBS::Producer::GetStatsResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::Consumer_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::Consumer::DumpResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::Consumer_GetStatsResponse: {
      auto ptr = reinterpret_cast<const FBS::Consumer::GetStatsResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::Consumer_SetPreferredLayersResponse: {
      auto ptr = reinterpret_cast<const FBS::Consumer::SetPreferredLayersResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::Consumer_SetPriorityResponse: {
      auto ptr = reinterpret_cast<const FBS::Consumer::SetPriorityResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::DataProducer_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::DataProducer::DumpResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::DataProducer_GetStatsResponse: {
      auto ptr = reinterpret_cast<const FBS::DataProducer::GetStatsResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::DataConsumer_GetBufferedAmountResponse: {
      auto ptr = reinterpret_cast<const FBS::DataConsumer::GetBufferedAmountResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::DataConsumer_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::DataConsumer::DumpResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::DataConsumer_GetStatsResponse: {
      auto ptr = reinterpret_cast<const FBS::DataConsumer::GetStatsResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::DataConsumer_SetSubchannelsResponse: {
      auto ptr = reinterpret_cast<const FBS::DataConsumer::SetSubchannelsResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::DataConsumer_AddSubchannelResponse: {
      auto ptr = reinterpret_cast<const FBS::DataConsumer::AddSubchannelResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Body::DataConsumer_RemoveSubchannelResponse: {
      auto ptr = reinterpret_cast<const FBS::DataConsumer::RemoveSubchannelResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    default: return nullptr;
  }
}

inline ::flatbuffers::Offset<void> BodyUnion::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher) const {
  (void)_rehasher;
  switch (type) {
    case Body::Worker_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::Worker::DumpResponseT *>(value);
      return CreateDumpResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::Worker_ResourceUsageResponse: {
      auto ptr = reinterpret_cast<const FBS::Worker::ResourceUsageResponseT *>(value);
      return CreateResourceUsageResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::WebRtcServer_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::WebRtcServer::DumpResponseT *>(value);
      return CreateDumpResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::Router_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::Router::DumpResponseT *>(value);
      return CreateDumpResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::Transport_ProduceResponse: {
      auto ptr = reinterpret_cast<const FBS::Transport::ProduceResponseT *>(value);
      return CreateProduceResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::Transport_ConsumeResponse: {
      auto ptr = reinterpret_cast<const FBS::Transport::ConsumeResponseT *>(value);
      return CreateConsumeResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::Transport_RestartIceResponse: {
      auto ptr = reinterpret_cast<const FBS::Transport::RestartIceResponseT *>(value);
      return CreateRestartIceResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::PlainTransport_ConnectResponse: {
      auto ptr = reinterpret_cast<const FBS::PlainTransport::ConnectResponseT *>(value);
      return CreateConnectResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::PlainTransport_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::PlainTransport::DumpResponseT *>(value);
      return CreateDumpResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::PlainTransport_GetStatsResponse: {
      auto ptr = reinterpret_cast<const FBS::PlainTransport::GetStatsResponseT *>(value);
      return CreateGetStatsResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::PipeTransport_ConnectResponse: {
      auto ptr = reinterpret_cast<const FBS::PipeTransport::ConnectResponseT *>(value);
      return CreateConnectResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::PipeTransport_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::PipeTransport::DumpResponseT *>(value);
      return CreateDumpResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::PipeTransport_GetStatsResponse: {
      auto ptr = reinterpret_cast<const FBS::PipeTransport::GetStatsResponseT *>(value);
      return CreateGetStatsResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::DirectTransport_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::DirectTransport::DumpResponseT *>(value);
      return CreateDumpResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::DirectTransport_GetStatsResponse: {
      auto ptr = reinterpret_cast<const FBS::DirectTransport::GetStatsResponseT *>(value);
      return CreateGetStatsResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::WebRtcTransport_ConnectResponse: {
      auto ptr = reinterpret_cast<const FBS::WebRtcTransport::ConnectResponseT *>(value);
      return CreateConnectResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::WebRtcTransport_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::WebRtcTransport::DumpResponseT *>(value);
      return CreateDumpResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::WebRtcTransport_GetStatsResponse: {
      auto ptr = reinterpret_cast<const FBS::WebRtcTransport::GetStatsResponseT *>(value);
      return CreateGetStatsResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::Producer_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::Producer::DumpResponseT *>(value);
      return CreateDumpResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::Producer_GetStatsResponse: {
      auto ptr = reinterpret_cast<const FBS::Producer::GetStatsResponseT *>(value);
      return CreateGetStatsResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::Consumer_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::Consumer::DumpResponseT *>(value);
      return CreateDumpResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::Consumer_GetStatsResponse: {
      auto ptr = reinterpret_cast<const FBS::Consumer::GetStatsResponseT *>(value);
      return CreateGetStatsResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::Consumer_SetPreferredLayersResponse: {
      auto ptr = reinterpret_cast<const FBS::Consumer::SetPreferredLayersResponseT *>(value);
      return CreateSetPreferredLayersResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::Consumer_SetPriorityResponse: {
      auto ptr = reinterpret_cast<const FBS::Consumer::SetPriorityResponseT *>(value);
      return CreateSetPriorityResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::DataProducer_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::DataProducer::DumpResponseT *>(value);
      return CreateDumpResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::DataProducer_GetStatsResponse: {
      auto ptr = reinterpret_cast<const FBS::DataProducer::GetStatsResponseT *>(value);
      return CreateGetStatsResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::DataConsumer_GetBufferedAmountResponse: {
      auto ptr = reinterpret_cast<const FBS::DataConsumer::GetBufferedAmountResponseT *>(value);
      return CreateGetBufferedAmountResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::DataConsumer_DumpResponse: {
      auto ptr = reinterpret_cast<const FBS::DataConsumer::DumpResponseT *>(value);
      return CreateDumpResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::DataConsumer_GetStatsResponse: {
      auto ptr = reinterpret_cast<const FBS::DataConsumer::GetStatsResponseT *>(value);
      return CreateGetStatsResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::DataConsumer_SetSubchannelsResponse: {
      auto ptr = reinterpret_cast<const FBS::DataConsumer::SetSubchannelsResponseT *>(value);
      return CreateSetSubchannelsResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::DataConsumer_AddSubchannelResponse: {
      auto ptr = reinterpret_cast<const FBS::DataConsumer::AddSubchannelResponseT *>(value);
      return CreateAddSubchannelResponse(_fbb, ptr, _rehasher).Union();
    }
    case Body::DataConsumer_RemoveSubchannelResponse: {
      auto ptr = reinterpret_cast<const FBS::DataConsumer::RemoveSubchannelResponseT *>(value);
      return CreateRemoveSubchannelResponse(_fbb, ptr, _rehasher).Union();
    }
    default: return 0;
  }
}

inline BodyUnion::BodyUnion(const BodyUnion &u) : type(u.type), value(nullptr) {
  switch (type) {
    case Body::Worker_DumpResponse: {
      value = new FBS::Worker::DumpResponseT(*reinterpret_cast<FBS::Worker::DumpResponseT *>(u.value));
      break;
    }
    case Body::Worker_ResourceUsageResponse: {
      value = new FBS::Worker::ResourceUsageResponseT(*reinterpret_cast<FBS::Worker::ResourceUsageResponseT *>(u.value));
      break;
    }
    case Body::WebRtcServer_DumpResponse: {
      value = new FBS::WebRtcServer::DumpResponseT(*reinterpret_cast<FBS::WebRtcServer::DumpResponseT *>(u.value));
      break;
    }
    case Body::Router_DumpResponse: {
      value = new FBS::Router::DumpResponseT(*reinterpret_cast<FBS::Router::DumpResponseT *>(u.value));
      break;
    }
    case Body::Transport_ProduceResponse: {
      value = new FBS::Transport::ProduceResponseT(*reinterpret_cast<FBS::Transport::ProduceResponseT *>(u.value));
      break;
    }
    case Body::Transport_ConsumeResponse: {
      value = new FBS::Transport::ConsumeResponseT(*reinterpret_cast<FBS::Transport::ConsumeResponseT *>(u.value));
      break;
    }
    case Body::Transport_RestartIceResponse: {
      value = new FBS::Transport::RestartIceResponseT(*reinterpret_cast<FBS::Transport::RestartIceResponseT *>(u.value));
      break;
    }
    case Body::PlainTransport_ConnectResponse: {
      value = new FBS::PlainTransport::ConnectResponseT(*reinterpret_cast<FBS::PlainTransport::ConnectResponseT *>(u.value));
      break;
    }
    case Body::PlainTransport_DumpResponse: {
      value = new FBS::PlainTransport::DumpResponseT(*reinterpret_cast<FBS::PlainTransport::DumpResponseT *>(u.value));
      break;
    }
    case Body::PlainTransport_GetStatsResponse: {
      value = new FBS::PlainTransport::GetStatsResponseT(*reinterpret_cast<FBS::PlainTransport::GetStatsResponseT *>(u.value));
      break;
    }
    case Body::PipeTransport_ConnectResponse: {
      value = new FBS::PipeTransport::ConnectResponseT(*reinterpret_cast<FBS::PipeTransport::ConnectResponseT *>(u.value));
      break;
    }
    case Body::PipeTransport_DumpResponse: {
      value = new FBS::PipeTransport::DumpResponseT(*reinterpret_cast<FBS::PipeTransport::DumpResponseT *>(u.value));
      break;
    }
    case Body::PipeTransport_GetStatsResponse: {
      value = new FBS::PipeTransport::GetStatsResponseT(*reinterpret_cast<FBS::PipeTransport::GetStatsResponseT *>(u.value));
      break;
    }
    case Body::DirectTransport_DumpResponse: {
      value = new FBS::DirectTransport::DumpResponseT(*reinterpret_cast<FBS::DirectTransport::DumpResponseT *>(u.value));
      break;
    }
    case Body::DirectTransport_GetStatsResponse: {
      value = new FBS::DirectTransport::GetStatsResponseT(*reinterpret_cast<FBS::DirectTransport::GetStatsResponseT *>(u.value));
      break;
    }
    case Body::WebRtcTransport_ConnectResponse: {
      value = new FBS::WebRtcTransport::ConnectResponseT(*reinterpret_cast<FBS::WebRtcTransport::ConnectResponseT *>(u.value));
      break;
    }
    case Body::WebRtcTransport_DumpResponse: {
      value = new FBS::WebRtcTransport::DumpResponseT(*reinterpret_cast<FBS::WebRtcTransport::DumpResponseT *>(u.value));
      break;
    }
    case Body::WebRtcTransport_GetStatsResponse: {
      value = new FBS::WebRtcTransport::GetStatsResponseT(*reinterpret_cast<FBS::WebRtcTransport::GetStatsResponseT *>(u.value));
      break;
    }
    case Body::Producer_DumpResponse: {
      value = new FBS::Producer::DumpResponseT(*reinterpret_cast<FBS::Producer::DumpResponseT *>(u.value));
      break;
    }
    case Body::Producer_GetStatsResponse: {
      value = new FBS::Producer::GetStatsResponseT(*reinterpret_cast<FBS::Producer::GetStatsResponseT *>(u.value));
      break;
    }
    case Body::Consumer_DumpResponse: {
      value = new FBS::Consumer::DumpResponseT(*reinterpret_cast<FBS::Consumer::DumpResponseT *>(u.value));
      break;
    }
    case Body::Consumer_GetStatsResponse: {
      value = new FBS::Consumer::GetStatsResponseT(*reinterpret_cast<FBS::Consumer::GetStatsResponseT *>(u.value));
      break;
    }
    case Body::Consumer_SetPreferredLayersResponse: {
      value = new FBS::Consumer::SetPreferredLayersResponseT(*reinterpret_cast<FBS::Consumer::SetPreferredLayersResponseT *>(u.value));
      break;
    }
    case Body::Consumer_SetPriorityResponse: {
      value = new FBS::Consumer::SetPriorityResponseT(*reinterpret_cast<FBS::Consumer::SetPriorityResponseT *>(u.value));
      break;
    }
    case Body::DataProducer_DumpResponse: {
      value = new FBS::DataProducer::DumpResponseT(*reinterpret_cast<FBS::DataProducer::DumpResponseT *>(u.value));
      break;
    }
    case Body::DataProducer_GetStatsResponse: {
      value = new FBS::DataProducer::GetStatsResponseT(*reinterpret_cast<FBS::DataProducer::GetStatsResponseT *>(u.value));
      break;
    }
    case Body::DataConsumer_GetBufferedAmountResponse: {
      value = new FBS::DataConsumer::GetBufferedAmountResponseT(*reinterpret_cast<FBS::DataConsumer::GetBufferedAmountResponseT *>(u.value));
      break;
    }
    case Body::DataConsumer_DumpResponse: {
      value = new FBS::DataConsumer::DumpResponseT(*reinterpret_cast<FBS::DataConsumer::DumpResponseT *>(u.value));
      break;
    }
    case Body::DataConsumer_GetStatsResponse: {
      value = new FBS::DataConsumer::GetStatsResponseT(*reinterpret_cast<FBS::DataConsumer::GetStatsResponseT *>(u.value));
      break;
    }
    case Body::DataConsumer_SetSubchannelsResponse: {
      value = new FBS::DataConsumer::SetSubchannelsResponseT(*reinterpret_cast<FBS::DataConsumer::SetSubchannelsResponseT *>(u.value));
      break;
    }
    case Body::DataConsumer_AddSubchannelResponse: {
      value = new FBS::DataConsumer::AddSubchannelResponseT(*reinterpret_cast<FBS::DataConsumer::AddSubchannelResponseT *>(u.value));
      break;
    }
    case Body::DataConsumer_RemoveSubchannelResponse: {
      value = new FBS::DataConsumer::RemoveSubchannelResponseT(*reinterpret_cast<FBS::DataConsumer::RemoveSubchannelResponseT *>(u.value));
      break;
    }
    default:
      break;
  }
}

inline void BodyUnion::Reset() {
  switch (type) {
    case Body::Worker_DumpResponse: {
      auto ptr = reinterpret_cast<FBS::Worker::DumpResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::Worker_ResourceUsageResponse: {
      auto ptr = reinterpret_cast<FBS::Worker::ResourceUsageResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::WebRtcServer_DumpResponse: {
      auto ptr = reinterpret_cast<FBS::WebRtcServer::DumpResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::Router_DumpResponse: {
      auto ptr = reinterpret_cast<FBS::Router::DumpResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::Transport_ProduceResponse: {
      auto ptr = reinterpret_cast<FBS::Transport::ProduceResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::Transport_ConsumeResponse: {
      auto ptr = reinterpret_cast<FBS::Transport::ConsumeResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::Transport_RestartIceResponse: {
      auto ptr = reinterpret_cast<FBS::Transport::RestartIceResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::PlainTransport_ConnectResponse: {
      auto ptr = reinterpret_cast<FBS::PlainTransport::ConnectResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::PlainTransport_DumpResponse: {
      auto ptr = reinterpret_cast<FBS::PlainTransport::DumpResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::PlainTransport_GetStatsResponse: {
      auto ptr = reinterpret_cast<FBS::PlainTransport::GetStatsResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::PipeTransport_ConnectResponse: {
      auto ptr = reinterpret_cast<FBS::PipeTransport::ConnectResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::PipeTransport_DumpResponse: {
      auto ptr = reinterpret_cast<FBS::PipeTransport::DumpResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::PipeTransport_GetStatsResponse: {
      auto ptr = reinterpret_cast<FBS::PipeTransport::GetStatsResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::DirectTransport_DumpResponse: {
      auto ptr = reinterpret_cast<FBS::DirectTransport::DumpResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::DirectTransport_GetStatsResponse: {
      auto ptr = reinterpret_cast<FBS::DirectTransport::GetStatsResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::WebRtcTransport_ConnectResponse: {
      auto ptr = reinterpret_cast<FBS::WebRtcTransport::ConnectResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::WebRtcTransport_DumpResponse: {
      auto ptr = reinterpret_cast<FBS::WebRtcTransport::DumpResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::WebRtcTransport_GetStatsResponse: {
      auto ptr = reinterpret_cast<FBS::WebRtcTransport::GetStatsResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::Producer_DumpResponse: {
      auto ptr = reinterpret_cast<FBS::Producer::DumpResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::Producer_GetStatsResponse: {
      auto ptr = reinterpret_cast<FBS::Producer::GetStatsResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::Consumer_DumpResponse: {
      auto ptr = reinterpret_cast<FBS::Consumer::DumpResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::Consumer_GetStatsResponse: {
      auto ptr = reinterpret_cast<FBS::Consumer::GetStatsResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::Consumer_SetPreferredLayersResponse: {
      auto ptr = reinterpret_cast<FBS::Consumer::SetPreferredLayersResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::Consumer_SetPriorityResponse: {
      auto ptr = reinterpret_cast<FBS::Consumer::SetPriorityResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::DataProducer_DumpResponse: {
      auto ptr = reinterpret_cast<FBS::DataProducer::DumpResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::DataProducer_GetStatsResponse: {
      auto ptr = reinterpret_cast<FBS::DataProducer::GetStatsResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::DataConsumer_GetBufferedAmountResponse: {
      auto ptr = reinterpret_cast<FBS::DataConsumer::GetBufferedAmountResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::DataConsumer_DumpResponse: {
      auto ptr = reinterpret_cast<FBS::DataConsumer::DumpResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::DataConsumer_GetStatsResponse: {
      auto ptr = reinterpret_cast<FBS::DataConsumer::GetStatsResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::DataConsumer_SetSubchannelsResponse: {
      auto ptr = reinterpret_cast<FBS::DataConsumer::SetSubchannelsResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::DataConsumer_AddSubchannelResponse: {
      auto ptr = reinterpret_cast<FBS::DataConsumer::AddSubchannelResponseT *>(value);
      delete ptr;
      break;
    }
    case Body::DataConsumer_RemoveSubchannelResponse: {
      auto ptr = reinterpret_cast<FBS::DataConsumer::RemoveSubchannelResponseT *>(value);
      delete ptr;
      break;
    }
    default: break;
  }
  value = nullptr;
  type = Body::NONE;
}

inline const ::flatbuffers::TypeTable *BodyTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SEQUENCE, 0, -1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 0 },
    { ::flatbuffers::ET_SEQUENCE, 0, 1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 2 },
    { ::flatbuffers::ET_SEQUENCE, 0, 3 },
    { ::flatbuffers::ET_SEQUENCE, 0, 4 },
    { ::flatbuffers::ET_SEQUENCE, 0, 5 },
    { ::flatbuffers::ET_SEQUENCE, 0, 6 },
    { ::flatbuffers::ET_SEQUENCE, 0, 7 },
    { ::flatbuffers::ET_SEQUENCE, 0, 8 },
    { ::flatbuffers::ET_SEQUENCE, 0, 9 },
    { ::flatbuffers::ET_SEQUENCE, 0, 10 },
    { ::flatbuffers::ET_SEQUENCE, 0, 11 },
    { ::flatbuffers::ET_SEQUENCE, 0, 12 },
    { ::flatbuffers::ET_SEQUENCE, 0, 13 },
    { ::flatbuffers::ET_SEQUENCE, 0, 14 },
    { ::flatbuffers::ET_SEQUENCE, 0, 15 },
    { ::flatbuffers::ET_SEQUENCE, 0, 16 },
    { ::flatbuffers::ET_SEQUENCE, 0, 17 },
    { ::flatbuffers::ET_SEQUENCE, 0, 18 },
    { ::flatbuffers::ET_SEQUENCE, 0, 19 },
    { ::flatbuffers::ET_SEQUENCE, 0, 20 },
    { ::flatbuffers::ET_SEQUENCE, 0, 21 },
    { ::flatbuffers::ET_SEQUENCE, 0, 22 },
    { ::flatbuffers::ET_SEQUENCE, 0, 23 },
    { ::flatbuffers::ET_SEQUENCE, 0, 24 },
    { ::flatbuffers::ET_SEQUENCE, 0, 25 },
    { ::flatbuffers::ET_SEQUENCE, 0, 26 },
    { ::flatbuffers::ET_SEQUENCE, 0, 27 },
    { ::flatbuffers::ET_SEQUENCE, 0, 28 },
    { ::flatbuffers::ET_SEQUENCE, 0, 29 },
    { ::flatbuffers::ET_SEQUENCE, 0, 30 },
    { ::flatbuffers::ET_SEQUENCE, 0, 31 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    FBS::Worker::DumpResponseTypeTable,
    FBS::Worker::ResourceUsageResponseTypeTable,
    FBS::WebRtcServer::DumpResponseTypeTable,
    FBS::Router::DumpResponseTypeTable,
    FBS::Transport::ProduceResponseTypeTable,
    FBS::Transport::ConsumeResponseTypeTable,
    FBS::Transport::RestartIceResponseTypeTable,
    FBS::PlainTransport::ConnectResponseTypeTable,
    FBS::PlainTransport::DumpResponseTypeTable,
    FBS::PlainTransport::GetStatsResponseTypeTable,
    FBS::PipeTransport::ConnectResponseTypeTable,
    FBS::PipeTransport::DumpResponseTypeTable,
    FBS::PipeTransport::GetStatsResponseTypeTable,
    FBS::DirectTransport::DumpResponseTypeTable,
    FBS::DirectTransport::GetStatsResponseTypeTable,
    FBS::WebRtcTransport::ConnectResponseTypeTable,
    FBS::WebRtcTransport::DumpResponseTypeTable,
    FBS::WebRtcTransport::GetStatsResponseTypeTable,
    FBS::Producer::DumpResponseTypeTable,
    FBS::Producer::GetStatsResponseTypeTable,
    FBS::Consumer::DumpResponseTypeTable,
    FBS::Consumer::GetStatsResponseTypeTable,
    FBS::Consumer::SetPreferredLayersResponseTypeTable,
    FBS::Consumer::SetPriorityResponseTypeTable,
    FBS::DataProducer::DumpResponseTypeTable,
    FBS::DataProducer::GetStatsResponseTypeTable,
    FBS::DataConsumer::GetBufferedAmountResponseTypeTable,
    FBS::DataConsumer::DumpResponseTypeTable,
    FBS::DataConsumer::GetStatsResponseTypeTable,
    FBS::DataConsumer::SetSubchannelsResponseTypeTable,
    FBS::DataConsumer::AddSubchannelResponseTypeTable,
    FBS::DataConsumer::RemoveSubchannelResponseTypeTable
  };
  static const char * const names[] = {
    "NONE",
    "Worker_DumpResponse",
    "Worker_ResourceUsageResponse",
    "WebRtcServer_DumpResponse",
    "Router_DumpResponse",
    "Transport_ProduceResponse",
    "Transport_ConsumeResponse",
    "Transport_RestartIceResponse",
    "PlainTransport_ConnectResponse",
    "PlainTransport_DumpResponse",
    "PlainTransport_GetStatsResponse",
    "PipeTransport_ConnectResponse",
    "PipeTransport_DumpResponse",
    "PipeTransport_GetStatsResponse",
    "DirectTransport_DumpResponse",
    "DirectTransport_GetStatsResponse",
    "WebRtcTransport_ConnectResponse",
    "WebRtcTransport_DumpResponse",
    "WebRtcTransport_GetStatsResponse",
    "Producer_DumpResponse",
    "Producer_GetStatsResponse",
    "Consumer_DumpResponse",
    "Consumer_GetStatsResponse",
    "Consumer_SetPreferredLayersResponse",
    "Consumer_SetPriorityResponse",
    "DataProducer_DumpResponse",
    "DataProducer_GetStatsResponse",
    "DataConsumer_GetBufferedAmountResponse",
    "DataConsumer_DumpResponse",
    "DataConsumer_GetStatsResponse",
    "DataConsumer_SetSubchannelsResponse",
    "DataConsumer_AddSubchannelResponse",
    "DataConsumer_RemoveSubchannelResponse"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_UNION, 33, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *ResponseTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_UINT, 0, -1 },
    { ::flatbuffers::ET_BOOL, 0, -1 },
    { ::flatbuffers::ET_UTYPE, 0, 0 },
    { ::flatbuffers::ET_SEQUENCE, 0, 0 },
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_STRING, 0, -1 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    FBS::Response::BodyTypeTable
  };
  static const char * const names[] = {
    "id",
    "accepted",
    "body_type",
    "body",
    "error",
    "reason"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 6, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

}  // namespace Response
}  // namespace FBS

#endif  // FLATBUFFERS_GENERATED_RESPONSE_FBS_RESPONSE_H_
