// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ROUTER_FBS_ROUTER_H_
#define FLATBUFFERS_GENERATED_ROUTER_FBS_ROUTER_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "activeSpeakerObserver_generated.h"
#include "audioLevelObserver_generated.h"
#include "common_generated.h"
#include "directTransport_generated.h"
#include "pipeTransport_generated.h"
#include "plainTransport_generated.h"
#include "transport_generated.h"
#include "webRtcTransport_generated.h"

namespace FBS {
namespace Router {

struct DumpResponse;
struct DumpResponseBuilder;
struct DumpResponseT;

struct CreatePipeTransportRequest;
struct CreatePipeTransportRequestBuilder;
struct CreatePipeTransportRequestT;

struct CreatePlainTransportRequest;
struct CreatePlainTransportRequestBuilder;
struct CreatePlainTransportRequestT;

struct CreateWebRtcTransportRequest;
struct CreateWebRtcTransportRequestBuilder;
struct CreateWebRtcTransportRequestT;

struct CreateDirectTransportRequest;
struct CreateDirectTransportRequestBuilder;
struct CreateDirectTransportRequestT;

struct CreateAudioLevelObserverRequest;
struct CreateAudioLevelObserverRequestBuilder;
struct CreateAudioLevelObserverRequestT;

struct CreateActiveSpeakerObserverRequest;
struct CreateActiveSpeakerObserverRequestBuilder;
struct CreateActiveSpeakerObserverRequestT;

struct CloseTransportRequest;
struct CloseTransportRequestBuilder;
struct CloseTransportRequestT;

struct CloseRtpObserverRequest;
struct CloseRtpObserverRequestBuilder;
struct CloseRtpObserverRequestT;

inline const ::flatbuffers::TypeTable *DumpResponseTypeTable();

inline const ::flatbuffers::TypeTable *CreatePipeTransportRequestTypeTable();

inline const ::flatbuffers::TypeTable *CreatePlainTransportRequestTypeTable();

inline const ::flatbuffers::TypeTable *CreateWebRtcTransportRequestTypeTable();

inline const ::flatbuffers::TypeTable *CreateDirectTransportRequestTypeTable();

inline const ::flatbuffers::TypeTable *CreateAudioLevelObserverRequestTypeTable();

inline const ::flatbuffers::TypeTable *CreateActiveSpeakerObserverRequestTypeTable();

inline const ::flatbuffers::TypeTable *CloseTransportRequestTypeTable();

inline const ::flatbuffers::TypeTable *CloseRtpObserverRequestTypeTable();

struct DumpResponseT : public ::flatbuffers::NativeTable {
  typedef DumpResponse TableType;
  std::string id{};
  std::vector<std::string> transportIds{};
  std::vector<std::string> rtpObserverIds{};
  std::vector<std::unique_ptr<FBS::Common::StringStringArrayT>> mapProducerIdConsumerIds{};
  std::vector<std::unique_ptr<FBS::Common::StringStringT>> mapConsumerIdProducerId{};
  std::vector<std::unique_ptr<FBS::Common::StringStringArrayT>> mapProducerIdObserverIds{};
  std::vector<std::unique_ptr<FBS::Common::StringStringArrayT>> mapDataProducerIdDataConsumerIds{};
  std::vector<std::unique_ptr<FBS::Common::StringStringT>> mapDataConsumerIdDataProducerId{};
  DumpResponseT() = default;
  DumpResponseT(const DumpResponseT &o);
  DumpResponseT(DumpResponseT&&) FLATBUFFERS_NOEXCEPT = default;
  DumpResponseT &operator=(DumpResponseT o) FLATBUFFERS_NOEXCEPT;
};

struct DumpResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DumpResponseT NativeTableType;
  typedef DumpResponseBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return DumpResponseTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TRANSPORTIDS = 6,
    VT_RTPOBSERVERIDS = 8,
    VT_MAPPRODUCERIDCONSUMERIDS = 10,
    VT_MAPCONSUMERIDPRODUCERID = 12,
    VT_MAPPRODUCERIDOBSERVERIDS = 14,
    VT_MAPDATAPRODUCERIDDATACONSUMERIDS = 16,
    VT_MAPDATACONSUMERIDDATAPRODUCERID = 18
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *transportIds() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_TRANSPORTIDS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *rtpObserverIds() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_RTPOBSERVERIDS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<FBS::Common::StringStringArray>> *mapProducerIdConsumerIds() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<FBS::Common::StringStringArray>> *>(VT_MAPPRODUCERIDCONSUMERIDS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<FBS::Common::StringString>> *mapConsumerIdProducerId() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<FBS::Common::StringString>> *>(VT_MAPCONSUMERIDPRODUCERID);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<FBS::Common::StringStringArray>> *mapProducerIdObserverIds() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<FBS::Common::StringStringArray>> *>(VT_MAPPRODUCERIDOBSERVERIDS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<FBS::Common::StringStringArray>> *mapDataProducerIdDataConsumerIds() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<FBS::Common::StringStringArray>> *>(VT_MAPDATAPRODUCERIDDATACONSUMERIDS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<FBS::Common::StringString>> *mapDataConsumerIdDataProducerId() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<FBS::Common::StringString>> *>(VT_MAPDATACONSUMERIDDATAPRODUCERID);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffsetRequired(verifier, VT_TRANSPORTIDS) &&
           verifier.VerifyVector(transportIds()) &&
           verifier.VerifyVectorOfStrings(transportIds()) &&
           VerifyOffsetRequired(verifier, VT_RTPOBSERVERIDS) &&
           verifier.VerifyVector(rtpObserverIds()) &&
           verifier.VerifyVectorOfStrings(rtpObserverIds()) &&
           VerifyOffsetRequired(verifier, VT_MAPPRODUCERIDCONSUMERIDS) &&
           verifier.VerifyVector(mapProducerIdConsumerIds()) &&
           verifier.VerifyVectorOfTables(mapProducerIdConsumerIds()) &&
           VerifyOffsetRequired(verifier, VT_MAPCONSUMERIDPRODUCERID) &&
           verifier.VerifyVector(mapConsumerIdProducerId()) &&
           verifier.VerifyVectorOfTables(mapConsumerIdProducerId()) &&
           VerifyOffsetRequired(verifier, VT_MAPPRODUCERIDOBSERVERIDS) &&
           verifier.VerifyVector(mapProducerIdObserverIds()) &&
           verifier.VerifyVectorOfTables(mapProducerIdObserverIds()) &&
           VerifyOffsetRequired(verifier, VT_MAPDATAPRODUCERIDDATACONSUMERIDS) &&
           verifier.VerifyVector(mapDataProducerIdDataConsumerIds()) &&
           verifier.VerifyVectorOfTables(mapDataProducerIdDataConsumerIds()) &&
           VerifyOffsetRequired(verifier, VT_MAPDATACONSUMERIDDATAPRODUCERID) &&
           verifier.VerifyVector(mapDataConsumerIdDataProducerId()) &&
           verifier.VerifyVectorOfTables(mapDataConsumerIdDataProducerId()) &&
           verifier.EndTable();
  }
  DumpResponseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(DumpResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<DumpResponse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DumpResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct DumpResponseBuilder {
  typedef DumpResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(DumpResponse::VT_ID, id);
  }
  void add_transportIds(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> transportIds) {
    fbb_.AddOffset(DumpResponse::VT_TRANSPORTIDS, transportIds);
  }
  void add_rtpObserverIds(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> rtpObserverIds) {
    fbb_.AddOffset(DumpResponse::VT_RTPOBSERVERIDS, rtpObserverIds);
  }
  void add_mapProducerIdConsumerIds(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FBS::Common::StringStringArray>>> mapProducerIdConsumerIds) {
    fbb_.AddOffset(DumpResponse::VT_MAPPRODUCERIDCONSUMERIDS, mapProducerIdConsumerIds);
  }
  void add_mapConsumerIdProducerId(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FBS::Common::StringString>>> mapConsumerIdProducerId) {
    fbb_.AddOffset(DumpResponse::VT_MAPCONSUMERIDPRODUCERID, mapConsumerIdProducerId);
  }
  void add_mapProducerIdObserverIds(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FBS::Common::StringStringArray>>> mapProducerIdObserverIds) {
    fbb_.AddOffset(DumpResponse::VT_MAPPRODUCERIDOBSERVERIDS, mapProducerIdObserverIds);
  }
  void add_mapDataProducerIdDataConsumerIds(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FBS::Common::StringStringArray>>> mapDataProducerIdDataConsumerIds) {
    fbb_.AddOffset(DumpResponse::VT_MAPDATAPRODUCERIDDATACONSUMERIDS, mapDataProducerIdDataConsumerIds);
  }
  void add_mapDataConsumerIdDataProducerId(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FBS::Common::StringString>>> mapDataConsumerIdDataProducerId) {
    fbb_.AddOffset(DumpResponse::VT_MAPDATACONSUMERIDDATAPRODUCERID, mapDataConsumerIdDataProducerId);
  }
  explicit DumpResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DumpResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DumpResponse>(end);
    fbb_.Required(o, DumpResponse::VT_ID);
    fbb_.Required(o, DumpResponse::VT_TRANSPORTIDS);
    fbb_.Required(o, DumpResponse::VT_RTPOBSERVERIDS);
    fbb_.Required(o, DumpResponse::VT_MAPPRODUCERIDCONSUMERIDS);
    fbb_.Required(o, DumpResponse::VT_MAPCONSUMERIDPRODUCERID);
    fbb_.Required(o, DumpResponse::VT_MAPPRODUCERIDOBSERVERIDS);
    fbb_.Required(o, DumpResponse::VT_MAPDATAPRODUCERIDDATACONSUMERIDS);
    fbb_.Required(o, DumpResponse::VT_MAPDATACONSUMERIDDATAPRODUCERID);
    return o;
  }
};

inline ::flatbuffers::Offset<DumpResponse> CreateDumpResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> transportIds = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> rtpObserverIds = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FBS::Common::StringStringArray>>> mapProducerIdConsumerIds = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FBS::Common::StringString>>> mapConsumerIdProducerId = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FBS::Common::StringStringArray>>> mapProducerIdObserverIds = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FBS::Common::StringStringArray>>> mapDataProducerIdDataConsumerIds = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FBS::Common::StringString>>> mapDataConsumerIdDataProducerId = 0) {
  DumpResponseBuilder builder_(_fbb);
  builder_.add_mapDataConsumerIdDataProducerId(mapDataConsumerIdDataProducerId);
  builder_.add_mapDataProducerIdDataConsumerIds(mapDataProducerIdDataConsumerIds);
  builder_.add_mapProducerIdObserverIds(mapProducerIdObserverIds);
  builder_.add_mapConsumerIdProducerId(mapConsumerIdProducerId);
  builder_.add_mapProducerIdConsumerIds(mapProducerIdConsumerIds);
  builder_.add_rtpObserverIds(rtpObserverIds);
  builder_.add_transportIds(transportIds);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DumpResponse> CreateDumpResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *transportIds = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *rtpObserverIds = nullptr,
    const std::vector<::flatbuffers::Offset<FBS::Common::StringStringArray>> *mapProducerIdConsumerIds = nullptr,
    const std::vector<::flatbuffers::Offset<FBS::Common::StringString>> *mapConsumerIdProducerId = nullptr,
    const std::vector<::flatbuffers::Offset<FBS::Common::StringStringArray>> *mapProducerIdObserverIds = nullptr,
    const std::vector<::flatbuffers::Offset<FBS::Common::StringStringArray>> *mapDataProducerIdDataConsumerIds = nullptr,
    const std::vector<::flatbuffers::Offset<FBS::Common::StringString>> *mapDataConsumerIdDataProducerId = nullptr) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto transportIds__ = transportIds ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*transportIds) : 0;
  auto rtpObserverIds__ = rtpObserverIds ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*rtpObserverIds) : 0;
  auto mapProducerIdConsumerIds__ = mapProducerIdConsumerIds ? _fbb.CreateVector<::flatbuffers::Offset<FBS::Common::StringStringArray>>(*mapProducerIdConsumerIds) : 0;
  auto mapConsumerIdProducerId__ = mapConsumerIdProducerId ? _fbb.CreateVector<::flatbuffers::Offset<FBS::Common::StringString>>(*mapConsumerIdProducerId) : 0;
  auto mapProducerIdObserverIds__ = mapProducerIdObserverIds ? _fbb.CreateVector<::flatbuffers::Offset<FBS::Common::StringStringArray>>(*mapProducerIdObserverIds) : 0;
  auto mapDataProducerIdDataConsumerIds__ = mapDataProducerIdDataConsumerIds ? _fbb.CreateVector<::flatbuffers::Offset<FBS::Common::StringStringArray>>(*mapDataProducerIdDataConsumerIds) : 0;
  auto mapDataConsumerIdDataProducerId__ = mapDataConsumerIdDataProducerId ? _fbb.CreateVector<::flatbuffers::Offset<FBS::Common::StringString>>(*mapDataConsumerIdDataProducerId) : 0;
  return FBS::Router::CreateDumpResponse(
      _fbb,
      id__,
      transportIds__,
      rtpObserverIds__,
      mapProducerIdConsumerIds__,
      mapConsumerIdProducerId__,
      mapProducerIdObserverIds__,
      mapDataProducerIdDataConsumerIds__,
      mapDataConsumerIdDataProducerId__);
}

::flatbuffers::Offset<DumpResponse> CreateDumpResponse(::flatbuffers::FlatBufferBuilder &_fbb, const DumpResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CreatePipeTransportRequestT : public ::flatbuffers::NativeTable {
  typedef CreatePipeTransportRequest TableType;
  std::string transportId{};
  std::unique_ptr<FBS::PipeTransport::PipeTransportOptionsT> options{};
  CreatePipeTransportRequestT() = default;
  CreatePipeTransportRequestT(const CreatePipeTransportRequestT &o);
  CreatePipeTransportRequestT(CreatePipeTransportRequestT&&) FLATBUFFERS_NOEXCEPT = default;
  CreatePipeTransportRequestT &operator=(CreatePipeTransportRequestT o) FLATBUFFERS_NOEXCEPT;
};

struct CreatePipeTransportRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CreatePipeTransportRequestT NativeTableType;
  typedef CreatePipeTransportRequestBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return CreatePipeTransportRequestTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TRANSPORTID = 4,
    VT_OPTIONS = 6
  };
  const ::flatbuffers::String *transportId() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TRANSPORTID);
  }
  const FBS::PipeTransport::PipeTransportOptions *options() const {
    return GetPointer<const FBS::PipeTransport::PipeTransportOptions *>(VT_OPTIONS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_TRANSPORTID) &&
           verifier.VerifyString(transportId()) &&
           VerifyOffsetRequired(verifier, VT_OPTIONS) &&
           verifier.VerifyTable(options()) &&
           verifier.EndTable();
  }
  CreatePipeTransportRequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CreatePipeTransportRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CreatePipeTransportRequest> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CreatePipeTransportRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CreatePipeTransportRequestBuilder {
  typedef CreatePipeTransportRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_transportId(::flatbuffers::Offset<::flatbuffers::String> transportId) {
    fbb_.AddOffset(CreatePipeTransportRequest::VT_TRANSPORTID, transportId);
  }
  void add_options(::flatbuffers::Offset<FBS::PipeTransport::PipeTransportOptions> options) {
    fbb_.AddOffset(CreatePipeTransportRequest::VT_OPTIONS, options);
  }
  explicit CreatePipeTransportRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CreatePipeTransportRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CreatePipeTransportRequest>(end);
    fbb_.Required(o, CreatePipeTransportRequest::VT_TRANSPORTID);
    fbb_.Required(o, CreatePipeTransportRequest::VT_OPTIONS);
    return o;
  }
};

inline ::flatbuffers::Offset<CreatePipeTransportRequest> CreateCreatePipeTransportRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> transportId = 0,
    ::flatbuffers::Offset<FBS::PipeTransport::PipeTransportOptions> options = 0) {
  CreatePipeTransportRequestBuilder builder_(_fbb);
  builder_.add_options(options);
  builder_.add_transportId(transportId);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CreatePipeTransportRequest> CreateCreatePipeTransportRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *transportId = nullptr,
    ::flatbuffers::Offset<FBS::PipeTransport::PipeTransportOptions> options = 0) {
  auto transportId__ = transportId ? _fbb.CreateString(transportId) : 0;
  return FBS::Router::CreateCreatePipeTransportRequest(
      _fbb,
      transportId__,
      options);
}

::flatbuffers::Offset<CreatePipeTransportRequest> CreateCreatePipeTransportRequest(::flatbuffers::FlatBufferBuilder &_fbb, const CreatePipeTransportRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CreatePlainTransportRequestT : public ::flatbuffers::NativeTable {
  typedef CreatePlainTransportRequest TableType;
  std::string transportId{};
  std::unique_ptr<FBS::PlainTransport::PlainTransportOptionsT> options{};
  CreatePlainTransportRequestT() = default;
  CreatePlainTransportRequestT(const CreatePlainTransportRequestT &o);
  CreatePlainTransportRequestT(CreatePlainTransportRequestT&&) FLATBUFFERS_NOEXCEPT = default;
  CreatePlainTransportRequestT &operator=(CreatePlainTransportRequestT o) FLATBUFFERS_NOEXCEPT;
};

struct CreatePlainTransportRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CreatePlainTransportRequestT NativeTableType;
  typedef CreatePlainTransportRequestBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return CreatePlainTransportRequestTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TRANSPORTID = 4,
    VT_OPTIONS = 6
  };
  const ::flatbuffers::String *transportId() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TRANSPORTID);
  }
  const FBS::PlainTransport::PlainTransportOptions *options() const {
    return GetPointer<const FBS::PlainTransport::PlainTransportOptions *>(VT_OPTIONS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_TRANSPORTID) &&
           verifier.VerifyString(transportId()) &&
           VerifyOffsetRequired(verifier, VT_OPTIONS) &&
           verifier.VerifyTable(options()) &&
           verifier.EndTable();
  }
  CreatePlainTransportRequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CreatePlainTransportRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CreatePlainTransportRequest> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CreatePlainTransportRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CreatePlainTransportRequestBuilder {
  typedef CreatePlainTransportRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_transportId(::flatbuffers::Offset<::flatbuffers::String> transportId) {
    fbb_.AddOffset(CreatePlainTransportRequest::VT_TRANSPORTID, transportId);
  }
  void add_options(::flatbuffers::Offset<FBS::PlainTransport::PlainTransportOptions> options) {
    fbb_.AddOffset(CreatePlainTransportRequest::VT_OPTIONS, options);
  }
  explicit CreatePlainTransportRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CreatePlainTransportRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CreatePlainTransportRequest>(end);
    fbb_.Required(o, CreatePlainTransportRequest::VT_TRANSPORTID);
    fbb_.Required(o, CreatePlainTransportRequest::VT_OPTIONS);
    return o;
  }
};

inline ::flatbuffers::Offset<CreatePlainTransportRequest> CreateCreatePlainTransportRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> transportId = 0,
    ::flatbuffers::Offset<FBS::PlainTransport::PlainTransportOptions> options = 0) {
  CreatePlainTransportRequestBuilder builder_(_fbb);
  builder_.add_options(options);
  builder_.add_transportId(transportId);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CreatePlainTransportRequest> CreateCreatePlainTransportRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *transportId = nullptr,
    ::flatbuffers::Offset<FBS::PlainTransport::PlainTransportOptions> options = 0) {
  auto transportId__ = transportId ? _fbb.CreateString(transportId) : 0;
  return FBS::Router::CreateCreatePlainTransportRequest(
      _fbb,
      transportId__,
      options);
}

::flatbuffers::Offset<CreatePlainTransportRequest> CreateCreatePlainTransportRequest(::flatbuffers::FlatBufferBuilder &_fbb, const CreatePlainTransportRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CreateWebRtcTransportRequestT : public ::flatbuffers::NativeTable {
  typedef CreateWebRtcTransportRequest TableType;
  std::string transportId{};
  std::unique_ptr<FBS::WebRtcTransport::WebRtcTransportOptionsT> options{};
  CreateWebRtcTransportRequestT() = default;
  CreateWebRtcTransportRequestT(const CreateWebRtcTransportRequestT &o);
  CreateWebRtcTransportRequestT(CreateWebRtcTransportRequestT&&) FLATBUFFERS_NOEXCEPT = default;
  CreateWebRtcTransportRequestT &operator=(CreateWebRtcTransportRequestT o) FLATBUFFERS_NOEXCEPT;
};

struct CreateWebRtcTransportRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CreateWebRtcTransportRequestT NativeTableType;
  typedef CreateWebRtcTransportRequestBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return CreateWebRtcTransportRequestTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TRANSPORTID = 4,
    VT_OPTIONS = 6
  };
  const ::flatbuffers::String *transportId() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TRANSPORTID);
  }
  const FBS::WebRtcTransport::WebRtcTransportOptions *options() const {
    return GetPointer<const FBS::WebRtcTransport::WebRtcTransportOptions *>(VT_OPTIONS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_TRANSPORTID) &&
           verifier.VerifyString(transportId()) &&
           VerifyOffsetRequired(verifier, VT_OPTIONS) &&
           verifier.VerifyTable(options()) &&
           verifier.EndTable();
  }
  CreateWebRtcTransportRequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CreateWebRtcTransportRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CreateWebRtcTransportRequest> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CreateWebRtcTransportRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CreateWebRtcTransportRequestBuilder {
  typedef CreateWebRtcTransportRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_transportId(::flatbuffers::Offset<::flatbuffers::String> transportId) {
    fbb_.AddOffset(CreateWebRtcTransportRequest::VT_TRANSPORTID, transportId);
  }
  void add_options(::flatbuffers::Offset<FBS::WebRtcTransport::WebRtcTransportOptions> options) {
    fbb_.AddOffset(CreateWebRtcTransportRequest::VT_OPTIONS, options);
  }
  explicit CreateWebRtcTransportRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CreateWebRtcTransportRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CreateWebRtcTransportRequest>(end);
    fbb_.Required(o, CreateWebRtcTransportRequest::VT_TRANSPORTID);
    fbb_.Required(o, CreateWebRtcTransportRequest::VT_OPTIONS);
    return o;
  }
};

inline ::flatbuffers::Offset<CreateWebRtcTransportRequest> CreateCreateWebRtcTransportRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> transportId = 0,
    ::flatbuffers::Offset<FBS::WebRtcTransport::WebRtcTransportOptions> options = 0) {
  CreateWebRtcTransportRequestBuilder builder_(_fbb);
  builder_.add_options(options);
  builder_.add_transportId(transportId);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CreateWebRtcTransportRequest> CreateCreateWebRtcTransportRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *transportId = nullptr,
    ::flatbuffers::Offset<FBS::WebRtcTransport::WebRtcTransportOptions> options = 0) {
  auto transportId__ = transportId ? _fbb.CreateString(transportId) : 0;
  return FBS::Router::CreateCreateWebRtcTransportRequest(
      _fbb,
      transportId__,
      options);
}

::flatbuffers::Offset<CreateWebRtcTransportRequest> CreateCreateWebRtcTransportRequest(::flatbuffers::FlatBufferBuilder &_fbb, const CreateWebRtcTransportRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CreateDirectTransportRequestT : public ::flatbuffers::NativeTable {
  typedef CreateDirectTransportRequest TableType;
  std::string transportId{};
  std::unique_ptr<FBS::DirectTransport::DirectTransportOptionsT> options{};
  CreateDirectTransportRequestT() = default;
  CreateDirectTransportRequestT(const CreateDirectTransportRequestT &o);
  CreateDirectTransportRequestT(CreateDirectTransportRequestT&&) FLATBUFFERS_NOEXCEPT = default;
  CreateDirectTransportRequestT &operator=(CreateDirectTransportRequestT o) FLATBUFFERS_NOEXCEPT;
};

struct CreateDirectTransportRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CreateDirectTransportRequestT NativeTableType;
  typedef CreateDirectTransportRequestBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return CreateDirectTransportRequestTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TRANSPORTID = 4,
    VT_OPTIONS = 6
  };
  const ::flatbuffers::String *transportId() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TRANSPORTID);
  }
  const FBS::DirectTransport::DirectTransportOptions *options() const {
    return GetPointer<const FBS::DirectTransport::DirectTransportOptions *>(VT_OPTIONS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_TRANSPORTID) &&
           verifier.VerifyString(transportId()) &&
           VerifyOffsetRequired(verifier, VT_OPTIONS) &&
           verifier.VerifyTable(options()) &&
           verifier.EndTable();
  }
  CreateDirectTransportRequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CreateDirectTransportRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CreateDirectTransportRequest> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CreateDirectTransportRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CreateDirectTransportRequestBuilder {
  typedef CreateDirectTransportRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_transportId(::flatbuffers::Offset<::flatbuffers::String> transportId) {
    fbb_.AddOffset(CreateDirectTransportRequest::VT_TRANSPORTID, transportId);
  }
  void add_options(::flatbuffers::Offset<FBS::DirectTransport::DirectTransportOptions> options) {
    fbb_.AddOffset(CreateDirectTransportRequest::VT_OPTIONS, options);
  }
  explicit CreateDirectTransportRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CreateDirectTransportRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CreateDirectTransportRequest>(end);
    fbb_.Required(o, CreateDirectTransportRequest::VT_TRANSPORTID);
    fbb_.Required(o, CreateDirectTransportRequest::VT_OPTIONS);
    return o;
  }
};

inline ::flatbuffers::Offset<CreateDirectTransportRequest> CreateCreateDirectTransportRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> transportId = 0,
    ::flatbuffers::Offset<FBS::DirectTransport::DirectTransportOptions> options = 0) {
  CreateDirectTransportRequestBuilder builder_(_fbb);
  builder_.add_options(options);
  builder_.add_transportId(transportId);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CreateDirectTransportRequest> CreateCreateDirectTransportRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *transportId = nullptr,
    ::flatbuffers::Offset<FBS::DirectTransport::DirectTransportOptions> options = 0) {
  auto transportId__ = transportId ? _fbb.CreateString(transportId) : 0;
  return FBS::Router::CreateCreateDirectTransportRequest(
      _fbb,
      transportId__,
      options);
}

::flatbuffers::Offset<CreateDirectTransportRequest> CreateCreateDirectTransportRequest(::flatbuffers::FlatBufferBuilder &_fbb, const CreateDirectTransportRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CreateAudioLevelObserverRequestT : public ::flatbuffers::NativeTable {
  typedef CreateAudioLevelObserverRequest TableType;
  std::string rtpObserverId{};
  std::unique_ptr<FBS::AudioLevelObserver::AudioLevelObserverOptionsT> options{};
  CreateAudioLevelObserverRequestT() = default;
  CreateAudioLevelObserverRequestT(const CreateAudioLevelObserverRequestT &o);
  CreateAudioLevelObserverRequestT(CreateAudioLevelObserverRequestT&&) FLATBUFFERS_NOEXCEPT = default;
  CreateAudioLevelObserverRequestT &operator=(CreateAudioLevelObserverRequestT o) FLATBUFFERS_NOEXCEPT;
};

struct CreateAudioLevelObserverRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CreateAudioLevelObserverRequestT NativeTableType;
  typedef CreateAudioLevelObserverRequestBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return CreateAudioLevelObserverRequestTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RTPOBSERVERID = 4,
    VT_OPTIONS = 6
  };
  const ::flatbuffers::String *rtpObserverId() const {
    return GetPointer<const ::flatbuffers::String *>(VT_RTPOBSERVERID);
  }
  const FBS::AudioLevelObserver::AudioLevelObserverOptions *options() const {
    return GetPointer<const FBS::AudioLevelObserver::AudioLevelObserverOptions *>(VT_OPTIONS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_RTPOBSERVERID) &&
           verifier.VerifyString(rtpObserverId()) &&
           VerifyOffsetRequired(verifier, VT_OPTIONS) &&
           verifier.VerifyTable(options()) &&
           verifier.EndTable();
  }
  CreateAudioLevelObserverRequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CreateAudioLevelObserverRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CreateAudioLevelObserverRequest> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CreateAudioLevelObserverRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CreateAudioLevelObserverRequestBuilder {
  typedef CreateAudioLevelObserverRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_rtpObserverId(::flatbuffers::Offset<::flatbuffers::String> rtpObserverId) {
    fbb_.AddOffset(CreateAudioLevelObserverRequest::VT_RTPOBSERVERID, rtpObserverId);
  }
  void add_options(::flatbuffers::Offset<FBS::AudioLevelObserver::AudioLevelObserverOptions> options) {
    fbb_.AddOffset(CreateAudioLevelObserverRequest::VT_OPTIONS, options);
  }
  explicit CreateAudioLevelObserverRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CreateAudioLevelObserverRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CreateAudioLevelObserverRequest>(end);
    fbb_.Required(o, CreateAudioLevelObserverRequest::VT_RTPOBSERVERID);
    fbb_.Required(o, CreateAudioLevelObserverRequest::VT_OPTIONS);
    return o;
  }
};

inline ::flatbuffers::Offset<CreateAudioLevelObserverRequest> CreateCreateAudioLevelObserverRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> rtpObserverId = 0,
    ::flatbuffers::Offset<FBS::AudioLevelObserver::AudioLevelObserverOptions> options = 0) {
  CreateAudioLevelObserverRequestBuilder builder_(_fbb);
  builder_.add_options(options);
  builder_.add_rtpObserverId(rtpObserverId);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CreateAudioLevelObserverRequest> CreateCreateAudioLevelObserverRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *rtpObserverId = nullptr,
    ::flatbuffers::Offset<FBS::AudioLevelObserver::AudioLevelObserverOptions> options = 0) {
  auto rtpObserverId__ = rtpObserverId ? _fbb.CreateString(rtpObserverId) : 0;
  return FBS::Router::CreateCreateAudioLevelObserverRequest(
      _fbb,
      rtpObserverId__,
      options);
}

::flatbuffers::Offset<CreateAudioLevelObserverRequest> CreateCreateAudioLevelObserverRequest(::flatbuffers::FlatBufferBuilder &_fbb, const CreateAudioLevelObserverRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CreateActiveSpeakerObserverRequestT : public ::flatbuffers::NativeTable {
  typedef CreateActiveSpeakerObserverRequest TableType;
  std::string rtpObserverId{};
  std::unique_ptr<FBS::ActiveSpeakerObserver::ActiveSpeakerObserverOptionsT> options{};
  CreateActiveSpeakerObserverRequestT() = default;
  CreateActiveSpeakerObserverRequestT(const CreateActiveSpeakerObserverRequestT &o);
  CreateActiveSpeakerObserverRequestT(CreateActiveSpeakerObserverRequestT&&) FLATBUFFERS_NOEXCEPT = default;
  CreateActiveSpeakerObserverRequestT &operator=(CreateActiveSpeakerObserverRequestT o) FLATBUFFERS_NOEXCEPT;
};

struct CreateActiveSpeakerObserverRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CreateActiveSpeakerObserverRequestT NativeTableType;
  typedef CreateActiveSpeakerObserverRequestBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return CreateActiveSpeakerObserverRequestTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RTPOBSERVERID = 4,
    VT_OPTIONS = 6
  };
  const ::flatbuffers::String *rtpObserverId() const {
    return GetPointer<const ::flatbuffers::String *>(VT_RTPOBSERVERID);
  }
  const FBS::ActiveSpeakerObserver::ActiveSpeakerObserverOptions *options() const {
    return GetPointer<const FBS::ActiveSpeakerObserver::ActiveSpeakerObserverOptions *>(VT_OPTIONS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_RTPOBSERVERID) &&
           verifier.VerifyString(rtpObserverId()) &&
           VerifyOffsetRequired(verifier, VT_OPTIONS) &&
           verifier.VerifyTable(options()) &&
           verifier.EndTable();
  }
  CreateActiveSpeakerObserverRequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CreateActiveSpeakerObserverRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CreateActiveSpeakerObserverRequest> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CreateActiveSpeakerObserverRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CreateActiveSpeakerObserverRequestBuilder {
  typedef CreateActiveSpeakerObserverRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_rtpObserverId(::flatbuffers::Offset<::flatbuffers::String> rtpObserverId) {
    fbb_.AddOffset(CreateActiveSpeakerObserverRequest::VT_RTPOBSERVERID, rtpObserverId);
  }
  void add_options(::flatbuffers::Offset<FBS::ActiveSpeakerObserver::ActiveSpeakerObserverOptions> options) {
    fbb_.AddOffset(CreateActiveSpeakerObserverRequest::VT_OPTIONS, options);
  }
  explicit CreateActiveSpeakerObserverRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CreateActiveSpeakerObserverRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CreateActiveSpeakerObserverRequest>(end);
    fbb_.Required(o, CreateActiveSpeakerObserverRequest::VT_RTPOBSERVERID);
    fbb_.Required(o, CreateActiveSpeakerObserverRequest::VT_OPTIONS);
    return o;
  }
};

inline ::flatbuffers::Offset<CreateActiveSpeakerObserverRequest> CreateCreateActiveSpeakerObserverRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> rtpObserverId = 0,
    ::flatbuffers::Offset<FBS::ActiveSpeakerObserver::ActiveSpeakerObserverOptions> options = 0) {
  CreateActiveSpeakerObserverRequestBuilder builder_(_fbb);
  builder_.add_options(options);
  builder_.add_rtpObserverId(rtpObserverId);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CreateActiveSpeakerObserverRequest> CreateCreateActiveSpeakerObserverRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *rtpObserverId = nullptr,
    ::flatbuffers::Offset<FBS::ActiveSpeakerObserver::ActiveSpeakerObserverOptions> options = 0) {
  auto rtpObserverId__ = rtpObserverId ? _fbb.CreateString(rtpObserverId) : 0;
  return FBS::Router::CreateCreateActiveSpeakerObserverRequest(
      _fbb,
      rtpObserverId__,
      options);
}

::flatbuffers::Offset<CreateActiveSpeakerObserverRequest> CreateCreateActiveSpeakerObserverRequest(::flatbuffers::FlatBufferBuilder &_fbb, const CreateActiveSpeakerObserverRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CloseTransportRequestT : public ::flatbuffers::NativeTable {
  typedef CloseTransportRequest TableType;
  std::string transportId{};
};

struct CloseTransportRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CloseTransportRequestT NativeTableType;
  typedef CloseTransportRequestBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return CloseTransportRequestTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TRANSPORTID = 4
  };
  const ::flatbuffers::String *transportId() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TRANSPORTID);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_TRANSPORTID) &&
           verifier.VerifyString(transportId()) &&
           verifier.EndTable();
  }
  CloseTransportRequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CloseTransportRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CloseTransportRequest> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CloseTransportRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CloseTransportRequestBuilder {
  typedef CloseTransportRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_transportId(::flatbuffers::Offset<::flatbuffers::String> transportId) {
    fbb_.AddOffset(CloseTransportRequest::VT_TRANSPORTID, transportId);
  }
  explicit CloseTransportRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CloseTransportRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CloseTransportRequest>(end);
    fbb_.Required(o, CloseTransportRequest::VT_TRANSPORTID);
    return o;
  }
};

inline ::flatbuffers::Offset<CloseTransportRequest> CreateCloseTransportRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> transportId = 0) {
  CloseTransportRequestBuilder builder_(_fbb);
  builder_.add_transportId(transportId);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CloseTransportRequest> CreateCloseTransportRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *transportId = nullptr) {
  auto transportId__ = transportId ? _fbb.CreateString(transportId) : 0;
  return FBS::Router::CreateCloseTransportRequest(
      _fbb,
      transportId__);
}

::flatbuffers::Offset<CloseTransportRequest> CreateCloseTransportRequest(::flatbuffers::FlatBufferBuilder &_fbb, const CloseTransportRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CloseRtpObserverRequestT : public ::flatbuffers::NativeTable {
  typedef CloseRtpObserverRequest TableType;
  std::string rtpObserverId{};
};

struct CloseRtpObserverRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CloseRtpObserverRequestT NativeTableType;
  typedef CloseRtpObserverRequestBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return CloseRtpObserverRequestTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RTPOBSERVERID = 4
  };
  const ::flatbuffers::String *rtpObserverId() const {
    return GetPointer<const ::flatbuffers::String *>(VT_RTPOBSERVERID);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_RTPOBSERVERID) &&
           verifier.VerifyString(rtpObserverId()) &&
           verifier.EndTable();
  }
  CloseRtpObserverRequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CloseRtpObserverRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CloseRtpObserverRequest> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CloseRtpObserverRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CloseRtpObserverRequestBuilder {
  typedef CloseRtpObserverRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_rtpObserverId(::flatbuffers::Offset<::flatbuffers::String> rtpObserverId) {
    fbb_.AddOffset(CloseRtpObserverRequest::VT_RTPOBSERVERID, rtpObserverId);
  }
  explicit CloseRtpObserverRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CloseRtpObserverRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CloseRtpObserverRequest>(end);
    fbb_.Required(o, CloseRtpObserverRequest::VT_RTPOBSERVERID);
    return o;
  }
};

inline ::flatbuffers::Offset<CloseRtpObserverRequest> CreateCloseRtpObserverRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> rtpObserverId = 0) {
  CloseRtpObserverRequestBuilder builder_(_fbb);
  builder_.add_rtpObserverId(rtpObserverId);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CloseRtpObserverRequest> CreateCloseRtpObserverRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *rtpObserverId = nullptr) {
  auto rtpObserverId__ = rtpObserverId ? _fbb.CreateString(rtpObserverId) : 0;
  return FBS::Router::CreateCloseRtpObserverRequest(
      _fbb,
      rtpObserverId__);
}

::flatbuffers::Offset<CloseRtpObserverRequest> CreateCloseRtpObserverRequest(::flatbuffers::FlatBufferBuilder &_fbb, const CloseRtpObserverRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline DumpResponseT::DumpResponseT(const DumpResponseT &o)
      : id(o.id),
        transportIds(o.transportIds),
        rtpObserverIds(o.rtpObserverIds) {
  mapProducerIdConsumerIds.reserve(o.mapProducerIdConsumerIds.size());
  for (const auto &mapProducerIdConsumerIds_ : o.mapProducerIdConsumerIds) { mapProducerIdConsumerIds.emplace_back((mapProducerIdConsumerIds_) ? new FBS::Common::StringStringArrayT(*mapProducerIdConsumerIds_) : nullptr); }
  mapConsumerIdProducerId.reserve(o.mapConsumerIdProducerId.size());
  for (const auto &mapConsumerIdProducerId_ : o.mapConsumerIdProducerId) { mapConsumerIdProducerId.emplace_back((mapConsumerIdProducerId_) ? new FBS::Common::StringStringT(*mapConsumerIdProducerId_) : nullptr); }
  mapProducerIdObserverIds.reserve(o.mapProducerIdObserverIds.size());
  for (const auto &mapProducerIdObserverIds_ : o.mapProducerIdObserverIds) { mapProducerIdObserverIds.emplace_back((mapProducerIdObserverIds_) ? new FBS::Common::StringStringArrayT(*mapProducerIdObserverIds_) : nullptr); }
  mapDataProducerIdDataConsumerIds.reserve(o.mapDataProducerIdDataConsumerIds.size());
  for (const auto &mapDataProducerIdDataConsumerIds_ : o.mapDataProducerIdDataConsumerIds) { mapDataProducerIdDataConsumerIds.emplace_back((mapDataProducerIdDataConsumerIds_) ? new FBS::Common::StringStringArrayT(*mapDataProducerIdDataConsumerIds_) : nullptr); }
  mapDataConsumerIdDataProducerId.reserve(o.mapDataConsumerIdDataProducerId.size());
  for (const auto &mapDataConsumerIdDataProducerId_ : o.mapDataConsumerIdDataProducerId) { mapDataConsumerIdDataProducerId.emplace_back((mapDataConsumerIdDataProducerId_) ? new FBS::Common::StringStringT(*mapDataConsumerIdDataProducerId_) : nullptr); }
}

inline DumpResponseT &DumpResponseT::operator=(DumpResponseT o) FLATBUFFERS_NOEXCEPT {
  std::swap(id, o.id);
  std::swap(transportIds, o.transportIds);
  std::swap(rtpObserverIds, o.rtpObserverIds);
  std::swap(mapProducerIdConsumerIds, o.mapProducerIdConsumerIds);
  std::swap(mapConsumerIdProducerId, o.mapConsumerIdProducerId);
  std::swap(mapProducerIdObserverIds, o.mapProducerIdObserverIds);
  std::swap(mapDataProducerIdDataConsumerIds, o.mapDataProducerIdDataConsumerIds);
  std::swap(mapDataConsumerIdDataProducerId, o.mapDataConsumerIdDataProducerId);
  return *this;
}

inline DumpResponseT *DumpResponse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<DumpResponseT>(new DumpResponseT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void DumpResponse::UnPackTo(DumpResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = id(); if (_e) _o->id = _e->str(); }
  { auto _e = transportIds(); if (_e) { _o->transportIds.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->transportIds[_i] = _e->Get(_i)->str(); } } else { _o->transportIds.resize(0); } }
  { auto _e = rtpObserverIds(); if (_e) { _o->rtpObserverIds.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->rtpObserverIds[_i] = _e->Get(_i)->str(); } } else { _o->rtpObserverIds.resize(0); } }
  { auto _e = mapProducerIdConsumerIds(); if (_e) { _o->mapProducerIdConsumerIds.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->mapProducerIdConsumerIds[_i]) { _e->Get(_i)->UnPackTo(_o->mapProducerIdConsumerIds[_i].get(), _resolver); } else { _o->mapProducerIdConsumerIds[_i] = std::unique_ptr<FBS::Common::StringStringArrayT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->mapProducerIdConsumerIds.resize(0); } }
  { auto _e = mapConsumerIdProducerId(); if (_e) { _o->mapConsumerIdProducerId.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->mapConsumerIdProducerId[_i]) { _e->Get(_i)->UnPackTo(_o->mapConsumerIdProducerId[_i].get(), _resolver); } else { _o->mapConsumerIdProducerId[_i] = std::unique_ptr<FBS::Common::StringStringT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->mapConsumerIdProducerId.resize(0); } }
  { auto _e = mapProducerIdObserverIds(); if (_e) { _o->mapProducerIdObserverIds.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->mapProducerIdObserverIds[_i]) { _e->Get(_i)->UnPackTo(_o->mapProducerIdObserverIds[_i].get(), _resolver); } else { _o->mapProducerIdObserverIds[_i] = std::unique_ptr<FBS::Common::StringStringArrayT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->mapProducerIdObserverIds.resize(0); } }
  { auto _e = mapDataProducerIdDataConsumerIds(); if (_e) { _o->mapDataProducerIdDataConsumerIds.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->mapDataProducerIdDataConsumerIds[_i]) { _e->Get(_i)->UnPackTo(_o->mapDataProducerIdDataConsumerIds[_i].get(), _resolver); } else { _o->mapDataProducerIdDataConsumerIds[_i] = std::unique_ptr<FBS::Common::StringStringArrayT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->mapDataProducerIdDataConsumerIds.resize(0); } }
  { auto _e = mapDataConsumerIdDataProducerId(); if (_e) { _o->mapDataConsumerIdDataProducerId.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->mapDataConsumerIdDataProducerId[_i]) { _e->Get(_i)->UnPackTo(_o->mapDataConsumerIdDataProducerId[_i].get(), _resolver); } else { _o->mapDataConsumerIdDataProducerId[_i] = std::unique_ptr<FBS::Common::StringStringT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->mapDataConsumerIdDataProducerId.resize(0); } }
}

inline ::flatbuffers::Offset<DumpResponse> DumpResponse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DumpResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateDumpResponse(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<DumpResponse> CreateDumpResponse(::flatbuffers::FlatBufferBuilder &_fbb, const DumpResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const DumpResponseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _id = _fbb.CreateString(_o->id);
  auto _transportIds = _fbb.CreateVectorOfStrings(_o->transportIds);
  auto _rtpObserverIds = _fbb.CreateVectorOfStrings(_o->rtpObserverIds);
  auto _mapProducerIdConsumerIds = _fbb.CreateVector<::flatbuffers::Offset<FBS::Common::StringStringArray>> (_o->mapProducerIdConsumerIds.size(), [](size_t i, _VectorArgs *__va) { return CreateStringStringArray(*__va->__fbb, __va->__o->mapProducerIdConsumerIds[i].get(), __va->__rehasher); }, &_va );
  auto _mapConsumerIdProducerId = _fbb.CreateVector<::flatbuffers::Offset<FBS::Common::StringString>> (_o->mapConsumerIdProducerId.size(), [](size_t i, _VectorArgs *__va) { return CreateStringString(*__va->__fbb, __va->__o->mapConsumerIdProducerId[i].get(), __va->__rehasher); }, &_va );
  auto _mapProducerIdObserverIds = _fbb.CreateVector<::flatbuffers::Offset<FBS::Common::StringStringArray>> (_o->mapProducerIdObserverIds.size(), [](size_t i, _VectorArgs *__va) { return CreateStringStringArray(*__va->__fbb, __va->__o->mapProducerIdObserverIds[i].get(), __va->__rehasher); }, &_va );
  auto _mapDataProducerIdDataConsumerIds = _fbb.CreateVector<::flatbuffers::Offset<FBS::Common::StringStringArray>> (_o->mapDataProducerIdDataConsumerIds.size(), [](size_t i, _VectorArgs *__va) { return CreateStringStringArray(*__va->__fbb, __va->__o->mapDataProducerIdDataConsumerIds[i].get(), __va->__rehasher); }, &_va );
  auto _mapDataConsumerIdDataProducerId = _fbb.CreateVector<::flatbuffers::Offset<FBS::Common::StringString>> (_o->mapDataConsumerIdDataProducerId.size(), [](size_t i, _VectorArgs *__va) { return CreateStringString(*__va->__fbb, __va->__o->mapDataConsumerIdDataProducerId[i].get(), __va->__rehasher); }, &_va );
  return FBS::Router::CreateDumpResponse(
      _fbb,
      _id,
      _transportIds,
      _rtpObserverIds,
      _mapProducerIdConsumerIds,
      _mapConsumerIdProducerId,
      _mapProducerIdObserverIds,
      _mapDataProducerIdDataConsumerIds,
      _mapDataConsumerIdDataProducerId);
}

inline CreatePipeTransportRequestT::CreatePipeTransportRequestT(const CreatePipeTransportRequestT &o)
      : transportId(o.transportId),
        options((o.options) ? new FBS::PipeTransport::PipeTransportOptionsT(*o.options) : nullptr) {
}

inline CreatePipeTransportRequestT &CreatePipeTransportRequestT::operator=(CreatePipeTransportRequestT o) FLATBUFFERS_NOEXCEPT {
  std::swap(transportId, o.transportId);
  std::swap(options, o.options);
  return *this;
}

inline CreatePipeTransportRequestT *CreatePipeTransportRequest::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CreatePipeTransportRequestT>(new CreatePipeTransportRequestT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CreatePipeTransportRequest::UnPackTo(CreatePipeTransportRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = transportId(); if (_e) _o->transportId = _e->str(); }
  { auto _e = options(); if (_e) { if(_o->options) { _e->UnPackTo(_o->options.get(), _resolver); } else { _o->options = std::unique_ptr<FBS::PipeTransport::PipeTransportOptionsT>(_e->UnPack(_resolver)); } } else if (_o->options) { _o->options.reset(); } }
}

inline ::flatbuffers::Offset<CreatePipeTransportRequest> CreatePipeTransportRequest::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CreatePipeTransportRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateCreatePipeTransportRequest(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CreatePipeTransportRequest> CreateCreatePipeTransportRequest(::flatbuffers::FlatBufferBuilder &_fbb, const CreatePipeTransportRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CreatePipeTransportRequestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _transportId = _fbb.CreateString(_o->transportId);
  auto _options = _o->options ? CreatePipeTransportOptions(_fbb, _o->options.get(), _rehasher) : 0;
  return FBS::Router::CreateCreatePipeTransportRequest(
      _fbb,
      _transportId,
      _options);
}

inline CreatePlainTransportRequestT::CreatePlainTransportRequestT(const CreatePlainTransportRequestT &o)
      : transportId(o.transportId),
        options((o.options) ? new FBS::PlainTransport::PlainTransportOptionsT(*o.options) : nullptr) {
}

inline CreatePlainTransportRequestT &CreatePlainTransportRequestT::operator=(CreatePlainTransportRequestT o) FLATBUFFERS_NOEXCEPT {
  std::swap(transportId, o.transportId);
  std::swap(options, o.options);
  return *this;
}

inline CreatePlainTransportRequestT *CreatePlainTransportRequest::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CreatePlainTransportRequestT>(new CreatePlainTransportRequestT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CreatePlainTransportRequest::UnPackTo(CreatePlainTransportRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = transportId(); if (_e) _o->transportId = _e->str(); }
  { auto _e = options(); if (_e) { if(_o->options) { _e->UnPackTo(_o->options.get(), _resolver); } else { _o->options = std::unique_ptr<FBS::PlainTransport::PlainTransportOptionsT>(_e->UnPack(_resolver)); } } else if (_o->options) { _o->options.reset(); } }
}

inline ::flatbuffers::Offset<CreatePlainTransportRequest> CreatePlainTransportRequest::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CreatePlainTransportRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateCreatePlainTransportRequest(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CreatePlainTransportRequest> CreateCreatePlainTransportRequest(::flatbuffers::FlatBufferBuilder &_fbb, const CreatePlainTransportRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CreatePlainTransportRequestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _transportId = _fbb.CreateString(_o->transportId);
  auto _options = _o->options ? CreatePlainTransportOptions(_fbb, _o->options.get(), _rehasher) : 0;
  return FBS::Router::CreateCreatePlainTransportRequest(
      _fbb,
      _transportId,
      _options);
}

inline CreateWebRtcTransportRequestT::CreateWebRtcTransportRequestT(const CreateWebRtcTransportRequestT &o)
      : transportId(o.transportId),
        options((o.options) ? new FBS::WebRtcTransport::WebRtcTransportOptionsT(*o.options) : nullptr) {
}

inline CreateWebRtcTransportRequestT &CreateWebRtcTransportRequestT::operator=(CreateWebRtcTransportRequestT o) FLATBUFFERS_NOEXCEPT {
  std::swap(transportId, o.transportId);
  std::swap(options, o.options);
  return *this;
}

inline CreateWebRtcTransportRequestT *CreateWebRtcTransportRequest::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CreateWebRtcTransportRequestT>(new CreateWebRtcTransportRequestT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CreateWebRtcTransportRequest::UnPackTo(CreateWebRtcTransportRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = transportId(); if (_e) _o->transportId = _e->str(); }
  { auto _e = options(); if (_e) { if(_o->options) { _e->UnPackTo(_o->options.get(), _resolver); } else { _o->options = std::unique_ptr<FBS::WebRtcTransport::WebRtcTransportOptionsT>(_e->UnPack(_resolver)); } } else if (_o->options) { _o->options.reset(); } }
}

inline ::flatbuffers::Offset<CreateWebRtcTransportRequest> CreateWebRtcTransportRequest::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CreateWebRtcTransportRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateCreateWebRtcTransportRequest(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CreateWebRtcTransportRequest> CreateCreateWebRtcTransportRequest(::flatbuffers::FlatBufferBuilder &_fbb, const CreateWebRtcTransportRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CreateWebRtcTransportRequestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _transportId = _fbb.CreateString(_o->transportId);
  auto _options = _o->options ? CreateWebRtcTransportOptions(_fbb, _o->options.get(), _rehasher) : 0;
  return FBS::Router::CreateCreateWebRtcTransportRequest(
      _fbb,
      _transportId,
      _options);
}

inline CreateDirectTransportRequestT::CreateDirectTransportRequestT(const CreateDirectTransportRequestT &o)
      : transportId(o.transportId),
        options((o.options) ? new FBS::DirectTransport::DirectTransportOptionsT(*o.options) : nullptr) {
}

inline CreateDirectTransportRequestT &CreateDirectTransportRequestT::operator=(CreateDirectTransportRequestT o) FLATBUFFERS_NOEXCEPT {
  std::swap(transportId, o.transportId);
  std::swap(options, o.options);
  return *this;
}

inline CreateDirectTransportRequestT *CreateDirectTransportRequest::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CreateDirectTransportRequestT>(new CreateDirectTransportRequestT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CreateDirectTransportRequest::UnPackTo(CreateDirectTransportRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = transportId(); if (_e) _o->transportId = _e->str(); }
  { auto _e = options(); if (_e) { if(_o->options) { _e->UnPackTo(_o->options.get(), _resolver); } else { _o->options = std::unique_ptr<FBS::DirectTransport::DirectTransportOptionsT>(_e->UnPack(_resolver)); } } else if (_o->options) { _o->options.reset(); } }
}

inline ::flatbuffers::Offset<CreateDirectTransportRequest> CreateDirectTransportRequest::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CreateDirectTransportRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateCreateDirectTransportRequest(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CreateDirectTransportRequest> CreateCreateDirectTransportRequest(::flatbuffers::FlatBufferBuilder &_fbb, const CreateDirectTransportRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CreateDirectTransportRequestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _transportId = _fbb.CreateString(_o->transportId);
  auto _options = _o->options ? CreateDirectTransportOptions(_fbb, _o->options.get(), _rehasher) : 0;
  return FBS::Router::CreateCreateDirectTransportRequest(
      _fbb,
      _transportId,
      _options);
}

inline CreateAudioLevelObserverRequestT::CreateAudioLevelObserverRequestT(const CreateAudioLevelObserverRequestT &o)
      : rtpObserverId(o.rtpObserverId),
        options((o.options) ? new FBS::AudioLevelObserver::AudioLevelObserverOptionsT(*o.options) : nullptr) {
}

inline CreateAudioLevelObserverRequestT &CreateAudioLevelObserverRequestT::operator=(CreateAudioLevelObserverRequestT o) FLATBUFFERS_NOEXCEPT {
  std::swap(rtpObserverId, o.rtpObserverId);
  std::swap(options, o.options);
  return *this;
}

inline CreateAudioLevelObserverRequestT *CreateAudioLevelObserverRequest::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CreateAudioLevelObserverRequestT>(new CreateAudioLevelObserverRequestT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CreateAudioLevelObserverRequest::UnPackTo(CreateAudioLevelObserverRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = rtpObserverId(); if (_e) _o->rtpObserverId = _e->str(); }
  { auto _e = options(); if (_e) { if(_o->options) { _e->UnPackTo(_o->options.get(), _resolver); } else { _o->options = std::unique_ptr<FBS::AudioLevelObserver::AudioLevelObserverOptionsT>(_e->UnPack(_resolver)); } } else if (_o->options) { _o->options.reset(); } }
}

inline ::flatbuffers::Offset<CreateAudioLevelObserverRequest> CreateAudioLevelObserverRequest::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CreateAudioLevelObserverRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateCreateAudioLevelObserverRequest(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CreateAudioLevelObserverRequest> CreateCreateAudioLevelObserverRequest(::flatbuffers::FlatBufferBuilder &_fbb, const CreateAudioLevelObserverRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CreateAudioLevelObserverRequestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _rtpObserverId = _fbb.CreateString(_o->rtpObserverId);
  auto _options = _o->options ? CreateAudioLevelObserverOptions(_fbb, _o->options.get(), _rehasher) : 0;
  return FBS::Router::CreateCreateAudioLevelObserverRequest(
      _fbb,
      _rtpObserverId,
      _options);
}

inline CreateActiveSpeakerObserverRequestT::CreateActiveSpeakerObserverRequestT(const CreateActiveSpeakerObserverRequestT &o)
      : rtpObserverId(o.rtpObserverId),
        options((o.options) ? new FBS::ActiveSpeakerObserver::ActiveSpeakerObserverOptionsT(*o.options) : nullptr) {
}

inline CreateActiveSpeakerObserverRequestT &CreateActiveSpeakerObserverRequestT::operator=(CreateActiveSpeakerObserverRequestT o) FLATBUFFERS_NOEXCEPT {
  std::swap(rtpObserverId, o.rtpObserverId);
  std::swap(options, o.options);
  return *this;
}

inline CreateActiveSpeakerObserverRequestT *CreateActiveSpeakerObserverRequest::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CreateActiveSpeakerObserverRequestT>(new CreateActiveSpeakerObserverRequestT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CreateActiveSpeakerObserverRequest::UnPackTo(CreateActiveSpeakerObserverRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = rtpObserverId(); if (_e) _o->rtpObserverId = _e->str(); }
  { auto _e = options(); if (_e) { if(_o->options) { _e->UnPackTo(_o->options.get(), _resolver); } else { _o->options = std::unique_ptr<FBS::ActiveSpeakerObserver::ActiveSpeakerObserverOptionsT>(_e->UnPack(_resolver)); } } else if (_o->options) { _o->options.reset(); } }
}

inline ::flatbuffers::Offset<CreateActiveSpeakerObserverRequest> CreateActiveSpeakerObserverRequest::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CreateActiveSpeakerObserverRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateCreateActiveSpeakerObserverRequest(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CreateActiveSpeakerObserverRequest> CreateCreateActiveSpeakerObserverRequest(::flatbuffers::FlatBufferBuilder &_fbb, const CreateActiveSpeakerObserverRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CreateActiveSpeakerObserverRequestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _rtpObserverId = _fbb.CreateString(_o->rtpObserverId);
  auto _options = _o->options ? CreateActiveSpeakerObserverOptions(_fbb, _o->options.get(), _rehasher) : 0;
  return FBS::Router::CreateCreateActiveSpeakerObserverRequest(
      _fbb,
      _rtpObserverId,
      _options);
}

inline CloseTransportRequestT *CloseTransportRequest::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CloseTransportRequestT>(new CloseTransportRequestT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CloseTransportRequest::UnPackTo(CloseTransportRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = transportId(); if (_e) _o->transportId = _e->str(); }
}

inline ::flatbuffers::Offset<CloseTransportRequest> CloseTransportRequest::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CloseTransportRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateCloseTransportRequest(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CloseTransportRequest> CreateCloseTransportRequest(::flatbuffers::FlatBufferBuilder &_fbb, const CloseTransportRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CloseTransportRequestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _transportId = _fbb.CreateString(_o->transportId);
  return FBS::Router::CreateCloseTransportRequest(
      _fbb,
      _transportId);
}

inline CloseRtpObserverRequestT *CloseRtpObserverRequest::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CloseRtpObserverRequestT>(new CloseRtpObserverRequestT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CloseRtpObserverRequest::UnPackTo(CloseRtpObserverRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = rtpObserverId(); if (_e) _o->rtpObserverId = _e->str(); }
}

inline ::flatbuffers::Offset<CloseRtpObserverRequest> CloseRtpObserverRequest::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CloseRtpObserverRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateCloseRtpObserverRequest(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CloseRtpObserverRequest> CreateCloseRtpObserverRequest(::flatbuffers::FlatBufferBuilder &_fbb, const CloseRtpObserverRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CloseRtpObserverRequestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _rtpObserverId = _fbb.CreateString(_o->rtpObserverId);
  return FBS::Router::CreateCloseRtpObserverRequest(
      _fbb,
      _rtpObserverId);
}

inline const ::flatbuffers::TypeTable *DumpResponseTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_STRING, 1, -1 },
    { ::flatbuffers::ET_STRING, 1, -1 },
    { ::flatbuffers::ET_SEQUENCE, 1, 0 },
    { ::flatbuffers::ET_SEQUENCE, 1, 1 },
    { ::flatbuffers::ET_SEQUENCE, 1, 0 },
    { ::flatbuffers::ET_SEQUENCE, 1, 0 },
    { ::flatbuffers::ET_SEQUENCE, 1, 1 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    FBS::Common::StringStringArrayTypeTable,
    FBS::Common::StringStringTypeTable
  };
  static const char * const names[] = {
    "id",
    "transportIds",
    "rtpObserverIds",
    "mapProducerIdConsumerIds",
    "mapConsumerIdProducerId",
    "mapProducerIdObserverIds",
    "mapDataProducerIdDataConsumerIds",
    "mapDataConsumerIdDataProducerId"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 8, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *CreatePipeTransportRequestTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    FBS::PipeTransport::PipeTransportOptionsTypeTable
  };
  static const char * const names[] = {
    "transportId",
    "options"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *CreatePlainTransportRequestTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    FBS::PlainTransport::PlainTransportOptionsTypeTable
  };
  static const char * const names[] = {
    "transportId",
    "options"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *CreateWebRtcTransportRequestTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    FBS::WebRtcTransport::WebRtcTransportOptionsTypeTable
  };
  static const char * const names[] = {
    "transportId",
    "options"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *CreateDirectTransportRequestTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    FBS::DirectTransport::DirectTransportOptionsTypeTable
  };
  static const char * const names[] = {
    "transportId",
    "options"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *CreateAudioLevelObserverRequestTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    FBS::AudioLevelObserver::AudioLevelObserverOptionsTypeTable
  };
  static const char * const names[] = {
    "rtpObserverId",
    "options"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *CreateActiveSpeakerObserverRequestTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    FBS::ActiveSpeakerObserver::ActiveSpeakerObserverOptionsTypeTable
  };
  static const char * const names[] = {
    "rtpObserverId",
    "options"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *CloseTransportRequestTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 }
  };
  static const char * const names[] = {
    "transportId"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 1, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *CloseRtpObserverRequestTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 }
  };
  static const char * const names[] = {
    "rtpObserverId"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 1, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

}  // namespace Router
}  // namespace FBS

#endif  // FLATBUFFERS_GENERATED_ROUTER_FBS_ROUTER_H_
